--
-- Task module — lifecycle, audit trail and the defects the proposal set out to
-- fix (§1.3 W3/W4/W5/W8, §4, §5).
--
-- Every assertion here maps to a defect of the original 7-column table:
--   W3  un-checking a task destroyed the completion record
--   W4  postponing was silent and lossy
--   W5  there was no creation timestamp
--   W8  deleting a contact destroyed its tasks
--
begin;

select plan(38);

--
-- Fixtures. Avatar/logo lookups do outbound HTTP, so the triggers that perform
-- them are disabled for the transaction (rolled back with everything else).
--
alter table public.contacts disable trigger "20_contact_saved";

-- `on_auth_user_created` mirrors the user into public.sales, so the fixture
-- goes through the same path a real signup does. The id is then pinned to a
-- fixed value to keep the assertions readable (`sales.id` is GENERATED BY
-- DEFAULT, so an explicit value is allowed).
insert into auth.users (id, email, raw_user_meta_data)
values ('11111111-1111-1111-1111-111111111111', 'owner@test.local',
        '{"first_name":"Test","last_name":"Owner"}'::jsonb);

update public.sales set id = 9001, role = 'admin'
where user_id = '11111111-1111-1111-1111-111111111111';

insert into public.contacts (id, first_name, last_name, sales_id)
values (9001, 'Ana', 'Ruiz', 9001);

-- Act as that user for the rest of the transaction: `current_sale_id()` reads
-- the JWT claims, so every trigger attributes its events to sale 9001.
select set_config(
    'request.jwt.claims',
    '{"sub":"11111111-1111-1111-1111-111111111111","role":"authenticated"}',
    true);

--
-- 1. Creation through the LEGACY shape the current frontend still sends.
--    The defaults trigger must fill the whole new model.
--
insert into public.tasks (id, contact_id, text, type, due_date, sales_id)
values (9001, 9001, 'Llamar a Ana sobre la renovación', 'call',
        '2026-09-01 09:00:00+00', 9001);

select is(
    (select title from public.tasks where id = 9001),
    'Llamar a Ana sobre la renovación',
    'title is backfilled from the legacy text column');

select is(
    (select s.key from public.tasks t join public.task_statuses s on s.id = t.status_id
      where t.id = 9001),
    'pending',
    'a new task starts in pending (§4.1)');

select is(
    (select p.key from public.tasks t join public.task_priorities p on p.id = t.priority_id
      where t.id = 9001),
    'normal',
    'priority defaults to normal');

select is(
    (select ty.key from public.tasks t join public.task_types ty on ty.id = t.task_type_id
      where t.id = 9001),
    'call',
    'the legacy type string resolves to a task_types row (fixes W11)');

select is(
    (select owner_sales_id from public.tasks where id = 9001), 9001::bigint,
    'owner is derived from the legacy sales_id');

select is(
    (select created_by from public.tasks where id = 9001), 9001::bigint,
    'created_by is recorded');

select ok(
    (select created_at from public.tasks where id = 9001) is not null,
    'created_at exists at last (fixes W5)');

--
-- 2. Creation emits an event, an owner assignment and a primary contact link.
--
select is(
    (select count(*)::int from public.task_events
      where task_id = 9001 and event_type = 'task.created'),
    1,
    'creation emits exactly one task.created event (§5.4)');

select is(
    (select actor_sales_id from public.task_events
      where task_id = 9001 and event_type = 'task.created'),
    9001::bigint,
    'the event is attributed to the acting user, resolved server-side (§5.1)');

select is(
    (select seq from public.task_events where task_id = 9001 and event_type = 'task.created'),
    1::bigint,
    'the per-task sequence starts at 1');

select is(
    (select count(*)::int from public.task_assignments
      where task_id = 9001 and role = 'owner' and unassigned_at is null),
    1,
    'an active owner assignment is seeded (§7.2)');

select is(
    (select entity_type::text from public.task_links
      where task_id = 9001 and is_primary and unlinked_at is null),
    'contact',
    'the contact becomes the primary link (§14.2)');

--
-- 3. The state machine is the only write path (§4.5).
--
select throws_ok(
    $$ update public.tasks
          set status_id = (select id from public.task_statuses where key = 'completed')
        where id = 9001 $$,
    '23514',
    null,
    'a direct status update is rejected — transitions go through transition_task() (§4.5)');

select throws_ok(
    $$ select public.transition_task(9001, 'archived') $$,
    '23514',
    null,
    'pending -> archived is an illegal transition (§4.2)');

select throws_ok(
    $$ select public.transition_task(9001, 'canceled') $$,
    '23514',
    null,
    'cancelling without a reason is rejected (§4.4)');

select lives_ok(
    $$ select public.transition_task(9001, 'in_progress') $$,
    'pending -> in_progress is legal');

select is(
    (select s.key from public.tasks t join public.task_statuses s on s.id = t.status_id
      where t.id = 9001),
    'in_progress',
    'the task is now in progress');

select ok(
    (select start_at from public.tasks where id = 9001) is not null,
    'start_at is stamped on the first start (§4.4)');

select is(
    (select count(*)::int from public.task_events
      where task_id = 9001 and event_type = 'task.started'),
    1,
    'starting emits task.started');

--
-- 4. Completion, and the W3 fix: reopening must NOT erase the completion.
--
select lives_ok(
    $$ select public.transition_task(9001, 'completed') $$,
    'in_progress -> completed is legal');

select ok(
    (select completed_at from public.tasks where id = 9001) is not null,
    'completed_at is set');

select is(
    (select completed_by from public.tasks where id = 9001), 9001::bigint,
    'completed_by records WHO completed it (the original schema could not)');

select ok(
    (select done_date from public.tasks where id = 9001) is not null,
    'the legacy done_date shim stays in sync for the current frontend');

select lives_ok(
    $$ select public.transition_task(9001, 'in_progress', 'el cliente reabrió el caso') $$,
    'completed -> in_progress (reopen) is legal');

select ok(
    (select completed_at from public.tasks where id = 9001) is null,
    'reopening clears completed_at on the row');

select is(
    (select count(*)::int from public.task_events
      where task_id = 9001 and event_type = 'task.completed'),
    1,
    'the completion event SURVIVES the reopen — history is never lost (fixes W3)');

select is(
    (select metadata ->> 'reason' from public.task_events
      where task_id = 9001 and event_type = 'task.reopened'),
    'el cliente reabrió el caso',
    'the reopen reason is recorded on the event (§4.4)');

--
-- 5. Rescheduling is counted and explained (fixes W4).
--
update public.tasks set due_date = '2026-09-08 09:00:00+00' where id = 9001;

select is(
    (select reschedule_count from public.tasks where id = 9001), 1,
    'reschedule_count is incremented (fixes W4)');

select is(
    (select count(*)::int from public.task_events
      where task_id = 9001 and event_type = 'task.rescheduled'),
    1,
    'rescheduling emits its own event');

select is(
    (select (metadata ->> 'delta_seconds')::numeric from public.task_events
      where task_id = 9001 and event_type = 'task.rescheduled'),
    604800::numeric,
    'the event records HOW FAR the task moved (+7 days)');

--
-- 6. The event stream is append-only (§5.5).
--
select throws_ok(
    $$ update public.task_events set note = 'tampered' where task_id = 9001 $$,
    '42501',
    null,
    'task_events cannot be updated — not even by the table owner (§5.5)');

select throws_ok(
    $$ delete from public.task_events where task_id = 9001 $$,
    '42501',
    null,
    'task_events cannot be deleted (§5.5)');

--
-- 7. Deletion is soft, and deleting the contact no longer destroys the task
--    (fixes W8 / B5).
--
delete from public.tasks where id = 9001;

select is(
    (select count(*)::int from public.tasks where id = 9001), 1,
    'a DELETE is converted into a soft delete — the row survives (fixes W8)');

select ok(
    (select deleted_at from public.tasks where id = 9001) is not null,
    'deleted_at is stamped');

select is(
    (select count(*)::int from public.task_events
      where task_id = 9001 and event_type = 'task.deleted'),
    1,
    'the deletion is itself an auditable event');

--
-- 8. The client performs the soft delete as an explicit UPDATE (a suppressed
--    DELETE returns no rows through PostgREST). Both paths must attribute it.
--
insert into public.tasks (id, contact_id, text, type, due_date, sales_id)
values (9002, 9001, 'Segunda tarea', 'call', '2026-09-01 09:00:00+00', 9001);

update public.tasks set deleted_at = now() where id = 9002;

select is(
    (select deleted_by from public.tasks where id = 9002), 9001::bigint,
    'a soft delete issued as an UPDATE still records who did it');

select is(
    (select count(*)::int from public.task_events
      where task_id = 9002 and event_type = 'task.deleted'),
    1,
    'the UPDATE path emits the same audit event as the DELETE path');

update public.tasks set deleted_at = null where id = 9002;

select ok(
    (select deleted_by from public.tasks where id = 9002) is null,
    'restoring a task clears the deletion attribution');

select * from finish();

rollback;
