import type {
  PortalSlide,
  PortalTemplate,
  SlideElement,
} from "../../../quotes/portal/portalSlides";

/**
 * The default portal template, as `20260924120000_portal_slides.sql` seeds it:
 * the presentation the portal always had, with its pictures bundled in the app
 * (`builtin/...`). Active and locked, exactly like the real one. Keep the two
 * copies identical — the migration's is the source.
 */
const DEFAULT_TEMPLATE_SLIDES: SlideElement[][] = [
  [
    {
      id: "cover-photo",
      kind: "image",
      x: 0,
      y: 0,
      w: 100,
      h: 100,
      path: "builtin/cover.webp",
      alt: "Plataforma Software - Event Production Company",
    },
    {
      id: "cover-eyebrow",
      kind: "text",
      x: 6,
      y: 50,
      w: 70,
      h: 5,
      text: "PLATAFORMA SOFTWARE · EVENT PRODUCTION COMPANY",
      size: "sm",
      align: "left",
      color: "light",
    },
    {
      id: "cover-title",
      kind: "text",
      x: 6,
      y: 56,
      w: 72,
      h: 24,
      text: "Una propuesta pensada para {company}",
      size: "xl",
      align: "left",
      color: "light",
    },
    {
      id: "cover-body",
      kind: "text",
      x: 6,
      y: 80,
      w: 60,
      h: 16,
      text: "Gracias por confiar en Plataforma Software. Hemos preparado esta propuesta para {company} con el fin de presentarte nuestra experiencia, nuestra forma de trabajar y, finalmente, el detalle de la solución y la inversión.",
      size: "sm",
      align: "left",
      color: "light",
    },
  ],
  [
    {
      id: "company-photo",
      kind: "image",
      x: 0,
      y: 0,
      w: 100,
      h: 55,
      path: "builtin/company.webp",
      alt: "Plataforma Software en evento",
    },
    {
      id: "company-eyebrow",
      kind: "text",
      x: 6,
      y: 59,
      w: 40,
      h: 5,
      text: "NUESTRA EMPRESA",
      size: "sm",
      align: "left",
      color: "light",
    },
    {
      id: "company-title",
      kind: "text",
      x: 6,
      y: 64,
      w: 88,
      h: 11,
      text: "Personas detrás de experiencias que conectan.",
      size: "lg",
      align: "left",
      color: "light",
    },
    {
      id: "company-body",
      kind: "text",
      x: 6,
      y: 76,
      w: 55,
      h: 20,
      text: "Conoce al equipo y la experiencia que respaldan esta propuesta para {company}. Esta sección funciona como introducción corporativa y busca generar contexto antes de entrar en la solución.",
      size: "sm",
      align: "left",
      color: "light",
    },
    {
      id: "company-highlights",
      kind: "text",
      x: 66,
      y: 76,
      w: 28,
      h: 20,
      text: "Experiencia\nInnovación\nEquipo\nResultados",
      size: "sm",
      align: "left",
      color: "light",
    },
  ],
  [
    {
      id: "purpose-eyebrow",
      kind: "text",
      x: 6,
      y: 14,
      w: 40,
      h: 5,
      text: "PROPÓSITO",
      size: "sm",
      align: "left",
      color: "light",
    },
    {
      id: "purpose-title",
      kind: "text",
      x: 6,
      y: 20,
      w: 40,
      h: 22,
      text: "Tecnología aplicada a experiencias reales.",
      size: "lg",
      align: "left",
      color: "light",
    },
    {
      id: "purpose-body",
      kind: "text",
      x: 6,
      y: 44,
      w: 40,
      h: 50,
      text: "Somos una compañía dedicada al desarrollo de soluciones tecnológicas propias aplicadas a la producción de eventos y a facilitar procesos de comunicación empresarial.\n\nNuestro objetivo es generar elementos diferenciadores en los productos y servicios donde son implementados.",
      size: "sm",
      align: "left",
      color: "light",
    },
    {
      id: "purpose-photo",
      kind: "image",
      x: 50,
      y: 0,
      w: 50,
      h: 100,
      path: "builtin/purpose.webp",
      alt: "Propósito de Plataforma Software",
    },
  ],
  [
    {
      id: "certifications-photo",
      kind: "image",
      x: 3,
      y: 8,
      w: 55,
      h: 84,
      path: "builtin/certifications.webp",
      alt: "Certificaciones y experiencia",
    },
    {
      id: "certifications-eyebrow",
      kind: "text",
      x: 62,
      y: 12,
      w: 34,
      h: 5,
      text: "CONFIANZA",
      size: "sm",
      align: "left",
      color: "light",
    },
    {
      id: "certifications-title",
      kind: "text",
      x: 62,
      y: 18,
      w: 34,
      h: 22,
      text: "El respaldo también hace parte de la propuesta.",
      size: "lg",
      align: "left",
      color: "light",
    },
    {
      id: "certifications-body",
      kind: "text",
      x: 62,
      y: 42,
      w: 34,
      h: 54,
      text: "ISO 9001:2015 — Procesos orientados a la calidad y mejora continua.\n\nISO 27001 — Seguridad y privacidad de la información.\n\nCapacitación — Equipo preparado en conocimiento especializado.\n\nServicio — Experiencia centrada en el cliente.",
      size: "sm",
      align: "left",
      color: "light",
    },
  ],
];

export const DEMO_PORTAL_TEMPLATES: PortalTemplate[] = [
  { id: 1, name: "Predeterminada", is_active: true, is_system: true },
];

export const DEMO_PORTAL_SLIDES: PortalSlide[] = DEFAULT_TEMPLATE_SLIDES.map(
  (elements, position) => ({
    id: position + 1,
    template_id: 1,
    position,
    elements,
  }),
);
