--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";
-- Lets `team_budgets` put `team_id with =` in a GiST exclusion constraint
-- alongside the daterange overlap test; plain GiST cannot index bigint equality.
create extension if not exists "btree_gist" with schema "extensions";
-- The reminder scheduler (§9.3). Declared here even though the cron JOB lives
-- in a migration (a row in `cron.job` is data, not schema): without this line
-- `supabase db diff` sees an extension the declarative schema does not know
-- about and helpfully generates `drop extension pg_cron`, which silently kills
-- every reminder in the product.
create extension if not exists "pg_cron";
-- `gen_random_bytes()`, which mints the portal access tokens (quotes §6.2).
-- Declared here for the same reason pg_cron is: an extension present in the
-- database but absent from the declarative schema makes `supabase db diff`
-- helpfully generate `drop extension pgcrypto`, which would take every future
-- token with it.
create extension if not exists "pgcrypto" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

-- Enums

-- Access level of a CRM user.
--   admin   - full access, manages users and application configuration
--   manager - sales manager: sees and reassigns every record, but does not manage users
--   rep     - sales representative: only sees and edits the records they own
create type public.sales_role as enum ('admin', 'manager', 'rep');

-- Task module (§3.3): assignment role, polymorphic link target, event type.
create type public.task_role as enum ('owner', 'collaborator', 'watcher', 'team');

-- Polymorphic link targets. Only the four that exist today are exercised by
-- the code, but the enum is the extension point for future entities (§14.1).
create type public.task_entity as enum
    ('contact', 'lead', 'company', 'deal', 'project', 'ticket', 'invoice', 'quote', 'order');

create type public.task_event_type as enum (
    -- lifecycle
    'task.created', 'task.updated', 'task.scheduled', 'task.started', 'task.waiting',
    'task.resumed', 'task.blocked', 'task.unblocked', 'task.completed', 'task.reopened',
    'task.canceled', 'task.archived', 'task.unarchived', 'task.deleted', 'task.restored',
    -- planning
    'task.rescheduled', 'task.priority_changed', 'task.type_changed', 'task.title_changed',
    'task.description_changed', 'task.due_removed',
    -- people
    'task.assigned', 'task.unassigned', 'task.reassigned', 'task.watcher_added',
    'task.watcher_removed', 'task.team_assigned',
    -- collaboration
    'comment.created', 'comment.edited', 'comment.deleted', 'comment.reaction_added',
    'comment.reaction_removed', 'mention.created',
    -- artefacts
    'attachment.added', 'attachment.removed',
    'checklist.item_added', 'checklist.item_completed', 'checklist.item_reopened',
    'checklist.item_removed', 'checklist.item_reordered',
    -- links & graph
    'link.added', 'link.removed', 'link.primary_changed',
    'dependency.added', 'dependency.removed', 'dependency.satisfied',
    -- time & reminders
    'timelog.started', 'timelog.stopped', 'timelog.edited',
    'reminder.created', 'reminder.updated', 'reminder.canceled',
    'reminder.sent', 'reminder.failed', 'reminder.acknowledged',
    -- system
    'automation.applied', 'sla.breached', 'sla.warning', 'import.applied'
);

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint,
    -- Which team the deal counts for in the budget dashboard. Seeded from the
    -- owner's team on creation, then edited on its own: a rep who belongs to
    -- two teams would otherwise make the same amount count twice, and moving a
    -- rep between teams would silently rewrite closed history.
    -- The foreign key is added after public.teams exists, further down.
    team_id bigint
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false,
    -- Declared last on purpose: the migration that replaced `administrator`
    -- appends `role` at the end of the table, and Postgres cannot insert a
    -- column mid-table. Keeping the same physical order here avoids a phantom
    -- diff on every `supabase db diff` run.
    role public.sales_role not null default 'rep'::public.sales_role
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

--
-- Why a deal moved from one stage to the next.
--
-- The kanban used to write `deals.stage` and nothing else, so the board could
-- say a deal reached "proposal sent" but never why, when, or on whose call.
-- This is the append-only record of every transition: the reason typed at the
-- moment of the move, the files that justified it, and the person who did it.
--
-- Written by `public.deals_log_stage_change()` only, on any path that changes
-- the stage (kanban, edit form, import). A client cannot insert here, so the
-- history cannot be back-dated or invented -- see 05_policies.sql.
--
-- `attachments` mirrors `deal_notes.attachments`: the same `jsonb[]` of
-- `{src,title,type,path}` objects stored in the public `attachments` bucket,
-- so one attachment renderer serves both.
--
create table public.deal_stage_changes (
    id bigint generated by default as identity primary key,
    deal_id bigint not null references public.deals(id) on update cascade on delete cascade,
    -- Null for the first transition of a deal created straight into a
    -- non-default stage: there is no previous stage to name.
    from_stage text,
    to_stage text not null,
    -- Free text, required when the move goes through `move_deal_stage()`, null
    -- when the stage was changed by another path (that gap is the point: an
    -- undocumented move stays visible as one).
    reason text,
    -- Who moved it. Null only when the actor has no `sales` row (service role,
    -- an import), never silently attributed to somebody else.
    sales_id bigint references public.sales(id),
    changed_at timestamp with time zone not null default now(),
    attachments jsonb[],
    -- Why an admin was allowed to move this deal without meeting the completed
    -- task requirement. Null on every move that satisfied the rule normally, so
    -- "which moves skipped the gate" is one `is not null` away. An override
    -- with no trace would put the backdoor straight back.
    override_reason text,
    constraint deal_stage_changes_to_stage_not_blank check (btrim(to_stage) <> ''),
    constraint deal_stage_changes_stages_differ check (from_stage is distinct from to_stage)
);

-- The deal timeline reads this table newest-first, always for one deal.
create index deal_stage_changes_deal_id_idx
    on public.deal_stage_changes (deal_id, changed_at desc);
create index deal_stage_changes_sales_id_idx
    on public.deal_stage_changes (sales_id);

--
-- How much work a deal must show before it may enter a stage.
--
-- The pipeline rule this backs: a deal only advances once something was
-- actually done on it. Encoded as a table rather than an `if` inside
-- `move_deal_stage()` for two reasons. `deals.stage` is free text and the stage
-- list is frontend configuration, so a function full of literal 'won' /
-- 'proposal-sent' would be wrong for the first customer who renames a column;
-- and a rule that can only be changed by shipping a migration is a rule nobody
-- can tune while a quarter is running.
--
-- A stage with no row here has no requirement. That is deliberate: `dealStages`
-- is customer-configurable, and a stage added to the frontend config with no
-- row here would otherwise freeze that column of the board with an error nobody
-- can act on.
--
create table public.deal_stage_requirements (
    to_stage text primary key,
    -- 0 disables the rule for this stage without deleting the row, which keeps
    -- the intent readable ("we decided not to gate this one").
    min_completed_tasks smallint not null default 0
        check (min_completed_tasks >= 0),
    -- Null means "not enforced". When set, it is compared against the moment
    -- the deal entered its CURRENT stage, not against now(): a deal that has
    -- been sitting in a stage since before the rule existed gets its next move
    -- for free, and is governed from then on. Without that, switching the rule
    -- on freezes every deal in flight on the day of the deploy.
    enforced_from timestamp with time zone,
    updated_at timestamp with time zone not null default now()
);

--
-- Leads: prospects that have not been qualified yet.
--
-- Deliberately decoupled from `companies`: a lead usually arrives with nothing
-- more than a company name typed into a web form, long before there is a
-- company record to point at. `public.convert_lead()` turns a qualified lead
-- into a company + contact (+ optional deal) and records what it produced.
--
create table public.leads (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    first_name text,
    last_name text,
    email extensions.citext,
    phone text,
    company_name text,
    company_id bigint,
    title text,
    source text,
    status text not null default 'new'::text,
    score smallint,
    notes text,
    tags bigint[],
    sales_id bigint,
    converted_at timestamp with time zone,
    converted_contact_id bigint,
    converted_company_id bigint,
    converted_deal_id bigint
);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

--
-- Task catalogues (§3.3)
--

create table public.task_statuses (
    id             bigint generated by default as identity primary key,
    key            text not null unique,             -- 'pending', 'in_progress', …
    label          text not null,
    color          text not null default 'gray',
    rank           smallint not null,                -- display order
    is_open        boolean not null default true,    -- counts as "open work"
    is_terminal    boolean not null default false,   -- no transitions out (except reopen)
    counts_as_done boolean not null default false,
    is_system      boolean not null default false    -- system states cannot be deleted
);

create table public.task_priorities (
    id        bigint generated by default as identity primary key,
    key       text not null unique,             -- 'low' | 'normal' | 'high' | 'urgent'
    label     text not null,
    color     text not null,
    rank      smallint not null,
    sla_hours integer                            -- null = no SLA
);

create table public.task_types (
    id        bigint generated by default as identity primary key,
    key       text not null unique,             -- 'call', 'email', 'demo', …
    label     text not null,
    icon      text,
    is_active boolean not null default true
);

create table public.tasks (
    id                bigint generated by default as identity primary key,

    -- legacy shims (kept read-only for one release; reads move to the new
    -- columns and to task_links; dropped later — see enterprise-task-module)
    contact_id        bigint,                  -- was NOT NULL; see task_links
    type              text,
    text              text,
    due_date          timestamp with time zone,
    done_date         timestamp with time zone,
    sales_id          bigint,

    -- content (§3.3)
    title             text not null,
    description       text,
    task_type_id      bigint not null,

    -- classification
    status_id         bigint not null,
    priority_id       bigint not null,

    -- scheduling
    start_at          timestamp with time zone,
    completed_at      timestamp with time zone,
    completed_by      bigint,
    canceled_at       timestamp with time zone,
    cancel_reason     text,

    -- ownership (denormalized from task_assignments for query speed)
    owner_sales_id    bigint not null,
    created_by        bigint not null,

    -- lifecycle bookkeeping
    created_at        timestamp with time zone not null default now(),
    updated_at        timestamp with time zone not null default now(),
    deleted_at        timestamp with time zone,
    deleted_by        bigint,
    archived_at       timestamp with time zone,

    -- denormalized counters (maintained by trigger)
    reschedule_count  integer not null default 0,
    reassign_count    integer not null default 0,
    comment_count     integer not null default 0,
    attachment_count  integer not null default 0,
    checklist_total   integer not null default 0,
    checklist_done    integer not null default 0,
    blocked_seconds   bigint  not null default 0,
    -- When the current block started. Phase 1 shipped `blocked_seconds` with a
    -- trigger that deferred the arithmetic to a scheduled job nobody wrote, so
    -- the counter never moved. Recording the entry instant makes the duration
    -- exact and computable on the way out, with no job at all (§10.2).
    blocked_since     timestamp with time zone,
    total_open_seconds bigint not null default 0,

    -- provenance
    source            text not null default 'manual'
                      check (source in ('manual', 'automation', 'import', 'api', 'email')),

    -- search
    search_tsv tsvector generated always as (
        setweight(to_tsvector('simple', coalesce(title, '')), 'A') ||
        setweight(to_tsvector('simple', coalesce(description, '')), 'B')
    ) stored,

    constraint tasks_completed_consistency
        check ((completed_at is null) = (completed_by is null))
);

--
-- Teams (§3.2). Deliberately two columns: a team exists to hang assignment,
-- escalation and reporting off, not to model an org chart. Managed from /teams
-- by admins and managers (05_policies.sql).
--

create table public.teams (
    id          bigint generated by default as identity primary key,
    name        text not null,
    description text,
    created_at  timestamp with time zone not null default now()
);

create table public.team_members (
    id        bigint generated by default as identity primary key,
    team_id   bigint not null references public.teams(id) on delete cascade,
    sales_id  bigint not null references public.sales(id) on delete cascade,
    created_at timestamp with time zone not null default now(),
    unique (team_id, sales_id),
    -- Redundant against the primary key on its own; it exists so
    -- `team_member_budgets` can point a composite foreign key at it and make a
    -- cross-team allocation unrepresentable. See that table below.
    constraint team_members_id_team_id_key unique (id, team_id)
);

-- "Which teams am I in" — asked by every task RLS check (§7.3). The
-- `unique (team_id, sales_id)` index above cannot serve it: wrong leading
-- column.
create index team_members_sales_id_idx
    on public.team_members (sales_id, team_id);

--
-- What a team is expected to sell, per period.
--
-- A separate table rather than a column on `teams`: a budget without a period
-- cannot answer "how did we do in Q3", and overwriting the number to set the
-- next target would destroy the only record of the previous one.
--
-- The exclusion constraint is the load-bearing one. Two overlapping periods for
-- the same team would make the dashboard pick a vigente budget arbitrarily,
-- which shows up as a number that changes between page loads.
--
create table public.team_budgets (
    id           bigint generated by default as identity primary key,
    team_id      bigint not null references public.teams(id) on delete cascade,
    period_start date not null,
    period_end   date not null,
    amount       numeric(14,2) not null check (amount >= 0),
    created_at   timestamp with time zone not null default now(),
    constraint team_budgets_period_order check (period_end > period_start),
    constraint team_budgets_no_overlap exclude using gist (
        team_id with =,
        daterange(period_start, period_end, '[]') with &&
    ),
    -- Foreign-key target for `team_member_budgets`, same reason as on
    -- `team_members` above.
    constraint team_budgets_id_team_id_key unique (id, team_id)
);

--
-- What each member of a team is expected to sell out of the team's target.
--
-- Keyed on the BUDGET, not on the team: an allocation with no period is the
-- mistake `team_budgets` exists to avoid — it would follow the team into the
-- next period and silently restate what was promised for the last one. Hanging
-- it off `team_budgets.id` makes "open a new period" mean "start from a blank
-- allocation", which is the honest default.
--
-- Keyed on the MEMBERSHIP rather than on the person: somebody removed from the
-- team carries no quota in it, so the roster quotas always sum to the team's
-- allocated total and the breakdown reconciles with the figure it sits under.
--
-- The two composite foreign keys are the load-bearing part. With plain
-- `references team_budgets(id)` / `references team_members(id)`, team A's
-- budget paired with team B's member is accepted, and that row is invisible in
-- every screen: it sums into one team's allocated total while the roster it
-- should appear in never shows it.
--
-- The sum is deliberately NOT constrained to the team budget. Reallocating
-- between two members is two writes, and an invariant enforced per row would
-- reject the first one purely for being first. Over- and under-allocation are
-- reported by the UI instead, which is also the only place that can say by how
-- much.
--
create table public.team_member_budgets (
    id             bigint generated by default as identity primary key,
    team_id        bigint not null,
    budget_id      bigint not null,
    team_member_id bigint not null,
    amount         numeric(14,2) not null check (amount >= 0),
    created_at     timestamp with time zone not null default now(),
    unique (budget_id, team_member_id),
    foreign key (budget_id, team_id)
        references public.team_budgets (id, team_id) on delete cascade,
    foreign key (team_member_id, team_id)
        references public.team_members (id, team_id) on delete cascade
);

-- "What is this person's quota", asked by the member drill-down. The unique
-- index above leads with `budget_id` and cannot serve it.
create index team_member_budgets_team_member_id_idx
    on public.team_member_budgets (team_member_id);

-- The deal -> team link, declared here because it is the first point where both
-- tables exist. The partial index serves the dashboard, which never sums
-- archived deals.
alter table public.deals
    add constraint deals_team_id_fkey foreign key (team_id)
    references public.teams(id);

create index deals_team_id_idx on public.deals (team_id) where archived_at is null;

--
-- Assignment: roles, closed rather than deleted (§3.3)
--

create table public.task_assignments (
    id             bigint generated by default as identity primary key,
    task_id        bigint not null references public.tasks(id) on delete restrict,
    sales_id       bigint references public.sales(id),
    team_id        bigint references public.teams(id),
    role           public.task_role not null,
    assigned_at    timestamp with time zone not null default now(),
    assigned_by    bigint not null references public.sales(id),
    unassigned_at  timestamp with time zone,     -- closed, never deleted
    unassigned_by  bigint references public.sales(id),
    reason         text,

    constraint task_assignments_subject
        check (num_nonnulls(sales_id, team_id) = 1)
);

-- Exactly one active owner at a time.
create unique index task_assignments_single_owner
    on public.task_assignments (task_id)
    where role = 'owner' and unassigned_at is null;

-- "My work" — the single most frequent query in the product.
create index task_assignments_active_by_sale
    on public.task_assignments (sales_id, role)
    where unassigned_at is null;

--
-- Polymorphic links (fixes W1) (§3.3)
--

create table public.task_links (
    id          bigint generated by default as identity primary key,
    task_id     bigint not null references public.tasks(id) on delete restrict,
    entity_type public.task_entity not null,
    entity_id   bigint not null,
    is_primary  boolean not null default false,
    linked_at   timestamp with time zone not null default now(),
    linked_by   bigint not null references public.sales(id),
    unlinked_at timestamp with time zone,
    -- Denormalized snapshot so the timeline can still say "vinculada a Acme"
    -- after the record is gone (§14.3).
    entity_label text
);

create unique index task_links_unique_active
    on public.task_links (task_id, entity_type, entity_id)
    where unlinked_at is null;

create unique index task_links_single_primary
    on public.task_links (task_id)
    where is_primary and unlinked_at is null;

-- The reverse lookup: "tasks on this deal". Leading columns are the filter.
create index task_links_entity
    on public.task_links (entity_type, entity_id, task_id)
    where unlinked_at is null;

--
-- State machine (§4)
--

create table public.task_transitions (
    id              bigint generated by default as identity primary key,
    from_status_key text not null,
    to_status_key   text not null,
    label           text,
    requires_reason boolean not null default false,
    is_system       boolean not null default false,
    unique (from_status_key, to_status_key)
);

--
-- Immutable event stream (§5)
--

create table public.task_events (
    id             bigint generated by default as identity,
    task_id        bigint not null,
    event_type     public.task_event_type not null,
    occurred_at    timestamp with time zone not null default clock_timestamp(),

    -- actor
    actor_sales_id bigint references public.sales(id),    -- null => system
    actor_kind     text not null default 'user'
                   check (actor_kind in ('user', 'system', 'automation', 'integration', 'import')),
    on_behalf_of   bigint references public.sales(id),

    -- payload
    field          text,
    old_value      jsonb,
    new_value      jsonb,
    metadata       jsonb not null default '{}'::jsonb,
    note           text,

    -- request context (optional, best effort)
    ip_address     inet,
    user_agent     text,
    device_kind    text check (device_kind in ('web', 'mobile', 'api', 'server')),
    request_id     uuid,
    session_id     uuid,

    -- ordering & integrity
    seq            bigint not null,        -- per-task monotonic sequence
    prev_hash      bytea,
    row_hash       bytea,

    primary key (id, occurred_at)
) partition by range (occurred_at);

-- Monthly partitions. The five below are the ones the module shipped with;
-- every later month is created by `ensure_task_events_partitions()`, which
-- pg_cron runs on the 1st (see the task_events_partition_maintenance
-- migration). The comment used to promise that job without it existing, and
-- the first symptom would have been every task write failing on 2027-01-01.
create table public.task_events_2026_08 partition of public.task_events
    for values from ('2026-08-01') to ('2026-09-01');
create table public.task_events_2026_09 partition of public.task_events
    for values from ('2026-09-01') to ('2026-10-01');
create table public.task_events_2026_10 partition of public.task_events
    for values from ('2026-10-01') to ('2026-11-01');
create table public.task_events_2026_11 partition of public.task_events
    for values from ('2026-11-01') to ('2026-12-01');
create table public.task_events_2026_12 partition of public.task_events
    for values from ('2026-12-01') to ('2027-01-01');

-- The safety net, never the mechanism: anything landing here is outside the
-- pruning the monthly layout exists to give. It is here so a month the
-- scheduler missed degrades into slower reads rather than an outage, because
-- a partition miss on this table aborts the task write that triggered it.
create table public.task_events_default partition of public.task_events default;

create index task_events_task_seq on public.task_events (task_id, seq desc);
create index task_events_actor    on public.task_events (actor_sales_id, occurred_at desc);
create index task_events_type     on public.task_events (event_type, occurred_at desc);
create index task_events_meta_gin on public.task_events using gin (metadata jsonb_path_ops);

--
-- Collaboration (§8)
--
-- `body_html` from the proposal is deliberately not stored: the repo already
-- sanitizes markdown at render time with `marked` + `dompurify`, and a
-- pre-rendered column is a second copy that can drift out of sync with the
-- body it claims to represent. One source of truth, sanitized on render.
--

create table public.task_comments (
    id         bigint generated by default as identity primary key,
    task_id    bigint not null references public.tasks(id) on delete restrict,
    parent_id  bigint references public.task_comments(id),  -- one level only
    author_id  bigint not null references public.sales(id),
    body       text not null,
    -- Internal note: author, managers and admins only (§8.2).
    is_private boolean not null default false,
    edited_at  timestamp with time zone,
    edit_count integer not null default 0,
    -- Soft delete only: the body stays readable in the audit view (§8.2).
    deleted_at timestamp with time zone,
    deleted_by bigint references public.sales(id),
    created_at timestamp with time zone not null default now(),

    constraint task_comments_body_not_blank check (btrim(body) <> '')
);

create index task_comments_task on public.task_comments (task_id, created_at)
    where deleted_at is null;
create index task_comments_thread on public.task_comments (parent_id, created_at)
    where deleted_at is null;

-- Every previous body. "Edited" without the old text is not an audit trail.
create table public.task_comment_revisions (
    id         bigint generated by default as identity primary key,
    comment_id bigint not null references public.task_comments(id) on delete restrict,
    body       text not null,
    edited_by  bigint not null references public.sales(id),
    edited_at  timestamp with time zone not null default now(),
    revision   integer not null,
    unique (comment_id, revision)
);

-- Resolved @mentions. Parsed server-side from the body, never trusted from the
-- client (§8.2): the body is the truth, these rows are derived from it.
create table public.task_comment_mentions (
    id                 bigint generated by default as identity primary key,
    comment_id         bigint not null references public.task_comments(id) on delete cascade,
    mentioned_sales_id bigint references public.sales(id),
    mentioned_team_id  bigint references public.teams(id),
    notified_at        timestamp with time zone,
    read_at            timestamp with time zone,

    constraint mention_subject
        check (num_nonnulls(mentioned_sales_id, mentioned_team_id) = 1)
);

-- "Mentions of me, unread" — the notification inbox query.
create index task_comment_mentions_inbox
    on public.task_comment_mentions (mentioned_sales_id, read_at);

-- Re-parsing a body on edit must not duplicate a mention that is still there.
create unique index task_comment_mentions_unique_sale
    on public.task_comment_mentions (comment_id, mentioned_sales_id)
    where mentioned_sales_id is not null;
create unique index task_comment_mentions_unique_team
    on public.task_comment_mentions (comment_id, mentioned_team_id)
    where mentioned_team_id is not null;

-- A surrogate key rather than the natural (comment, sale, emoji) triple as the
-- primary key: PostgREST and react-admin both address a row by a single `id`,
-- and un-reacting is a delete by id. The triple stays unique, so the same
-- person cannot register the same emoji twice.
create table public.task_comment_reactions (
    id         bigint generated by default as identity primary key,
    comment_id bigint not null references public.task_comments(id) on delete cascade,
    sales_id   bigint not null references public.sales(id),
    emoji      text not null,
    created_at timestamp with time zone not null default now(),

    constraint task_comment_reactions_unique unique (comment_id, sales_id, emoji)
);

--
-- Attachments (§3.2, §8.2)
--
-- One table for both task-level and comment-level files: a comment attachment
-- is a task attachment with `comment_id` set. Two tables would mean two upload
-- flows, two policies and two counters for the same thing.
--
-- The row is metadata; the bytes live in the private `task-attachments`
-- storage bucket under `<task_id>/…`, which is what lets the storage policy
-- gate a download on `can_see_task()` (§17.3). The public `attachments` bucket
-- used by notes cannot do that: a public bucket serves any object to anyone
-- holding the URL, signed in or not.
--
create table public.task_attachments (
    id           bigint generated by default as identity primary key,
    task_id      bigint not null references public.tasks(id) on delete restrict,
    -- Null for a task-level attachment; set when the file hangs off a comment.
    comment_id   bigint references public.task_comments(id) on delete restrict,

    storage_path text not null,          -- '<task_id>/<random>.<ext>' in the bucket
    file_name    text not null,          -- what the user uploaded, for display
    mime_type    text,
    size_bytes   bigint,
    -- SHA-256 of the bytes, computed at upload time. Recorded rather than used:
    -- it is the one piece of metadata that cannot be recovered afterwards if a
    -- retention job has already moved the object.
    checksum     text,

    uploaded_by  bigint not null references public.sales(id),
    uploaded_at  timestamp with time zone not null default now(),
    -- Soft delete, like everything else in this module: the history references
    -- the attachment by id and must keep resolving.
    deleted_at   timestamp with time zone,
    deleted_by   bigint references public.sales(id),

    constraint task_attachments_file_name_not_blank check (btrim(file_name) <> ''),
    constraint task_attachments_path_not_blank check (btrim(storage_path) <> ''),
    constraint task_attachments_size_not_negative
        check (size_bytes is null or size_bytes >= 0)
);

-- "The files on this task" — the only query the detail panel makes.
create index task_attachments_task
    on public.task_attachments (task_id, uploaded_at)
    where deleted_at is null;

-- "The files on this comment", rendered under each message in the thread.
create index task_attachments_comment
    on public.task_attachments (comment_id, uploaded_at)
    where deleted_at is null and comment_id is not null;

-- One live row per stored object: a retry that re-registers the same upload
-- would double the counter and show the file twice.
create unique index task_attachments_path_unique
    on public.task_attachments (storage_path)
    where deleted_at is null;

--
-- Checklists (§11)
--
-- A checklist item is a step of somebody else's work item, not a work item of
-- its own: no status machine, no comments, never in "my tasks". When a step
-- needs its own owner it should become a sub-task instead (§11.1).
--

create table public.task_checklist_items (
    id          bigint generated by default as identity primary key,
    task_id     bigint not null references public.tasks(id) on delete restrict,
    label       text not null,
    -- Fractional ranking: inserting between 1.0 and 2.0 writes 1.5, so a drag
    -- and drop is one row update instead of renumbering the whole list.
    position    numeric not null,
    is_done     boolean not null default false,
    done_at     timestamp with time zone,
    done_by     bigint references public.sales(id),
    due_at      timestamp with time zone,
    assignee_id bigint references public.sales(id),
    created_by  bigint not null references public.sales(id),
    created_at  timestamp with time zone not null default now(),
    deleted_at  timestamp with time zone,

    constraint task_checklist_items_label_not_blank check (btrim(label) <> ''),
    -- "Done" without who and when is the exact hole this module exists to fix.
    constraint checklist_done_consistency
        check ((is_done = false and done_at is null and done_by is null)
            or (is_done = true and done_at is not null and done_by is not null))
);

create index task_checklist_items_task
    on public.task_checklist_items (task_id, position)
    where deleted_at is null;

--
-- Dependencies (§10)
--
-- Edges are directed and stored ONCE; the inverse is derived ("A blocks B"
-- means "B is blocked by A"). Storing both directions is the classic source of
-- inconsistent graphs.
--

create type public.task_dependency_kind as enum
    ('blocks', 'parent', 'related', 'duplicates');

create table public.task_dependencies (
    id             bigint generated by default as identity primary key,
    source_task_id bigint not null references public.tasks(id) on delete restrict,
    target_task_id bigint not null references public.tasks(id) on delete restrict,
    kind           public.task_dependency_kind not null,
    created_by     bigint not null references public.sales(id),
    created_at     timestamp with time zone not null default now(),
    removed_at     timestamp with time zone,
    removed_by     bigint references public.sales(id),

    constraint no_self_dependency check (source_task_id <> target_task_id)
);

create unique index task_dependencies_unique_active
    on public.task_dependencies (source_task_id, target_task_id, kind)
    where removed_at is null;

-- "What blocks me?" — walked on every completion to release dependents.
create index task_dependencies_reverse
    on public.task_dependencies (target_task_id, kind)
    where removed_at is null;

--
-- Reminders (§9)
--
-- Two tables, because a rule is edited while a delivery is a fact. Editing
-- "remind me a day before" must not rewrite the record of the ping that already
-- went out last Tuesday — that is the same append-only reasoning as
-- `task_events`, applied to notifications.
--

create type public.reminder_channel as enum
    ('in_app', 'email', 'push', 'whatsapp', 'sms', 'webhook');

create table public.task_reminders (
    id             bigint generated by default as identity primary key,
    task_id        bigint not null references public.tasks(id) on delete restrict,
    created_by     bigint not null references public.sales(id),
    created_at     timestamp with time zone not null default now(),

    -- WHEN
    schedule_kind  text not null check (schedule_kind in
                     ('absolute', 'relative_before_due', 'relative_after_due', 'recurring')),
    absolute_at    timestamp with time zone,
    -- For relative_*: 60 = one hour before (or after) the due date.
    offset_minutes integer,
    -- RFC 5545 rather than a bespoke format: it is what every calendar client
    -- already speaks, which makes iCal export in Phase 3 free (§9.2).
    rrule          text,
    timezone       text not null default 'UTC',
    until_at       timestamp with time zone,
    max_occurrences integer,

    -- WHO / HOW
    channels       public.reminder_channel[] not null default '{in_app}',
    recipients     text not null default 'owner'
                   check (recipients in ('owner', 'assignees', 'watchers', 'all', 'custom')),
    custom_recipients bigint[],
    message_template text,

    -- STATE
    is_active      boolean not null default true,
    -- Materialized for the scheduler: the dispatcher must never recompute a
    -- schedule for rows it is not going to fire.
    next_fire_at   timestamp with time zone,
    fired_count    integer not null default 0,
    stop_on_complete boolean not null default true,

    -- Each schedule kind needs exactly the field that defines it.
    constraint task_reminders_schedule_shape check (
        (schedule_kind = 'absolute' and absolute_at is not null)
        or (schedule_kind in ('relative_before_due', 'relative_after_due')
            and offset_minutes is not null and offset_minutes >= 0)
        or (schedule_kind = 'recurring' and btrim(coalesce(rrule, '')) <> '')
    ),
    constraint task_reminders_channels_not_empty
        check (array_length(channels, 1) >= 1),
    constraint task_reminders_custom_recipients check (
        recipients <> 'custom'
        or coalesce(array_length(custom_recipients, 1), 0) >= 1
    )
);

-- The scheduler's ONLY query. Partial, so it stays the size of the pending
-- work rather than the size of the reminder history.
create index task_reminders_due
    on public.task_reminders (next_fire_at)
    where is_active and next_fire_at is not null;

create index task_reminders_task
    on public.task_reminders (task_id)
    where is_active;

--
-- The outbox. One row per delivery attempt per recipient per channel, so a
-- reminder that was never delivered is visible AS SUCH (O6) instead of being
-- indistinguishable from one nobody acted on.
--
create table public.task_notifications (
    id            bigint generated by default as identity primary key,
    reminder_id   bigint references public.task_reminders(id),
    task_id       bigint not null references public.tasks(id) on delete restrict,
    recipient_id  bigint not null references public.sales(id),
    channel       public.reminder_channel not null,
    scheduled_for timestamp with time zone not null,
    sent_at       timestamp with time zone,
    delivered_at  timestamp with time zone,
    read_at       timestamp with time zone,
    acknowledged_at timestamp with time zone,
    title         text,
    body          text,
    status        text not null default 'queued'
                  check (status in ('queued', 'sending', 'sent', 'delivered',
                                    'failed', 'bounced', 'skipped', 'canceled')),
    attempt       smallint not null default 0,
    error         text,
    provider_message_id text,
    -- Idempotency: `reminder:occurrence:recipient:channel`. A replayed
    -- dispatch is a no-op instead of a second ping.
    dedupe_key    text unique,
    created_at    timestamp with time zone not null default now()
);

-- The worker's claim query.
create index task_notifications_outbox
    on public.task_notifications (status, scheduled_for)
    where status in ('queued', 'sending');

-- "My unread in-app notifications" — the bell badge, on every page load.
create index task_notifications_inbox
    on public.task_notifications (recipient_id, created_at desc)
    where channel = 'in_app' and read_at is null;

create index task_notifications_task
    on public.task_notifications (task_id, created_at desc);

--
-- Anti-fatigue preferences for reminders (§9.5)
--
-- "A reminder system without throttling is uninstalled within a week." One row
-- per user; absent means the defaults, so nobody needs backfilling.
--
create table public.notification_preferences (
    id          bigint generated by default as identity primary key,
    sales_id    bigint not null unique references public.sales(id) on delete cascade,

    -- Quiet hours are expressed in the user's own timezone; storing them as
    -- `time` plus a zone is what makes "no pings before 08:00" mean the same
    -- thing in Bogota and in Madrid.
    timezone    text not null default 'UTC',
    quiet_hours_start time,
    quiet_hours_end   time,

    -- Digest: one message at a fixed hour instead of N pings through the day.
    digest_mode boolean not null default false,
    digest_at   time not null default '08:00',

    -- Per-channel opt-out. Per-EVENT-TYPE preferences are deliberately not
    -- modelled yet: every row in the outbox comes from a reminder today, so a
    -- second axis would have exactly one value to key on (YAGNI). Add it when
    -- automations start writing notifications (Phase 3).
    muted_channels public.reminder_channel[] not null default '{}',

    -- Hard ceiling on deliveries per rolling hour, enforced at claim time.
    max_per_hour integer not null default 20 check (max_per_hour > 0),

    -- "Same task, several rules fired" collapses inside this window.
    dedupe_window_minutes integer not null default 60
        check (dedupe_window_minutes >= 0),

    created_at  timestamp with time zone not null default now(),
    updated_at  timestamp with time zone not null default now()
);

create index notification_preferences_sales_id_idx
    on public.notification_preferences (sales_id);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.leads
    add constraint leads_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.leads
    add constraint leads_company_id_fkey foreign key (company_id) references public.companies(id) on delete set null;

-- The conversion pointers are provenance, not ownership: if the record they
-- produced is later deleted the lead stays, with the pointer cleared.
alter table public.leads
    add constraint leads_converted_contact_id_fkey foreign key (converted_contact_id) references public.contacts(id) on delete set null;

alter table public.leads
    add constraint leads_converted_company_id_fkey foreign key (converted_company_id) references public.companies(id) on delete set null;

alter table public.leads
    add constraint leads_converted_deal_id_fkey foreign key (converted_deal_id) references public.deals(id) on delete set null;

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

-- W8 fix: the cascade is gone. Deleting a parent closes `task_links`
-- (`unlinked_at`) and emits an event instead of cascading a delete; the
-- legacy `tasks.contact_id` shim is kept nullable and read-only.
alter table public.tasks
    add constraint tasks_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.tasks
    add constraint tasks_owner_sales_id_fkey foreign key (owner_sales_id) references public.sales(id);

alter table public.tasks
    add constraint tasks_created_by_fkey foreign key (created_by) references public.sales(id);

alter table public.tasks
    add constraint tasks_completed_by_fkey foreign key (completed_by) references public.sales(id);

alter table public.tasks
    add constraint tasks_deleted_by_fkey foreign key (deleted_by) references public.sales(id);

alter table public.tasks
    add constraint tasks_task_type_id_fkey foreign key (task_type_id) references public.task_types(id);

alter table public.tasks
    add constraint tasks_status_id_fkey foreign key (status_id) references public.task_statuses(id);

alter table public.tasks
    add constraint tasks_priority_id_fkey foreign key (priority_id) references public.task_priorities(id);

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);

--
-- Ownership indexes
--
-- Every owner-scoped RLS policy filters on `sales_id`, and so do the
-- "only mine" list filters. Without these the policies degrade to a sequential
-- scan on every list query.
--
create index companies_sales_id_idx on public.companies using btree (sales_id);
create index contacts_sales_id_idx on public.contacts using btree (sales_id);
create index deals_sales_id_idx on public.deals using btree (sales_id);
create index contact_notes_sales_id_idx on public.contact_notes using btree (sales_id);
create index deal_notes_sales_id_idx on public.deal_notes using btree (sales_id);

-- tasks.contact_id had no index at all: it now carries both the contact detail
-- page lookup and the legacy RLS path. This is by far the most scanned index
-- in the schema.
create index tasks_contact_id_idx on public.tasks using btree (contact_id);
-- The task list filters by owner and orders by due date.
create index tasks_sales_id_due_date_idx on public.tasks using btree (sales_id, due_date);

--
-- List ordering indexes
--
-- Every one of these backs an `order by ... limit n` that would otherwise
-- top-N heapsort the whole table on each page load. Partial where the list is
-- always filtered the same way.
--
create index contacts_last_seen_idx on public.contacts using btree (last_seen desc);
create index contact_notes_date_idx on public.contact_notes using btree (date desc);
create index deal_notes_date_idx on public.deal_notes using btree (date desc);
-- Backs `contacts_summary.nb_tasks` (open, non-deleted tasks only).
create index tasks_pending_contact_id_idx on public.tasks using btree (contact_id) where done_date is null and deleted_at is null;
-- Backs the "tasks due" lists, which never show completed tasks.
create index tasks_pending_due_date_idx on public.tasks using btree (due_date) where done_date is null;
-- Backs the deal kanban, which only ever lists non-archived deals.
create index deals_active_index_idx on public.deals using btree (index desc) where archived_at is null;

-- Task-module query indexes (§18.3).
-- "My open tasks by due date" — the single hottest query in the product.
create index tasks_owner_open_due
    on public.tasks (owner_sales_id, due_date)
    where deleted_at is null and completed_at is null and canceled_at is null;
-- Overdue triage (manager inbox).
create index tasks_overdue
    on public.tasks (due_date)
    where deleted_at is null and completed_at is null and canceled_at is null;
-- "Everything this person owns", whatever state it is in -- the access path
-- `team_workload_summary` needs. Every other owner index is PARTIAL (open, or
-- completed), so a query that counts open AND completed in one pass matches
-- none of them: without this the planner fell back to a full scan of `tasks`
-- once per member, measured at 1.7 s for 40 reps over 200k tasks against 215 ms
-- with it.
create index tasks_owner_all
    on public.tasks (owner_sales_id)
    where deleted_at is null;
-- Completed work per owner -- the team dashboards' `nb_tasks_completed`
-- counters and the `team_task_stats` cube, both of which ask "what did this
-- person close inside the period". None of the indexes above can serve it: they
-- are all partial ON completed_at BEING NULL, which is the exact complement of
-- this query.
create index tasks_owner_completed
    on public.tasks (owner_sales_id, completed_at)
    where completed_at is not null and deleted_at is null;
-- Status boards / Kanban.
create index tasks_status_due on public.tasks (status_id, due_date)
    where deleted_at is null;
-- Full-text search.
create index tasks_search on public.tasks using gin (search_tsv);

-- Leads: owner scoping (RLS + "only mine"), the default list ordering, and the
-- conversion pointers used by the contact/company/deal detail pages.
create index leads_sales_id_idx on public.leads using btree (sales_id);
create index leads_created_at_idx on public.leads using btree (created_at desc);
create index leads_company_id_idx on public.leads using btree (company_id);
create index leads_converted_contact_id_idx on public.leads using btree (converted_contact_id);

-- ---------------------------------------------------------------------------
-- The one index this module ships
-- ---------------------------------------------------------------------------
--
-- Backs every period-scoped deal figure: the won/lost branch of
-- `deal_flow_stats` and the decided counters on `deal_owner_stats`, both of
-- which range-filter `expected_closing_date`.
--
-- MEASURED, because an index that does not change a plan is pure write cost.
-- 200k deals, 40 owners, three years, local Postgres 15, three runs each:
--
--   12-month window:  50.5 / 49.0 / 51.5 ms  ->  43.0 / 42.6 / 45.8 ms  (-12%)
--    1-month window:  34.5 / 33.3 / 35.5 ms  ->  24.0 / 24.3 / 26.1 ms  (-28%)
--
-- The planner switches from a parallel sequential scan to a bitmap index scan
-- in both cases, and the narrower the window the more it wins -- which is the
-- shape of the period presets the UI actually offers.
--
-- Two candidates were measured and REJECTED rather than shipped on intuition:
--   * `deals (created_at)` -- never chosen by the planner. A 12-month window is
--     a third of the table, so the creation branch stays a sequential scan.
--   * `leads (created_at)` -- moved `lead_flow_stats` from 17.2 ms to 17.0 ms,
--     which is noise.
--
create index if not exists deals_expected_closing_date_idx
    on public.deals (expected_closing_date)
    where archived_at is null;

--
-- Reports module (§ reports): the catalogue, and the saved reports.
--
-- `/analytics` answers a fixed set of questions with eight purpose-built
-- aggregate functions. This module answers questions nobody wrote a function
-- for: pick an entity, some metrics, one or two dimensions, filters, a period.
-- That is dynamic SQL, and dynamic SQL built from client input is the single
-- most dangerous thing this schema could grow -- so the shape below exists to
-- make the dangerous version unrepresentable.
--
-- THE RULE: the client never sends SQL. It sends KEYS. Every key is resolved
-- against `report_fields`, whose `sql_expr` values are authored in migrations
-- and can only be written by `service_role`. A key that is not in the
-- catalogue raises an exception, so the set of programs `run_report()` can be
-- persuaded to run is exactly the set this table describes.
--
-- The catalogue is also what the builder UI renders itself from
-- (`report_catalog()`), so the picker cannot offer a field the executor would
-- refuse. One source of truth, no drift possible -- the same reason
-- `deal_stage_requirements` is a table rather than an `if`.
--

--
-- One row per reportable entity.
--
create table public.report_datasets (
    key   text primary key,
    label text not null,
    --
    -- The FROM clause, authored here. Every join is LEFT and every join key is
    -- the target's primary key, which lets Postgres drop the ones a given
    -- report does not reference (join elimination) -- so the wide base costs
    -- nothing when a report groups by stage alone.
    --
    from_sql text not null,
    --
    -- Rows no report on this dataset may ever see: soft deletes, archives.
    -- Applied before any user filter, so "deleted" is not something a report
    -- can be built to reveal.
    --
    base_where text not null default 'true',
    -- Which date field the period filter uses when the report does not say.
    default_date_field text,
    rank smallint not null default 0
);

--
-- One row per selectable field.
--
-- `role` splits the two things a field can be. A dimension is something to
-- GROUP BY; a metric is an aggregate. `stage` is a dimension, `amount_sum` is
-- a metric, and the executor will not let them swap places.
--
create table public.report_fields (
    dataset_key text not null
        references public.report_datasets(key) on delete cascade,
    key   text not null,
    label text not null,
    role  text not null check (role in ('dimension', 'metric')),
    --
    -- Drives the operators the filter builder offers and how the value is
    -- cast. `month` is a date already truncated by `sql_expr`; it exists so the
    -- UI knows to format it as a month label rather than a day.
    --
    data_type text not null
        check (data_type in ('text', 'number', 'money', 'date', 'month')),
    --
    -- THE TRUSTED STRING. Interpolated into the generated statement verbatim,
    -- which is safe for exactly one reason: it is written in a migration and
    -- no role but `service_role` may write this table. Never build a row here
    -- from user input, and never expose a write path to it.
    --
    sql_expr text not null,
    --
    -- Metrics only. For everything but `raw`, `sql_expr` is the ARGUMENT and
    -- this names the function wrapped around it. `raw` means `sql_expr` is
    -- already a complete aggregate expression -- the escape hatch that lets a
    -- ratio like win rate be one field instead of two plus arithmetic in the
    -- browser, where it would be computed over whatever page happened to load.
    --
    aggregate text
        check (aggregate in ('sum', 'count', 'count_distinct', 'avg', 'raw')),
    -- Whether this field may appear in a `filters[]` entry.
    filterable boolean not null default true,
    --
    -- Names a frontend configuration list (`dealStages`, `leadSources`,
    -- `taskTypes`) that resolves this dimension's raw key to a human label.
    -- Resolved in the browser, not here: `deals.stage` is free text and its
    -- vocabulary lives in application configuration, so a join to a labels
    -- table would be wrong for the first customer who renames a stage.
    --
    label_source text,
    rank smallint not null default 0,
    primary key (dataset_key, key),
    -- A dimension with an aggregate, or a metric without one, is a catalogue
    -- bug that would surface as malformed SQL at run time instead of here.
    constraint report_fields_aggregate_matches_role check (
        (role = 'metric'    and aggregate is not null) or
        (role = 'dimension' and aggregate is null)
    )
);

--
-- A saved report: the definition, never the data.
--
-- `spec` is the same jsonb the builder produces, the URL carries and
-- `run_report()` consumes. Storing the definition rather than a result is what
-- makes sharing safe: two people opening one shared report each execute it
-- under their own row level security, so a rep with whom a manager shared the
-- company pipeline sees their own pipeline, not the manager's. It also means
-- the two see different numbers under one title, which the UI has to say out
-- loud.
--
create table public.reports (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    spec jsonb not null,
    --
    -- Author and owner. Null only for the seeded library reports, which belong
    -- to the installation rather than to a person.
    --
    -- Set by the CLIENT from the signed-in identity, not by a column default.
    -- `default public.current_sale_id()` would read better, but this file is
    -- applied before `02_functions.sql` in the declarative schema, so the
    -- default would reference a function that does not exist yet and a clean
    -- `supabase db reset` would fail. No other table here uses a function
    -- default, and this is not the place to become the first.
    --
    -- Forging it is still impossible: the insert policy requires
    -- `sales_id = current_sale_id()`, so passing somebody else's id is refused
    -- rather than accepted.
    --
    sales_id bigint references public.sales(id) on delete cascade,
    --
    -- 'private'  -- only the owner (and admins/managers) may read it
    -- 'shared'   -- any authenticated user may read it
    --
    -- Deliberately two values and not an ACL. A per-user share list is a
    -- permission system, and this schema already has one; a report that could
    -- be shared with a subset would invite the reading that the SUBSET sees the
    -- same numbers, which is exactly what row level security guarantees they do
    -- not.
    --
    visibility text not null default 'private'
        check (visibility in ('private', 'shared')),
    -- True for the reports the migration seeds. They cannot be edited or
    -- deleted, only duplicated -- so the library always has a working example
    -- of every visualisation, whatever users do to their own copies.
    is_builtin boolean not null default false,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint reports_name_not_blank check (btrim(name) <> ''),
    -- A built-in has no owner; a user report must have one. Without this a
    -- personal report could be written with a null owner and become readable
    -- by everyone through the built-in branch of the read policy.
    constraint reports_builtin_has_no_owner check (
        (is_builtin and sales_id is null) or (not is_builtin and sales_id is not null)
    )
);

-- The library lists a user's own reports plus the shared ones, newest first.
create index reports_sales_id_idx on public.reports (sales_id, updated_at desc);
create index reports_visibility_idx on public.reports (visibility)
    where visibility = 'shared';


--
-- How each person left a report they cannot edit.
--
-- The library's built-ins belong to the installation, not to anybody, and a
-- report somebody shared belongs to its author. Neither can be written by the
-- reader -- which used to mean that adjusting one and coming back tomorrow lost
-- the adjustment, or forced a duplicate into the library for what was really
-- just "I prefer to look at this by month".
--
-- So the report keeps its definition and the READER keeps their view of it.
-- The rule is one line: if you cannot edit a report, your changes to it are
-- remembered as yours. That covers the built-ins and other people's shared
-- reports with the same mechanism, and it leaves the original permanently
-- recoverable -- deleting the preference row restores it, which is what makes
-- the built-in library still able to guarantee a working example of every
-- visualisation.
--
-- Per user and NEVER shared, exactly like `notification_preferences`. A global
-- "last configuration wins" was the alternative: one rep regrouping the team's
-- pipeline report would silently rewrite what their director opens, and the
-- director would have no way to know it changed or who did it.
--
create table public.report_preferences (
    sales_id  bigint not null references public.sales(id) on delete cascade,
    report_id bigint not null references public.reports(id) on delete cascade,
    -- The same jsonb shape as `reports.spec`. Deliberately a full spec rather
    -- than a diff against the original: a diff would have to be re-applied
    -- against a built-in that a later migration may have amended, and the two
    -- would silently disagree about what the user actually asked to see.
    spec jsonb not null,
    updated_at timestamp with time zone not null default now(),
    primary key (sales_id, report_id)
);

-- ===========================================================================
-- Quotes / CPQ module (docs/proposals/quotes-cpq-module.md, Phase 2)
-- ===========================================================================
--
-- THE GUIDING RULE, and the reason half of what follows looks like extra work:
-- the catalogue is CURRENT information and a quote is a HISTORICAL SNAPSHOT.
-- A quote the customer accepted must render identically in a year, after the
-- price list has been rewritten twice. Every freeze guard, every frozen column
-- on `quote_lines` and the whole version chain exist to keep those two things
-- from becoming the same thing.
--
-- Section references below (§2.1, §6.2, …) point at that proposal.

--
-- Catalogues (§2.1)
--

-- Tax rates are a TABLE and units of measure are not, and the difference is not
-- taste: a tax rate is referenced by a foreign key and frozen onto a quote line,
-- whereas a unit is a label. Units and product categories live as arrays in the
-- `configuration` singleton, editable from the settings screen exactly as
-- `taskTypes` and `noteStatuses` already are -- parametrisable at zero schema
-- cost.
--
-- `exento` and `excluido` are both 0.000 and legally distinct in Colombia,
-- which is why they are two rows and not one rate.
create table public.tax_rates (
    id         bigint generated by default as identity primary key,
    code       extensions.citext not null unique,
    label      text not null,
    rate       numeric(6,3) not null check (rate >= 0 and rate <= 100),
    is_default boolean not null default false,
    active     boolean not null default true,
    rank       smallint not null default 0,
    is_system  boolean not null default false,
    constraint tax_rates_label_not_blank check (btrim(label) <> '')
);

-- "Which rate applies when nobody picked one" must resolve to exactly one row,
-- or the answer changes between page loads.
create unique index tax_rates_one_default
    on public.tax_rates (is_default) where is_default and active;

-- The `task_statuses` shape (see that table above), with `counts_as_won` in
-- place of `counts_as_done`: for a quote the terminal state worth reporting on
-- is the one that produced revenue.
create table public.quote_statuses (
    id            bigint generated by default as identity primary key,
    key           text not null unique,
    label         text not null,
    color         text not null default 'gray',
    rank          smallint not null,
    is_open       boolean not null default true,
    is_terminal   boolean not null default false,
    counts_as_won boolean not null default false,
    is_system     boolean not null default false
);

-- The legal edges of the status machine, as DATA -- the same argument
-- `deal_stage_requirements` makes above: a graph that needs a migration to
-- change is one nobody tunes, and a function full of literal status names is
-- wrong for the first customer who renames one.
--
-- `allowed_actor` is the security piece and the one column `task_transitions`
-- does not have. `viewed`, `accepted` and `rejected` are customer-driven;
-- `approved` and `sent` are internal; `expired` is the sweeper's. Without this
-- column the public portal function would be one parameter away from driving
-- `draft -> approved`.
create table public.quote_transitions (
    id                      bigint generated by default as identity primary key,
    from_status_key         text not null
        references public.quote_statuses(key) on update cascade,
    to_status_key           text not null
        references public.quote_statuses(key) on update cascade,
    label                   text,
    requires_reason         boolean not null default false,
    -- "You cannot send what you never issued." Checked against the existence of
    -- an issued version, not against a status, so it stays true whichever path
    -- reached the transition.
    requires_issued_version boolean not null default false,
    allowed_actor           text not null default 'internal'
        check (allowed_actor in ('internal', 'customer', 'system', 'any')),
    is_system               boolean not null default false,
    unique (from_status_key, to_status_key),
    constraint quote_transitions_differ check (from_status_key <> to_status_key)
);

--
-- Commercial catalogue (§2.2)
--

-- `sku` is citext for the same reason `sales.email` is: `ABC-1` and `abc-1` are
-- the same SKU to every human who will ever type one, and a case-sensitive
-- unique index lets both exist.
--
-- `internal_notes` is the one column on this table that must never reach the
-- public portal (§6.3). `quote_portal.test.sql` asserts its absence once the
-- portal exists.
create table public.products (
    id             bigint generated by default as identity primary key,
    sku            extensions.citext not null unique,
    name           text not null,
    description    text,
    internal_notes text,
    kind           text not null default 'product'
        check (kind in ('product', 'service', 'plan', 'subscription', 'concept')),
    category       text,
    unit           text not null default 'unit',
    list_price     numeric(14,2) not null default 0 check (list_price >= 0),
    -- No default. `defaultConfiguration.currency` is "USD" and a Colombian
    -- catalogue silently inheriting it is exactly the bug F3 describes, so the
    -- currency is always stated rather than assumed.
    currency       character(3) not null check (currency ~ '^[A-Z]{3}$'),
    tax_rate_id    bigint references public.tax_rates(id),
    image          jsonb,
    is_active      boolean not null default true,
    sales_id       bigint references public.sales(id),
    created_at     timestamp with time zone not null default now(),
    updated_at     timestamp with time zone not null default now(),
    -- The `tasks.search_tsv` idiom: an explicit 'simple' configuration, so the
    -- expression is immutable and the column may be STORED.
    search_tsv tsvector generated always as (
        setweight(to_tsvector('simple', coalesce((sku)::text, '')), 'A') ||
        setweight(to_tsvector('simple', coalesce(name, '')), 'A') ||
        setweight(to_tsvector('simple', coalesce(description, '')), 'B')
    ) stored,
    constraint products_name_not_blank check (btrim(name) <> '')
);

create index products_active_name on public.products (name) where is_active;
create index products_search on public.products using gin (search_tsv);
create index products_active_category on public.products (category) where is_active;
create index products_sales_id_idx on public.products (sales_id);

-- "Consult the change history" for the catalogue, one row per watched field --
-- the `log_task_changes()` idiom applied to a much smaller table.
--
-- A SEPARATE table from the quote history on purpose: mixing a catalogue's
-- edits with a negotiation's events makes both harder to read, and they answer
-- different questions ("who changed this price" vs "why did this deal move").
create table public.product_events (
    id          bigint generated by default as identity primary key,
    product_id  bigint not null references public.products(id) on delete cascade,
    event_type  text not null
        check (event_type in ('product.created', 'product.updated',
                              'product.deactivated', 'product.reactivated')),
    occurred_at timestamp with time zone not null default clock_timestamp(),
    sales_id    bigint references public.sales(id),
    field       text,
    old_value   jsonb,
    new_value   jsonb
);

create index product_events_product
    on public.product_events (product_id, occurred_at desc);

create table public.price_lists (
    id         bigint generated by default as identity primary key,
    code       extensions.citext not null unique,
    name       text not null,
    currency   character(3) not null check (currency ~ '^[A-Z]{3}$'),
    is_default boolean not null default false,
    is_active  boolean not null default true,
    valid_from date,
    valid_to   date,
    notes      text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint price_lists_name_not_blank check (btrim(name) <> ''),
    constraint price_lists_period_order
        check (valid_from is null or valid_to is null or valid_to >= valid_from),
    -- Foreign-key target for `quotes`, so a quote cannot point at a price list
    -- in another currency. Same trick as `team_budgets_id_team_id_key`.
    constraint price_lists_id_currency_key unique (id, currency)
);

-- One default per CURRENCY, not one globally. With multi-currency (D3) a single
-- global default would make "which price applies" answerable only by guessing
-- which currency the reader meant.
create unique index price_lists_one_default_per_currency
    on public.price_lists (currency) where is_default and is_active;

create table public.price_list_items (
    id            bigint generated by default as identity primary key,
    price_list_id bigint not null references public.price_lists(id) on delete cascade,
    -- `restrict`, not `cascade`: a product that has been priced is deactivated,
    -- never deleted. Losing the price row silently would change what a list
    -- means without anybody editing it.
    product_id    bigint not null references public.products(id) on delete restrict,
    unit_price    numeric(14,2) not null check (unit_price >= 0),
    -- Overrides the product's own rate for this list (an export list may be
    -- exempt where the domestic one is not).
    tax_rate_id   bigint references public.tax_rates(id),
    -- Volume tiers. Only "highest tier that fits" resolution is used; a real
    -- tier editor is named out of scope in §12.
    min_quantity  numeric(14,3) not null default 1 check (min_quantity > 0),
    unique (price_list_id, product_id, min_quantity)
);

create index price_list_items_product on public.price_list_items (product_id);

--
-- Quotes (§2.3)
--
-- Human-facing document numbers. A sequence rather than `max(quote_number) + 1`:
-- the latter takes a lock on the whole table and still collides under
-- concurrency, and a gap in a quote number is not a problem worth a lock.
create sequence public.quote_number_seq as bigint;

-- The header and the current state. Three deliberate absences:
--
--   * No `current_version_id`. A `quotes.current_version_id -> quote_versions.id`
--     foreign key alongside `quote_versions.quote_id -> quotes.id` is a cycle,
--     which forces deferrable constraints and an insertion order. The current
--     version is derived with the repo's `left join lateral (… order by
--     version_number desc limit 1)` idiom in `quotes_summary`.
--   * No totals. They live on the version -- one source -- and `quotes_summary`
--     surfaces them for lists and boards.
--   * No global discount amount. A generated column cannot see the other rows,
--     so a pro-rata header discount would be impossible to compute locally and
--     per-line tax would stop reconciling. See `quote_lines` below.
--
-- `status_key` is TEXT referencing `quote_statuses(key)`, not `status_id
-- bigint`. Three reasons, all verifiable in this schema: `quote_transitions` is
-- keyed on keys, so a bigint header would force a lookup on both sides of every
-- legality check (which is exactly what `transition_task()` has to do);
-- `quotes_summary` then needs no join to render a badge, keeping it in the
-- scalar-subquery-only shape the view file demands; and Realtime
-- `postgres_changes` delivers raw column values, so a client receiving
-- `status_id: 7` has learned nothing where `status_key: 'accepted'` is
-- self-describing. The cost is that renaming a key is a foreign-key cascade,
-- which `on update cascade` handles.
create table public.quotes (
    id             bigint generated by default as identity primary key,
    quote_number   text not null unique,
    title          text,
    -- The deal is provenance, not ownership: a quote outlives the opportunity
    -- it was raised against.
    deal_id        bigint references public.deals(id) on delete set null,
    company_id     bigint not null references public.companies(id) on delete restrict,
    contact_id     bigint references public.contacts(id) on delete set null,
    -- The owner, and what drives RLS.
    sales_id       bigint not null references public.sales(id),
    price_list_id  bigint,
    currency       character(3) not null check (currency ~ '^[A-Z]{3}$'),
    status_key     text not null default 'draft'
        references public.quote_statuses(key) on update cascade,
    -- A MIRROR of the current version's, kept by `quote_versions_sync_header`.
    -- A client writes them on insert only, where they seed version 1; after
    -- that they are edited on the draft version (`quotes_header_guard`). The
    -- copy is here for `quotes_expiring_idx` and for the list.
    valid_until    date,
    terms          text,
    internal_notes text,
    created_by     bigint references public.sales(id),
    created_at     timestamp with time zone not null default now(),
    updated_at     timestamp with time zone not null default now(),
    -- A quote priced from a list in another currency is a document whose
    -- totals mean nothing. The composite key makes it unrepresentable rather
    -- than merely discouraged.
    constraint quotes_price_list_currency_fkey
        foreign key (price_list_id, currency)
        references public.price_lists (id, currency),
    -- Foreign-key target for `quote_versions` and `quote_comments`, so a
    -- version cannot carry a currency its quote does not.
    constraint quotes_id_currency_key unique (id, currency),
    constraint quotes_number_not_blank check (btrim(quote_number) <> '')
);

-- The quotes panel on a deal, rendered on every deal open.
create index quotes_deal_id_idx on public.quotes (deal_id) where deal_id is not null;
-- "My quotes by status" -- the list's default, and the hottest query here.
create index quotes_sales_status_idx on public.quotes (sales_id, status_key);
create index quotes_company_id_idx on public.quotes (company_id);

-- The expiry sweeper's ONLY query. Partial, so it stays the size of the pending
-- work rather than the size of the quote history -- the `task_reminders_due`
-- idiom.
create index quotes_expiring_idx on public.quotes (valid_until)
    where valid_until is not null
      and status_key in ('sent', 'viewed', 'under_review');

-- One row per document the customer was (or will be) shown.
--
-- `issued_at is null` means THIS IS THE WORKING DRAFT. `issued_at is not null`
-- means THIS IS A DOCUMENT A CUSTOMER WAS SHOWN, and it is immutable forever
-- (see the freeze guards in 02_functions.sql). Revising copies rather than
-- edits, which is what makes the customer's copy still byte-identical to what
-- they were shown -- the same thing Odoo and Salesforce CPQ do, for the same
-- reason: a commercial commitment you can edit is not one.
--
-- `party_snapshot` is the ONLY jsonb blob in this module, and the exception is
-- argued rather than assumed: the relational lines carry the prices (D6),
-- but "the customer's address on the day we sent it" is not a queryable
-- dimension, and normalising it would mean versioning `companies`.
create table public.quote_versions (
    id                  bigint generated by default as identity primary key,
    quote_id            bigint not null,
    -- Carrier for the composite foreign key below. Never edited on its own.
    currency            character(3) not null,
    version_number      smallint not null check (version_number > 0),
    issued_at           timestamp with time zone,
    issued_by           bigint references public.sales(id),
    superseded_at       timestamp with time zone,
    valid_until         date,
    terms               text,
    party_snapshot      jsonb,
    -- A RECORD OF INTENT ONLY. The discount that actually applies is on each
    -- line; this is the figure somebody asked for. Keeping both is what lets
    -- the document stay honest about where the discount landed.
    discount_percent    numeric(5,2)
        check (discount_percent is null
               or (discount_percent >= 0 and discount_percent <= 100)),
    subtotal            numeric(14,2) not null default 0,
    discount_total      numeric(14,2) not null default 0,
    tax_total           numeric(14,2) not null default 0,
    total               numeric(14,2) not null default 0,
    accepted_at         timestamp with time zone,
    accepted_by_name    text,
    accepted_by_email   extensions.citext,
    accepted_ip         inet,
    -- `otp_email` and `esign` are listed here DELIBERATELY, before either
    -- exists: adding OTP is then one table plus one route plus one branch, and
    -- e-signature is a webhook plus `acceptance_evidence` -- neither needs a
    -- schema change to this table (§6.4).
    acceptance_method   text
        check (acceptance_method in ('portal_click', 'otp_email', 'esign', 'offline')),
    acceptance_evidence jsonb,
    rejected_at         timestamp with time zone,
    rejected_reason     text,
    rejected_reason_code text
        check (rejected_reason_code in ('price', 'terms', 'delivery_time',
                                        'product', 'other')),
    created_at          timestamp with time zone not null default now(),
    constraint quote_versions_quote_fkey
        foreign key (quote_id, currency)
        references public.quotes (id, currency) on delete cascade,
    unique (quote_id, version_number),
    -- Foreign-key target for `quote_lines`, `quote_comments` and
    -- `quote_access_tokens`.
    constraint quote_versions_id_quote_key unique (id, quote_id),
    -- "Issued" without who issued it is the exact hole this module exists to
    -- close.
    constraint quote_versions_issued_consistency
        check ((issued_at is null) = (issued_by is null)),
    -- A draft cannot be superseded: there is nothing it replaced.
    constraint quote_versions_superseded_requires_issue
        check (superseded_at is null or issued_at is not null),
    constraint quote_versions_acceptance_consistency
        check ((accepted_at is null) = (acceptance_method is null)),
    -- One terminal answer per document. A version both accepted and rejected is
    -- not a state this negotiation can be in.
    constraint quote_versions_one_outcome
        check (accepted_at is null or rejected_at is null)
);

-- THE index the whole design rests on. Without it, two browser tabs produce two
-- drafts and the "current version" lateral picks one arbitrarily.
create unique index quote_versions_one_draft
    on public.quote_versions (quote_id) where issued_at is null;

-- "The issued versions of this quote, newest first" -- the version history
-- panel, and the lookup `issue_quote_version()` makes to supersede the previous
-- one.
create index quote_versions_issued_idx
    on public.quote_versions (quote_id, version_number desc)
    where issued_at is not null;

-- The snapshot, as COLUMNS rather than a jsonb blob (D6): the reports module
-- has to be able to answer "what did we sell, at what price", and a jsonb
-- snapshot is invisible to `run_report()`.
--
-- ROUNDING POLICY: round per line, then sum. That is what the printed document
-- shows and what every LATAM invoicing system expects. Summing unrounded values
-- and rounding once produces a total that contradicts its own visible line
-- amounts by cents -- the kind of discrepancy a customer notices and a
-- salesperson cannot explain.
create table public.quote_lines (
    id               bigint generated by default as identity primary key,
    version_id       bigint not null,
    -- Carrier for the composite foreign key below.
    quote_id         bigint not null,
    -- Provenance only. `on delete set null` is correct because the frozen
    -- columns below ARE the record; the UI still never offers to delete a
    -- product that has been quoted, it deactivates.
    product_id       bigint references public.products(id) on delete set null,
    sku              text,
    name             text not null,
    description      text,
    unit             text,
    quantity         numeric(14,3) not null check (quantity > 0),
    unit_price       numeric(14,2) not null check (unit_price >= 0),
    discount_percent numeric(5,2) not null default 0
        check (discount_percent >= 0 and discount_percent <= 100),
    -- Provenance …
    tax_rate_id      bigint references public.tax_rates(id),
    -- … and the record, frozen. The rate that applied on the day, whatever the
    -- catalogue says now.
    --
    -- NO DEFAULT, on purpose. `default 0` made an omitted percentage
    -- indistinguishable from an explicit 0%, so a line posted with a
    -- `tax_rate_id` and no percentage was taxed at zero -- silently, which is
    -- the worst way for a document to be wrong (§13.6 #10).
    -- `quote_lines_snapshot_defaults` fills it from the rate instead: a line
    -- naming neither still lands at 0, and one that somehow reaches the table
    -- with a null percentage fails loudly rather than under-taxing.
    tax_rate_percent numeric(5,2) not null
        check (tax_rate_percent >= 0 and tax_rate_percent <= 100),
    position         smallint not null default 0,
    --
    -- Each column is computed from BASE columns: a generated column may not
    -- reference another generated column, which is why round() is repeated
    -- rather than chained. round(numeric, int) is immutable, so all four are
    -- legal STORED -- and being STORED is what makes the totals the server's
    -- (D8). A total computed in the browser is a negotiable total.
    --
    line_gross    numeric(14,2) generated always as
        (round(quantity * unit_price, 2)) stored,
    line_discount numeric(14,2) generated always as
        (round(round(quantity * unit_price, 2) * discount_percent / 100, 2)) stored,
    line_tax      numeric(14,2) generated always as
        (round((round(quantity * unit_price, 2)
                - round(round(quantity * unit_price, 2) * discount_percent / 100, 2))
               * tax_rate_percent / 100, 2)) stored,
    line_total    numeric(14,2) generated always as
        (round(quantity * unit_price, 2)
         - round(round(quantity * unit_price, 2) * discount_percent / 100, 2)
         + round((round(quantity * unit_price, 2)
                  - round(round(quantity * unit_price, 2) * discount_percent / 100, 2))
                 * tax_rate_percent / 100, 2)) stored,
    --
    -- The `team_member_budgets` trick. With a plain `references
    -- quote_versions(id)`, quote A's version paired with quote B's id is
    -- accepted, and that row sums into one quote's total while appearing in
    -- neither document -- so the first symptom is a total that contradicts its
    -- own breakdown.
    --
    constraint quote_lines_version_fkey
        foreign key (version_id, quote_id)
        references public.quote_versions (id, quote_id) on delete cascade,
    constraint quote_lines_name_not_blank check (btrim(name) <> '')
);

-- A version's lines in document order -- every document render.
create index quote_lines_version_position
    on public.quote_lines (version_id, "position");
-- "What did we sell, at what price" -- the reports query D6 exists to enable.
create index quote_lines_product_idx
    on public.quote_lines (product_id) where product_id is not null;

-- The negotiation thread, both sides of it (§2.5).
--
-- `visibility` defaults to 'internal', because a shared-by-default field turns
-- an internal remark about a customer's budget into a message to that customer.
create table public.quote_comments (
    id                  bigint generated by default as identity primary key,
    quote_id            bigint not null,
    -- Carrier for the composite foreign key below.
    currency            character(3) not null,
    -- Which document the remark is about. Null for a comment on the quote as a
    -- whole.
    version_id          bigint,
    parent_id           bigint references public.quote_comments(id) on delete cascade,
    author_sales_id     bigint references public.sales(id),
    author_kind         text not null default 'internal'
        check (author_kind in ('internal', 'customer')),
    author_name         text,
    author_email        extensions.citext,
    visibility          text not null default 'internal'
        check (visibility in ('internal', 'shared')),
    body                text not null,
    -- Drives the "customer wrote and nobody answered" badge on the list. Not
    -- derivable from `created_at`: somebody reading the thread is the fact, and
    -- nothing else records it.
    read_by_internal_at timestamp with time zone,
    created_at          timestamp with time zone not null default now(),
    edited_at           timestamp with time zone,
    deleted_at          timestamp with time zone,
    constraint quote_comments_quote_fkey
        foreign key (quote_id, currency)
        references public.quotes (id, currency) on delete cascade,
    constraint quote_comments_version_fkey
        foreign key (version_id, quote_id)
        references public.quote_versions (id, quote_id) on delete cascade,
    constraint quote_comments_body_length
        check (char_length(body) between 1 and 8000),
    --
    -- The illegal combinations, made UNREPRESENTABLE. A customer comment marked
    -- internal would be invisible to the person who wrote it; a customer
    -- comment attributed to a `sales` row is a forgery. The constraint means a
    -- bug in the portal function CANNOT produce either one.
    --
    constraint quote_comments_author check (
        (author_kind = 'internal' and author_sales_id is not null)
     or (author_kind = 'customer'  and author_sales_id is null
         and visibility = 'shared' and btrim(coalesce(author_name, '')) <> ''))
);

-- The shared thread -- every portal load.
create index quote_comments_shared
    on public.quote_comments (quote_id, created_at)
    where visibility = 'shared' and deleted_at is null;
-- "Customer wrote and nobody answered" -- the attention badge on the list.
create index quote_comments_unanswered
    on public.quote_comments (quote_id)
    where author_kind = 'customer' and read_by_internal_at is null
      and deleted_at is null;
create index quote_comments_thread
    on public.quote_comments (parent_id, created_at) where deleted_at is null;

-- What the public portal authenticates with (§6.2).
--
-- ONLY THE sha256 OF THE TOKEN IS STORED, NEVER THE TOKEN. `sha256(bytea)` is
-- core PostgreSQL, no extension needed. The raw token exists exactly once, as
-- the return value of `issue_quote_version()`.
--
-- The UX consequence is real and the UI has to say it out loud: "copy link"
-- only works at the moment of issue. Afterwards the action is "generate a new
-- link", which mints a fresh token; older ones keep working until revoked.
-- Since tokens are per recipient and carry a `label`, that is coherent -- but
-- it differs from the stable-forever link HubSpot offers.
--
-- The token is bound to THE VERSION it was minted for, which is what makes
-- "you are looking at a superseded quote" detectable at accept time.
create table public.quote_access_tokens (
    id           bigint generated by default as identity primary key,
    quote_id     bigint not null,
    version_id   bigint not null,
    token_hash   bytea not null unique,
    label        text,
    created_by   bigint references public.sales(id),
    created_at   timestamp with time zone not null default now(),
    expires_at   timestamp with time zone not null,
    revoked_at   timestamp with time zone,
    revoked_by   bigint references public.sales(id),
    last_seen_at timestamp with time zone,
    view_count   integer not null default 0 check (view_count >= 0),
    constraint quote_access_tokens_version_fkey
        foreign key (version_id, quote_id)
        references public.quote_versions (id, quote_id) on delete cascade,
    -- A 32-byte digest. A shorter value here means somebody stored something
    -- that is not a sha256, and the only thing that could be is the token.
    constraint quote_access_tokens_hash_length
        check (octet_length(token_hash) = 32)
);

create index quote_access_tokens_quote
    on public.quote_access_tokens (quote_id, created_at desc);

--
-- Audit trail (§5)
--
-- TWO append-only tables rather than one event log, because internal moves and
-- customer actions answer different questions and carry different columns.
--
-- Both get the DOUBLE BLINDFOLD the repo already applies to
-- `deal_stage_changes`: no insert/update/delete policy AND the privileges
-- revoked in 06_grants.sql, plus a `reject_quote_history_mutation()` trigger.
-- Both halves are needed: an UPDATE or DELETE that matches no row SUCCEEDS
-- SILENTLY, and TRUNCATE ignores RLS entirely.
--

-- Who moved the quote, when, and why.
create table public.quote_status_changes (
    id            bigint generated by default as identity primary key,
    quote_id      bigint not null
        references public.quotes(id) on update cascade on delete cascade,
    -- Null for the first transition of a quote created straight into a
    -- non-default status: there is no previous status to name.
    from_status   text,
    to_status     text not null,
    reason        text,
    -- Null when the actor has no `sales` row (the sweeper, the portal), never
    -- silently attributed to somebody else.
    sales_id      bigint references public.sales(id),
    actor_kind    text not null default 'internal'
        check (actor_kind in ('internal', 'customer', 'system')),
    changed_at    timestamp with time zone not null default now(),
    attachments   jsonb[],
    -- Why an admin was allowed to issue past the discount rule. Null on every
    -- move that satisfied it, so `where override_reason is not null` is the
    -- list of moves that skipped the gate.
    override_reason text,
    -- Per-quote monotonic counter, computed as `emit_task_event()` computes
    -- its own. `changed_at` alone cannot order two moves in one transaction:
    -- `now()` is the transaction timestamp and would be identical.
    seq           bigint not null,
    unique (quote_id, seq),
    constraint quote_status_changes_to_not_blank check (btrim(to_status) <> ''),
    constraint quote_status_changes_differ
        check (from_status is distinct from to_status)
);

create index quote_status_changes_quote
    on public.quote_status_changes (quote_id, changed_at desc);
create index quote_status_changes_sales_id
    on public.quote_status_changes (sales_id);

-- What the customer did, and from where.
--
-- `ip_address` lives HERE and appears in no timeline payload: it belongs in the
-- audit table, not on a screen a whole sales team reads.
create table public.quote_portal_events (
    id          bigint generated by default as identity primary key,
    quote_id    bigint not null references public.quotes(id) on delete cascade,
    version_id  bigint references public.quote_versions(id) on delete set null,
    token_id    bigint references public.quote_access_tokens(id) on delete set null,
    event_type  text not null
        check (event_type in ('viewed', 'downloaded', 'commented', 'accepted',
                              'rejected', 'throttled', 'token_invalid')),
    occurred_at timestamp with time zone not null default clock_timestamp(),
    -- Passed as EXPLICIT PARAMETERS by the portal function, never read from
    -- `request_context()`: a service-role RPC has no request headers at all,
    -- and silently receiving nulls would produce an audit trail that looks
    -- complete and is not.
    ip_address  inet,
    user_agent  text,
    actor_name  text,
    actor_email extensions.citext,
    payload     jsonb not null default '{}'::jsonb,
    seq         bigint not null,
    unique (quote_id, seq)
);

create index quote_portal_events_quote
    on public.quote_portal_events (quote_id, occurred_at desc);
-- The portal throttle, once per portal request.
create index quote_portal_events_token
    on public.quote_portal_events (token_id, occurred_at desc);

--
-- Discount approval, as data (§3.1)
--
-- The ceiling each role may grant without an admin's written override. Keyed on
-- `sales_role`, so the rule is three rows and not three `if` branches.
--
-- `enforced_from is null` means NOT ENFORCED -- the same escape valve
-- `deal_stage_requirements` uses, so switching the rule on does not freeze
-- every quote in flight on deploy day.
create table public.quote_discount_rules (
    role                  public.sales_role primary key,
    max_discount_percent  numeric(5,2) not null
        check (max_discount_percent >= 0 and max_discount_percent <= 100),
    -- Below the ceiling but above this, the issue still needs a written reason
    -- (`issue_quote_version(p_reason)`), stored on the `sent` history row. A
    -- written approval already is one. Null means no such band.
    requires_reason_above numeric(5,2)
        check (requires_reason_above is null
               or (requires_reason_above >= 0 and requires_reason_above <= 100)),
    enforced_from         timestamp with time zone,
    updated_at            timestamp with time zone not null default now()
);
