--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

-- Enums

-- Access level of a CRM user.
--   admin   - full access, manages users and application configuration
--   manager - sales manager: sees and reassigns every record, but does not manage users
--   rep     - sales representative: only sees and edits the records they own
create type public.sales_role as enum ('admin', 'manager', 'rep');

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false,
    -- Declared last on purpose: the migration that replaced `administrator`
    -- appends `role` at the end of the table, and Postgres cannot insert a
    -- column mid-table. Keeping the same physical order here avoids a phantom
    -- diff on every `supabase db diff` run.
    role public.sales_role not null default 'rep'::public.sales_role
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

--
-- Leads: prospects that have not been qualified yet.
--
-- Deliberately decoupled from `companies`: a lead usually arrives with nothing
-- more than a company name typed into a web form, long before there is a
-- company record to point at. `public.convert_lead()` turns a qualified lead
-- into a company + contact (+ optional deal) and records what it produced.
--
create table public.leads (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    first_name text,
    last_name text,
    email extensions.citext,
    phone text,
    company_name text,
    company_id bigint,
    title text,
    source text,
    status text not null default 'new'::text,
    score smallint,
    notes text,
    tags bigint[],
    sales_id bigint,
    converted_at timestamp with time zone,
    converted_contact_id bigint,
    converted_company_id bigint,
    converted_deal_id bigint
);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.leads
    add constraint leads_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.leads
    add constraint leads_company_id_fkey foreign key (company_id) references public.companies(id) on delete set null;

-- The conversion pointers are provenance, not ownership: if the record they
-- produced is later deleted the lead stays, with the pointer cleared.
alter table public.leads
    add constraint leads_converted_contact_id_fkey foreign key (converted_contact_id) references public.contacts(id) on delete set null;

alter table public.leads
    add constraint leads_converted_company_id_fkey foreign key (converted_company_id) references public.companies(id) on delete set null;

alter table public.leads
    add constraint leads_converted_deal_id_fkey foreign key (converted_deal_id) references public.deals(id) on delete set null;

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);

--
-- Ownership indexes
--
-- Every owner-scoped RLS policy filters on `sales_id`, and so do the
-- "only mine" list filters. Without these the policies degrade to a sequential
-- scan on every list query.
--
create index companies_sales_id_idx on public.companies using btree (sales_id);
create index contacts_sales_id_idx on public.contacts using btree (sales_id);
create index deals_sales_id_idx on public.deals using btree (sales_id);
create index contact_notes_sales_id_idx on public.contact_notes using btree (sales_id);
create index deal_notes_sales_id_idx on public.deal_notes using btree (sales_id);

-- tasks.contact_id had no index at all: it now carries both the contact detail
-- page lookup and the task RLS policy, which resolves ownership through the
-- parent contact. This is by far the most scanned index in the schema.
create index tasks_contact_id_idx on public.tasks using btree (contact_id);
-- The task list filters by owner and orders by due date.
create index tasks_sales_id_due_date_idx on public.tasks using btree (sales_id, due_date);

--
-- List ordering indexes
--
-- Every one of these backs an `order by ... limit n` that would otherwise
-- top-N heapsort the whole table on each page load. Partial where the list is
-- always filtered the same way.
--
create index contacts_last_seen_idx on public.contacts using btree (last_seen desc);
create index contact_notes_date_idx on public.contact_notes using btree (date desc);
create index deal_notes_date_idx on public.deal_notes using btree (date desc);
-- Backs `contacts_summary.nb_tasks`.
create index tasks_pending_contact_id_idx on public.tasks using btree (contact_id) where done_date is null;
-- Backs the "tasks due" lists, which never show completed tasks.
create index tasks_pending_due_date_idx on public.tasks using btree (due_date) where done_date is null;
-- Backs the deal kanban, which only ever lists non-archived deals.
create index deals_active_index_idx on public.deals using btree (index desc) where archived_at is null;

-- Leads: owner scoping (RLS + "only mine"), the default list ordering, and the
-- conversion pointers used by the contact/company/deal detail pages.
create index leads_sales_id_idx on public.leads using btree (sales_id);
create index leads_created_at_idx on public.leads using btree (created_at desc);
create index leads_company_id_idx on public.leads using btree (company_id);
create index leads_converted_contact_id_idx on public.leads using btree (converted_contact_id);
