--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";
-- Lets `team_budgets` put `team_id with =` in a GiST exclusion constraint
-- alongside the daterange overlap test; plain GiST cannot index bigint equality.
create extension if not exists "btree_gist" with schema "extensions";
-- The reminder scheduler (§9.3). Declared here even though the cron JOB lives
-- in a migration (a row in `cron.job` is data, not schema): without this line
-- `supabase db diff` sees an extension the declarative schema does not know
-- about and helpfully generates `drop extension pg_cron`, which silently kills
-- every reminder in the product.
create extension if not exists "pg_cron";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

-- Enums

-- Access level of a CRM user.
--   admin   - full access, manages users and application configuration
--   manager - sales manager: sees and reassigns every record, but does not manage users
--   rep     - sales representative: only sees and edits the records they own
create type public.sales_role as enum ('admin', 'manager', 'rep');

-- Task module (§3.3): assignment role, polymorphic link target, event type.
create type public.task_role as enum ('owner', 'collaborator', 'watcher', 'team');

-- Polymorphic link targets. Only the four that exist today are exercised by
-- the code, but the enum is the extension point for future entities (§14.1).
create type public.task_entity as enum
    ('contact', 'lead', 'company', 'deal', 'project', 'ticket', 'invoice', 'quote', 'order');

create type public.task_event_type as enum (
    -- lifecycle
    'task.created', 'task.updated', 'task.scheduled', 'task.started', 'task.waiting',
    'task.resumed', 'task.blocked', 'task.unblocked', 'task.completed', 'task.reopened',
    'task.canceled', 'task.archived', 'task.unarchived', 'task.deleted', 'task.restored',
    -- planning
    'task.rescheduled', 'task.priority_changed', 'task.type_changed', 'task.title_changed',
    'task.description_changed', 'task.due_removed',
    -- people
    'task.assigned', 'task.unassigned', 'task.reassigned', 'task.watcher_added',
    'task.watcher_removed', 'task.team_assigned',
    -- collaboration
    'comment.created', 'comment.edited', 'comment.deleted', 'comment.reaction_added',
    'comment.reaction_removed', 'mention.created',
    -- artefacts
    'attachment.added', 'attachment.removed',
    'checklist.item_added', 'checklist.item_completed', 'checklist.item_reopened',
    'checklist.item_removed', 'checklist.item_reordered',
    -- links & graph
    'link.added', 'link.removed', 'link.primary_changed',
    'dependency.added', 'dependency.removed', 'dependency.satisfied',
    -- time & reminders
    'timelog.started', 'timelog.stopped', 'timelog.edited',
    'reminder.created', 'reminder.updated', 'reminder.canceled',
    'reminder.sent', 'reminder.failed', 'reminder.acknowledged',
    -- system
    'automation.applied', 'sla.breached', 'sla.warning', 'import.applied'
);

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint,
    -- Which team the deal counts for in the budget dashboard. Seeded from the
    -- owner's team on creation, then edited on its own: a rep who belongs to
    -- two teams would otherwise make the same amount count twice, and moving a
    -- rep between teams would silently rewrite closed history.
    -- The foreign key is added after public.teams exists, further down.
    team_id bigint
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false,
    -- Declared last on purpose: the migration that replaced `administrator`
    -- appends `role` at the end of the table, and Postgres cannot insert a
    -- column mid-table. Keeping the same physical order here avoids a phantom
    -- diff on every `supabase db diff` run.
    role public.sales_role not null default 'rep'::public.sales_role
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

--
-- Why a deal moved from one stage to the next.
--
-- The kanban used to write `deals.stage` and nothing else, so the board could
-- say a deal reached "proposal sent" but never why, when, or on whose call.
-- This is the append-only record of every transition: the reason typed at the
-- moment of the move, the files that justified it, and the person who did it.
--
-- Written by `public.deals_log_stage_change()` only, on any path that changes
-- the stage (kanban, edit form, import). A client cannot insert here, so the
-- history cannot be back-dated or invented -- see 05_policies.sql.
--
-- `attachments` mirrors `deal_notes.attachments`: the same `jsonb[]` of
-- `{src,title,type,path}` objects stored in the public `attachments` bucket,
-- so one attachment renderer serves both.
--
create table public.deal_stage_changes (
    id bigint generated by default as identity primary key,
    deal_id bigint not null references public.deals(id) on update cascade on delete cascade,
    -- Null for the first transition of a deal created straight into a
    -- non-default stage: there is no previous stage to name.
    from_stage text,
    to_stage text not null,
    -- Free text, required when the move goes through `move_deal_stage()`, null
    -- when the stage was changed by another path (that gap is the point: an
    -- undocumented move stays visible as one).
    reason text,
    -- Who moved it. Null only when the actor has no `sales` row (service role,
    -- an import), never silently attributed to somebody else.
    sales_id bigint references public.sales(id),
    changed_at timestamp with time zone not null default now(),
    attachments jsonb[],
    constraint deal_stage_changes_to_stage_not_blank check (btrim(to_stage) <> ''),
    constraint deal_stage_changes_stages_differ check (from_stage is distinct from to_stage)
);

-- The deal timeline reads this table newest-first, always for one deal.
create index deal_stage_changes_deal_id_idx
    on public.deal_stage_changes (deal_id, changed_at desc);
create index deal_stage_changes_sales_id_idx
    on public.deal_stage_changes (sales_id);

--
-- Leads: prospects that have not been qualified yet.
--
-- Deliberately decoupled from `companies`: a lead usually arrives with nothing
-- more than a company name typed into a web form, long before there is a
-- company record to point at. `public.convert_lead()` turns a qualified lead
-- into a company + contact (+ optional deal) and records what it produced.
--
create table public.leads (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    first_name text,
    last_name text,
    email extensions.citext,
    phone text,
    company_name text,
    company_id bigint,
    title text,
    source text,
    status text not null default 'new'::text,
    score smallint,
    notes text,
    tags bigint[],
    sales_id bigint,
    converted_at timestamp with time zone,
    converted_contact_id bigint,
    converted_company_id bigint,
    converted_deal_id bigint
);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

--
-- Task catalogues (§3.3)
--

create table public.task_statuses (
    id             bigint generated by default as identity primary key,
    key            text not null unique,             -- 'pending', 'in_progress', …
    label          text not null,
    color          text not null default 'gray',
    rank           smallint not null,                -- display order
    is_open        boolean not null default true,    -- counts as "open work"
    is_terminal    boolean not null default false,   -- no transitions out (except reopen)
    counts_as_done boolean not null default false,
    is_system      boolean not null default false    -- system states cannot be deleted
);

create table public.task_priorities (
    id        bigint generated by default as identity primary key,
    key       text not null unique,             -- 'low' | 'normal' | 'high' | 'urgent'
    label     text not null,
    color     text not null,
    rank      smallint not null,
    sla_hours integer                            -- null = no SLA
);

create table public.task_types (
    id        bigint generated by default as identity primary key,
    key       text not null unique,             -- 'call', 'email', 'demo', …
    label     text not null,
    icon      text,
    is_active boolean not null default true
);

create table public.tasks (
    id                bigint generated by default as identity primary key,

    -- legacy shims (kept read-only for one release; reads move to the new
    -- columns and to task_links; dropped later — see enterprise-task-module)
    contact_id        bigint,                  -- was NOT NULL; see task_links
    type              text,
    text              text,
    due_date          timestamp with time zone,
    done_date         timestamp with time zone,
    sales_id          bigint,

    -- content (§3.3)
    title             text not null,
    description       text,
    task_type_id      bigint not null,

    -- classification
    status_id         bigint not null,
    priority_id       bigint not null,

    -- scheduling
    start_at          timestamp with time zone,
    completed_at      timestamp with time zone,
    completed_by      bigint,
    canceled_at       timestamp with time zone,
    cancel_reason     text,

    -- ownership (denormalized from task_assignments for query speed)
    owner_sales_id    bigint not null,
    created_by        bigint not null,

    -- lifecycle bookkeeping
    created_at        timestamp with time zone not null default now(),
    updated_at        timestamp with time zone not null default now(),
    deleted_at        timestamp with time zone,
    deleted_by        bigint,
    archived_at       timestamp with time zone,

    -- denormalized counters (maintained by trigger)
    reschedule_count  integer not null default 0,
    reassign_count    integer not null default 0,
    comment_count     integer not null default 0,
    attachment_count  integer not null default 0,
    checklist_total   integer not null default 0,
    checklist_done    integer not null default 0,
    blocked_seconds   bigint  not null default 0,
    -- When the current block started. Phase 1 shipped `blocked_seconds` with a
    -- trigger that deferred the arithmetic to a scheduled job nobody wrote, so
    -- the counter never moved. Recording the entry instant makes the duration
    -- exact and computable on the way out, with no job at all (§10.2).
    blocked_since     timestamp with time zone,
    total_open_seconds bigint not null default 0,

    -- provenance
    source            text not null default 'manual'
                      check (source in ('manual', 'automation', 'import', 'api', 'email')),

    -- search
    search_tsv tsvector generated always as (
        setweight(to_tsvector('simple', coalesce(title, '')), 'A') ||
        setweight(to_tsvector('simple', coalesce(description, '')), 'B')
    ) stored,

    constraint tasks_completed_consistency
        check ((completed_at is null) = (completed_by is null))
);

--
-- Teams (§3.2). Deliberately two columns: a team exists to hang assignment,
-- escalation and reporting off, not to model an org chart. Managed from /teams
-- by admins and managers (05_policies.sql).
--

create table public.teams (
    id          bigint generated by default as identity primary key,
    name        text not null,
    description text,
    created_at  timestamp with time zone not null default now()
);

create table public.team_members (
    id        bigint generated by default as identity primary key,
    team_id   bigint not null references public.teams(id) on delete cascade,
    sales_id  bigint not null references public.sales(id) on delete cascade,
    created_at timestamp with time zone not null default now(),
    unique (team_id, sales_id),
    -- Redundant against the primary key on its own; it exists so
    -- `team_member_budgets` can point a composite foreign key at it and make a
    -- cross-team allocation unrepresentable. See that table below.
    constraint team_members_id_team_id_key unique (id, team_id)
);

-- "Which teams am I in" — asked by every task RLS check (§7.3). The
-- `unique (team_id, sales_id)` index above cannot serve it: wrong leading
-- column.
create index team_members_sales_id_idx
    on public.team_members (sales_id, team_id);

--
-- What a team is expected to sell, per period.
--
-- A separate table rather than a column on `teams`: a budget without a period
-- cannot answer "how did we do in Q3", and overwriting the number to set the
-- next target would destroy the only record of the previous one.
--
-- The exclusion constraint is the load-bearing one. Two overlapping periods for
-- the same team would make the dashboard pick a vigente budget arbitrarily,
-- which shows up as a number that changes between page loads.
--
create table public.team_budgets (
    id           bigint generated by default as identity primary key,
    team_id      bigint not null references public.teams(id) on delete cascade,
    period_start date not null,
    period_end   date not null,
    amount       numeric(14,2) not null check (amount >= 0),
    created_at   timestamp with time zone not null default now(),
    constraint team_budgets_period_order check (period_end > period_start),
    constraint team_budgets_no_overlap exclude using gist (
        team_id with =,
        daterange(period_start, period_end, '[]') with &&
    ),
    -- Foreign-key target for `team_member_budgets`, same reason as on
    -- `team_members` above.
    constraint team_budgets_id_team_id_key unique (id, team_id)
);

--
-- What each member of a team is expected to sell out of the team's target.
--
-- Keyed on the BUDGET, not on the team: an allocation with no period is the
-- mistake `team_budgets` exists to avoid — it would follow the team into the
-- next period and silently restate what was promised for the last one. Hanging
-- it off `team_budgets.id` makes "open a new period" mean "start from a blank
-- allocation", which is the honest default.
--
-- Keyed on the MEMBERSHIP rather than on the person: somebody removed from the
-- team carries no quota in it, so the roster quotas always sum to the team's
-- allocated total and the breakdown reconciles with the figure it sits under.
--
-- The two composite foreign keys are the load-bearing part. With plain
-- `references team_budgets(id)` / `references team_members(id)`, team A's
-- budget paired with team B's member is accepted, and that row is invisible in
-- every screen: it sums into one team's allocated total while the roster it
-- should appear in never shows it.
--
-- The sum is deliberately NOT constrained to the team budget. Reallocating
-- between two members is two writes, and an invariant enforced per row would
-- reject the first one purely for being first. Over- and under-allocation are
-- reported by the UI instead, which is also the only place that can say by how
-- much.
--
create table public.team_member_budgets (
    id             bigint generated by default as identity primary key,
    team_id        bigint not null,
    budget_id      bigint not null,
    team_member_id bigint not null,
    amount         numeric(14,2) not null check (amount >= 0),
    created_at     timestamp with time zone not null default now(),
    unique (budget_id, team_member_id),
    foreign key (budget_id, team_id)
        references public.team_budgets (id, team_id) on delete cascade,
    foreign key (team_member_id, team_id)
        references public.team_members (id, team_id) on delete cascade
);

-- "What is this person's quota", asked by the member drill-down. The unique
-- index above leads with `budget_id` and cannot serve it.
create index team_member_budgets_team_member_id_idx
    on public.team_member_budgets (team_member_id);

-- The deal -> team link, declared here because it is the first point where both
-- tables exist. The partial index serves the dashboard, which never sums
-- archived deals.
alter table public.deals
    add constraint deals_team_id_fkey foreign key (team_id)
    references public.teams(id);

create index deals_team_id_idx on public.deals (team_id) where archived_at is null;

--
-- Assignment: roles, closed rather than deleted (§3.3)
--

create table public.task_assignments (
    id             bigint generated by default as identity primary key,
    task_id        bigint not null references public.tasks(id) on delete restrict,
    sales_id       bigint references public.sales(id),
    team_id        bigint references public.teams(id),
    role           public.task_role not null,
    assigned_at    timestamp with time zone not null default now(),
    assigned_by    bigint not null references public.sales(id),
    unassigned_at  timestamp with time zone,     -- closed, never deleted
    unassigned_by  bigint references public.sales(id),
    reason         text,

    constraint task_assignments_subject
        check (num_nonnulls(sales_id, team_id) = 1)
);

-- Exactly one active owner at a time.
create unique index task_assignments_single_owner
    on public.task_assignments (task_id)
    where role = 'owner' and unassigned_at is null;

-- "My work" — the single most frequent query in the product.
create index task_assignments_active_by_sale
    on public.task_assignments (sales_id, role)
    where unassigned_at is null;

--
-- Polymorphic links (fixes W1) (§3.3)
--

create table public.task_links (
    id          bigint generated by default as identity primary key,
    task_id     bigint not null references public.tasks(id) on delete restrict,
    entity_type public.task_entity not null,
    entity_id   bigint not null,
    is_primary  boolean not null default false,
    linked_at   timestamp with time zone not null default now(),
    linked_by   bigint not null references public.sales(id),
    unlinked_at timestamp with time zone,
    -- Denormalized snapshot so the timeline can still say "vinculada a Acme"
    -- after the record is gone (§14.3).
    entity_label text
);

create unique index task_links_unique_active
    on public.task_links (task_id, entity_type, entity_id)
    where unlinked_at is null;

create unique index task_links_single_primary
    on public.task_links (task_id)
    where is_primary and unlinked_at is null;

-- The reverse lookup: "tasks on this deal". Leading columns are the filter.
create index task_links_entity
    on public.task_links (entity_type, entity_id, task_id)
    where unlinked_at is null;

--
-- State machine (§4)
--

create table public.task_transitions (
    id              bigint generated by default as identity primary key,
    from_status_key text not null,
    to_status_key   text not null,
    label           text,
    requires_reason boolean not null default false,
    is_system       boolean not null default false,
    unique (from_status_key, to_status_key)
);

--
-- Immutable event stream (§5)
--

create table public.task_events (
    id             bigint generated by default as identity,
    task_id        bigint not null,
    event_type     public.task_event_type not null,
    occurred_at    timestamp with time zone not null default clock_timestamp(),

    -- actor
    actor_sales_id bigint references public.sales(id),    -- null => system
    actor_kind     text not null default 'user'
                   check (actor_kind in ('user', 'system', 'automation', 'integration', 'import')),
    on_behalf_of   bigint references public.sales(id),

    -- payload
    field          text,
    old_value      jsonb,
    new_value      jsonb,
    metadata       jsonb not null default '{}'::jsonb,
    note           text,

    -- request context (optional, best effort)
    ip_address     inet,
    user_agent     text,
    device_kind    text check (device_kind in ('web', 'mobile', 'api', 'server')),
    request_id     uuid,
    session_id     uuid,

    -- ordering & integrity
    seq            bigint not null,        -- per-task monotonic sequence
    prev_hash      bytea,
    row_hash       bytea,

    primary key (id, occurred_at)
) partition by range (occurred_at);

-- Monthly partitions, created ahead of time by a scheduled job.
create table public.task_events_2026_08 partition of public.task_events
    for values from ('2026-08-01') to ('2026-09-01');
create table public.task_events_2026_09 partition of public.task_events
    for values from ('2026-09-01') to ('2026-10-01');
create table public.task_events_2026_10 partition of public.task_events
    for values from ('2026-10-01') to ('2026-11-01');
create table public.task_events_2026_11 partition of public.task_events
    for values from ('2026-11-01') to ('2026-12-01');
create table public.task_events_2026_12 partition of public.task_events
    for values from ('2026-12-01') to ('2027-01-01');

create index task_events_task_seq on public.task_events (task_id, seq desc);
create index task_events_actor    on public.task_events (actor_sales_id, occurred_at desc);
create index task_events_type     on public.task_events (event_type, occurred_at desc);
create index task_events_meta_gin on public.task_events using gin (metadata jsonb_path_ops);

--
-- Collaboration (§8)
--
-- `body_html` from the proposal is deliberately not stored: the repo already
-- sanitizes markdown at render time with `marked` + `dompurify`, and a
-- pre-rendered column is a second copy that can drift out of sync with the
-- body it claims to represent. One source of truth, sanitized on render.
--

create table public.task_comments (
    id         bigint generated by default as identity primary key,
    task_id    bigint not null references public.tasks(id) on delete restrict,
    parent_id  bigint references public.task_comments(id),  -- one level only
    author_id  bigint not null references public.sales(id),
    body       text not null,
    -- Internal note: author, managers and admins only (§8.2).
    is_private boolean not null default false,
    edited_at  timestamp with time zone,
    edit_count integer not null default 0,
    -- Soft delete only: the body stays readable in the audit view (§8.2).
    deleted_at timestamp with time zone,
    deleted_by bigint references public.sales(id),
    created_at timestamp with time zone not null default now(),

    constraint task_comments_body_not_blank check (btrim(body) <> '')
);

create index task_comments_task on public.task_comments (task_id, created_at)
    where deleted_at is null;
create index task_comments_thread on public.task_comments (parent_id, created_at)
    where deleted_at is null;

-- Every previous body. "Edited" without the old text is not an audit trail.
create table public.task_comment_revisions (
    id         bigint generated by default as identity primary key,
    comment_id bigint not null references public.task_comments(id) on delete restrict,
    body       text not null,
    edited_by  bigint not null references public.sales(id),
    edited_at  timestamp with time zone not null default now(),
    revision   integer not null,
    unique (comment_id, revision)
);

-- Resolved @mentions. Parsed server-side from the body, never trusted from the
-- client (§8.2): the body is the truth, these rows are derived from it.
create table public.task_comment_mentions (
    id                 bigint generated by default as identity primary key,
    comment_id         bigint not null references public.task_comments(id) on delete cascade,
    mentioned_sales_id bigint references public.sales(id),
    mentioned_team_id  bigint references public.teams(id),
    notified_at        timestamp with time zone,
    read_at            timestamp with time zone,

    constraint mention_subject
        check (num_nonnulls(mentioned_sales_id, mentioned_team_id) = 1)
);

-- "Mentions of me, unread" — the notification inbox query.
create index task_comment_mentions_inbox
    on public.task_comment_mentions (mentioned_sales_id, read_at);

-- Re-parsing a body on edit must not duplicate a mention that is still there.
create unique index task_comment_mentions_unique_sale
    on public.task_comment_mentions (comment_id, mentioned_sales_id)
    where mentioned_sales_id is not null;
create unique index task_comment_mentions_unique_team
    on public.task_comment_mentions (comment_id, mentioned_team_id)
    where mentioned_team_id is not null;

-- A surrogate key rather than the natural (comment, sale, emoji) triple as the
-- primary key: PostgREST and react-admin both address a row by a single `id`,
-- and un-reacting is a delete by id. The triple stays unique, so the same
-- person cannot register the same emoji twice.
create table public.task_comment_reactions (
    id         bigint generated by default as identity primary key,
    comment_id bigint not null references public.task_comments(id) on delete cascade,
    sales_id   bigint not null references public.sales(id),
    emoji      text not null,
    created_at timestamp with time zone not null default now(),

    constraint task_comment_reactions_unique unique (comment_id, sales_id, emoji)
);

--
-- Attachments (§3.2, §8.2)
--
-- One table for both task-level and comment-level files: a comment attachment
-- is a task attachment with `comment_id` set. Two tables would mean two upload
-- flows, two policies and two counters for the same thing.
--
-- The row is metadata; the bytes live in the private `task-attachments`
-- storage bucket under `<task_id>/…`, which is what lets the storage policy
-- gate a download on `can_see_task()` (§17.3). The public `attachments` bucket
-- used by notes cannot do that: a public bucket serves any object to anyone
-- holding the URL, signed in or not.
--
create table public.task_attachments (
    id           bigint generated by default as identity primary key,
    task_id      bigint not null references public.tasks(id) on delete restrict,
    -- Null for a task-level attachment; set when the file hangs off a comment.
    comment_id   bigint references public.task_comments(id) on delete restrict,

    storage_path text not null,          -- '<task_id>/<random>.<ext>' in the bucket
    file_name    text not null,          -- what the user uploaded, for display
    mime_type    text,
    size_bytes   bigint,
    -- SHA-256 of the bytes, computed at upload time. Recorded rather than used:
    -- it is the one piece of metadata that cannot be recovered afterwards if a
    -- retention job has already moved the object.
    checksum     text,

    uploaded_by  bigint not null references public.sales(id),
    uploaded_at  timestamp with time zone not null default now(),
    -- Soft delete, like everything else in this module: the history references
    -- the attachment by id and must keep resolving.
    deleted_at   timestamp with time zone,
    deleted_by   bigint references public.sales(id),

    constraint task_attachments_file_name_not_blank check (btrim(file_name) <> ''),
    constraint task_attachments_path_not_blank check (btrim(storage_path) <> ''),
    constraint task_attachments_size_not_negative
        check (size_bytes is null or size_bytes >= 0)
);

-- "The files on this task" — the only query the detail panel makes.
create index task_attachments_task
    on public.task_attachments (task_id, uploaded_at)
    where deleted_at is null;

-- "The files on this comment", rendered under each message in the thread.
create index task_attachments_comment
    on public.task_attachments (comment_id, uploaded_at)
    where deleted_at is null and comment_id is not null;

-- One live row per stored object: a retry that re-registers the same upload
-- would double the counter and show the file twice.
create unique index task_attachments_path_unique
    on public.task_attachments (storage_path)
    where deleted_at is null;

--
-- Checklists (§11)
--
-- A checklist item is a step of somebody else's work item, not a work item of
-- its own: no status machine, no comments, never in "my tasks". When a step
-- needs its own owner it should become a sub-task instead (§11.1).
--

create table public.task_checklist_items (
    id          bigint generated by default as identity primary key,
    task_id     bigint not null references public.tasks(id) on delete restrict,
    label       text not null,
    -- Fractional ranking: inserting between 1.0 and 2.0 writes 1.5, so a drag
    -- and drop is one row update instead of renumbering the whole list.
    position    numeric not null,
    is_done     boolean not null default false,
    done_at     timestamp with time zone,
    done_by     bigint references public.sales(id),
    due_at      timestamp with time zone,
    assignee_id bigint references public.sales(id),
    created_by  bigint not null references public.sales(id),
    created_at  timestamp with time zone not null default now(),
    deleted_at  timestamp with time zone,

    constraint task_checklist_items_label_not_blank check (btrim(label) <> ''),
    -- "Done" without who and when is the exact hole this module exists to fix.
    constraint checklist_done_consistency
        check ((is_done = false and done_at is null and done_by is null)
            or (is_done = true and done_at is not null and done_by is not null))
);

create index task_checklist_items_task
    on public.task_checklist_items (task_id, position)
    where deleted_at is null;

--
-- Dependencies (§10)
--
-- Edges are directed and stored ONCE; the inverse is derived ("A blocks B"
-- means "B is blocked by A"). Storing both directions is the classic source of
-- inconsistent graphs.
--

create type public.task_dependency_kind as enum
    ('blocks', 'parent', 'related', 'duplicates');

create table public.task_dependencies (
    id             bigint generated by default as identity primary key,
    source_task_id bigint not null references public.tasks(id) on delete restrict,
    target_task_id bigint not null references public.tasks(id) on delete restrict,
    kind           public.task_dependency_kind not null,
    created_by     bigint not null references public.sales(id),
    created_at     timestamp with time zone not null default now(),
    removed_at     timestamp with time zone,
    removed_by     bigint references public.sales(id),

    constraint no_self_dependency check (source_task_id <> target_task_id)
);

create unique index task_dependencies_unique_active
    on public.task_dependencies (source_task_id, target_task_id, kind)
    where removed_at is null;

-- "What blocks me?" — walked on every completion to release dependents.
create index task_dependencies_reverse
    on public.task_dependencies (target_task_id, kind)
    where removed_at is null;

--
-- Reminders (§9)
--
-- Two tables, because a rule is edited while a delivery is a fact. Editing
-- "remind me a day before" must not rewrite the record of the ping that already
-- went out last Tuesday — that is the same append-only reasoning as
-- `task_events`, applied to notifications.
--

create type public.reminder_channel as enum
    ('in_app', 'email', 'push', 'whatsapp', 'sms', 'webhook');

create table public.task_reminders (
    id             bigint generated by default as identity primary key,
    task_id        bigint not null references public.tasks(id) on delete restrict,
    created_by     bigint not null references public.sales(id),
    created_at     timestamp with time zone not null default now(),

    -- WHEN
    schedule_kind  text not null check (schedule_kind in
                     ('absolute', 'relative_before_due', 'relative_after_due', 'recurring')),
    absolute_at    timestamp with time zone,
    -- For relative_*: 60 = one hour before (or after) the due date.
    offset_minutes integer,
    -- RFC 5545 rather than a bespoke format: it is what every calendar client
    -- already speaks, which makes iCal export in Phase 3 free (§9.2).
    rrule          text,
    timezone       text not null default 'UTC',
    until_at       timestamp with time zone,
    max_occurrences integer,

    -- WHO / HOW
    channels       public.reminder_channel[] not null default '{in_app}',
    recipients     text not null default 'owner'
                   check (recipients in ('owner', 'assignees', 'watchers', 'all', 'custom')),
    custom_recipients bigint[],
    message_template text,

    -- STATE
    is_active      boolean not null default true,
    -- Materialized for the scheduler: the dispatcher must never recompute a
    -- schedule for rows it is not going to fire.
    next_fire_at   timestamp with time zone,
    fired_count    integer not null default 0,
    stop_on_complete boolean not null default true,

    -- Each schedule kind needs exactly the field that defines it.
    constraint task_reminders_schedule_shape check (
        (schedule_kind = 'absolute' and absolute_at is not null)
        or (schedule_kind in ('relative_before_due', 'relative_after_due')
            and offset_minutes is not null and offset_minutes >= 0)
        or (schedule_kind = 'recurring' and btrim(coalesce(rrule, '')) <> '')
    ),
    constraint task_reminders_channels_not_empty
        check (array_length(channels, 1) >= 1),
    constraint task_reminders_custom_recipients check (
        recipients <> 'custom'
        or coalesce(array_length(custom_recipients, 1), 0) >= 1
    )
);

-- The scheduler's ONLY query. Partial, so it stays the size of the pending
-- work rather than the size of the reminder history.
create index task_reminders_due
    on public.task_reminders (next_fire_at)
    where is_active and next_fire_at is not null;

create index task_reminders_task
    on public.task_reminders (task_id)
    where is_active;

--
-- The outbox. One row per delivery attempt per recipient per channel, so a
-- reminder that was never delivered is visible AS SUCH (O6) instead of being
-- indistinguishable from one nobody acted on.
--
create table public.task_notifications (
    id            bigint generated by default as identity primary key,
    reminder_id   bigint references public.task_reminders(id),
    task_id       bigint not null references public.tasks(id) on delete restrict,
    recipient_id  bigint not null references public.sales(id),
    channel       public.reminder_channel not null,
    scheduled_for timestamp with time zone not null,
    sent_at       timestamp with time zone,
    delivered_at  timestamp with time zone,
    read_at       timestamp with time zone,
    acknowledged_at timestamp with time zone,
    title         text,
    body          text,
    status        text not null default 'queued'
                  check (status in ('queued', 'sending', 'sent', 'delivered',
                                    'failed', 'bounced', 'skipped', 'canceled')),
    attempt       smallint not null default 0,
    error         text,
    provider_message_id text,
    -- Idempotency: `reminder:occurrence:recipient:channel`. A replayed
    -- dispatch is a no-op instead of a second ping.
    dedupe_key    text unique,
    created_at    timestamp with time zone not null default now()
);

-- The worker's claim query.
create index task_notifications_outbox
    on public.task_notifications (status, scheduled_for)
    where status in ('queued', 'sending');

-- "My unread in-app notifications" — the bell badge, on every page load.
create index task_notifications_inbox
    on public.task_notifications (recipient_id, created_at desc)
    where channel = 'in_app' and read_at is null;

create index task_notifications_task
    on public.task_notifications (task_id, created_at desc);

--
-- Anti-fatigue preferences for reminders (§9.5)
--
-- "A reminder system without throttling is uninstalled within a week." One row
-- per user; absent means the defaults, so nobody needs backfilling.
--
create table public.notification_preferences (
    id          bigint generated by default as identity primary key,
    sales_id    bigint not null unique references public.sales(id) on delete cascade,

    -- Quiet hours are expressed in the user's own timezone; storing them as
    -- `time` plus a zone is what makes "no pings before 08:00" mean the same
    -- thing in Bogota and in Madrid.
    timezone    text not null default 'UTC',
    quiet_hours_start time,
    quiet_hours_end   time,

    -- Digest: one message at a fixed hour instead of N pings through the day.
    digest_mode boolean not null default false,
    digest_at   time not null default '08:00',

    -- Per-channel opt-out. Per-EVENT-TYPE preferences are deliberately not
    -- modelled yet: every row in the outbox comes from a reminder today, so a
    -- second axis would have exactly one value to key on (YAGNI). Add it when
    -- automations start writing notifications (Phase 3).
    muted_channels public.reminder_channel[] not null default '{}',

    -- Hard ceiling on deliveries per rolling hour, enforced at claim time.
    max_per_hour integer not null default 20 check (max_per_hour > 0),

    -- "Same task, several rules fired" collapses inside this window.
    dedupe_window_minutes integer not null default 60
        check (dedupe_window_minutes >= 0),

    created_at  timestamp with time zone not null default now(),
    updated_at  timestamp with time zone not null default now()
);

create index notification_preferences_sales_id_idx
    on public.notification_preferences (sales_id);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.leads
    add constraint leads_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.leads
    add constraint leads_company_id_fkey foreign key (company_id) references public.companies(id) on delete set null;

-- The conversion pointers are provenance, not ownership: if the record they
-- produced is later deleted the lead stays, with the pointer cleared.
alter table public.leads
    add constraint leads_converted_contact_id_fkey foreign key (converted_contact_id) references public.contacts(id) on delete set null;

alter table public.leads
    add constraint leads_converted_company_id_fkey foreign key (converted_company_id) references public.companies(id) on delete set null;

alter table public.leads
    add constraint leads_converted_deal_id_fkey foreign key (converted_deal_id) references public.deals(id) on delete set null;

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

-- W8 fix: the cascade is gone. Deleting a parent closes `task_links`
-- (`unlinked_at`) and emits an event instead of cascading a delete; the
-- legacy `tasks.contact_id` shim is kept nullable and read-only.
alter table public.tasks
    add constraint tasks_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.tasks
    add constraint tasks_owner_sales_id_fkey foreign key (owner_sales_id) references public.sales(id);

alter table public.tasks
    add constraint tasks_created_by_fkey foreign key (created_by) references public.sales(id);

alter table public.tasks
    add constraint tasks_completed_by_fkey foreign key (completed_by) references public.sales(id);

alter table public.tasks
    add constraint tasks_deleted_by_fkey foreign key (deleted_by) references public.sales(id);

alter table public.tasks
    add constraint tasks_task_type_id_fkey foreign key (task_type_id) references public.task_types(id);

alter table public.tasks
    add constraint tasks_status_id_fkey foreign key (status_id) references public.task_statuses(id);

alter table public.tasks
    add constraint tasks_priority_id_fkey foreign key (priority_id) references public.task_priorities(id);

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);

--
-- Ownership indexes
--
-- Every owner-scoped RLS policy filters on `sales_id`, and so do the
-- "only mine" list filters. Without these the policies degrade to a sequential
-- scan on every list query.
--
create index companies_sales_id_idx on public.companies using btree (sales_id);
create index contacts_sales_id_idx on public.contacts using btree (sales_id);
create index deals_sales_id_idx on public.deals using btree (sales_id);
create index contact_notes_sales_id_idx on public.contact_notes using btree (sales_id);
create index deal_notes_sales_id_idx on public.deal_notes using btree (sales_id);

-- tasks.contact_id had no index at all: it now carries both the contact detail
-- page lookup and the legacy RLS path. This is by far the most scanned index
-- in the schema.
create index tasks_contact_id_idx on public.tasks using btree (contact_id);
-- The task list filters by owner and orders by due date.
create index tasks_sales_id_due_date_idx on public.tasks using btree (sales_id, due_date);

--
-- List ordering indexes
--
-- Every one of these backs an `order by ... limit n` that would otherwise
-- top-N heapsort the whole table on each page load. Partial where the list is
-- always filtered the same way.
--
create index contacts_last_seen_idx on public.contacts using btree (last_seen desc);
create index contact_notes_date_idx on public.contact_notes using btree (date desc);
create index deal_notes_date_idx on public.deal_notes using btree (date desc);
-- Backs `contacts_summary.nb_tasks` (open, non-deleted tasks only).
create index tasks_pending_contact_id_idx on public.tasks using btree (contact_id) where done_date is null and deleted_at is null;
-- Backs the "tasks due" lists, which never show completed tasks.
create index tasks_pending_due_date_idx on public.tasks using btree (due_date) where done_date is null;
-- Backs the deal kanban, which only ever lists non-archived deals.
create index deals_active_index_idx on public.deals using btree (index desc) where archived_at is null;

-- Task-module query indexes (§18.3).
-- "My open tasks by due date" — the single hottest query in the product.
create index tasks_owner_open_due
    on public.tasks (owner_sales_id, due_date)
    where deleted_at is null and completed_at is null and canceled_at is null;
-- Overdue triage (manager inbox).
create index tasks_overdue
    on public.tasks (due_date)
    where deleted_at is null and completed_at is null and canceled_at is null;
-- "Everything this person owns", whatever state it is in -- the access path
-- `team_workload_summary` needs. Every other owner index is PARTIAL (open, or
-- completed), so a query that counts open AND completed in one pass matches
-- none of them: without this the planner fell back to a full scan of `tasks`
-- once per member, measured at 1.7 s for 40 reps over 200k tasks against 215 ms
-- with it.
create index tasks_owner_all
    on public.tasks (owner_sales_id)
    where deleted_at is null;
-- Completed work per owner -- the team dashboards' `nb_tasks_completed`
-- counters and the `team_task_stats` cube, both of which ask "what did this
-- person close inside the period". None of the indexes above can serve it: they
-- are all partial ON completed_at BEING NULL, which is the exact complement of
-- this query.
create index tasks_owner_completed
    on public.tasks (owner_sales_id, completed_at)
    where completed_at is not null and deleted_at is null;
-- Status boards / Kanban.
create index tasks_status_due on public.tasks (status_id, due_date)
    where deleted_at is null;
-- Full-text search.
create index tasks_search on public.tasks using gin (search_tsv);

-- Leads: owner scoping (RLS + "only mine"), the default list ordering, and the
-- conversion pointers used by the contact/company/deal detail pages.
create index leads_sales_id_idx on public.leads using btree (sales_id);
create index leads_created_at_idx on public.leads using btree (created_at desc);
create index leads_company_id_idx on public.leads using btree (company_id);
create index leads_converted_contact_id_idx on public.leads using btree (converted_contact_id);
