# -*- coding: utf-8 -*-
"""Crop the supplied Plataforma artwork into the assets the application uses.

Two source files are supplied by the brand owner and are never edited:

  plataforma_software_dark.svg   760x206  outlined icon + BLACK text
  plataforma_software_light.svg  792x612  filled icon   + WHITE text

Note the names are the opposite way round from this repository's convention.
Here `_light` / `_dark` has always meant *the mode the asset is for*
(`logo_atomic_crm_dark.svg` is filled white, because it is the dark-MODE logo).
The sources are named after the colour of the ink instead. The mapping below is
by legibility, not by filename: black ink goes to the light-mode asset.

The script only ever adds a `viewBox` and drops the fixed `width`/`height`.
It changes no path, no colour and no proportion:

  * the sources carry a lot of empty canvas -- the dark-mode one is 612 units
    tall around 178 units of ink, so at `height: 24px` roughly seven of those
    pixels would be logo and the rest air;
  * dropping `width`/`height` lets one asset serve a 20px footer mark and a
    44px login lockup without a second export.

It also cuts an icon-only square out of each, because the lockup is 4:1 and
illegible in the collapsed sidebar rail. That is a crop of supplied artwork,
not a redrawing.

All four boxes were measured in a real renderer (`getBoundingClientRect` against
the root SVG), not eyeballed. Re-run after replacing a source file.

Usage: python scripts/compose-plataforma-logo.py
"""

import re

DIR = "src/components/atomic-crm/root/logos/"

# source file, ink box, icon box -- measured, in the file's own user units.
# `text_fill` is the colour of the lettering, which is what tells the icon crop
# which paths to drop: cropping with a viewBox alone leaves every letter in the
# file, merely outside the visible area, and the icon asset then weighs as much
# as the full lockup for artwork nobody can see.
SOURCES = {
    "light": {
        "file": "plataforma_software_dark.svg",
        "ink": (28.4, 11.3, 708.7, 184.8),
        "icon": (28.4, 11.3, 151.0, 184.8),
        "text_fill": "#000000",
    },
    "dark": {
        "file": "plataforma_software_light.svg",
        "ink": (34.5, 225.7, 717.6, 178.4),
        "icon": (34.5, 225.7, 143.8, 178.4),
        "text_fill": "#ffffff",
    },
}

# Breathing room so the mark never touches the edge of its container.
LOCKUP_PAD = 8
ICON_PAD = 12

HEADER = '<?xml version="1.0" encoding="UTF-8"?>\n'
# No double hyphen anywhere in here: `--` is not legal inside an XML comment,
# and a browser drops the whole file rather than reporting it.
NOTE = (
    "<!-- Generated by scripts/compose-plataforma-logo.py from %s.\n"
    "     Cropped only: no path, colour or proportion is altered.\n"
    "     Do not hand-edit; re-run the script instead. -->\n"
)


def body(path):
    """Everything inside the root <svg>, verbatim."""
    svg = open(path, encoding="utf-8").read()
    inner = re.search(r"<svg[^>]*>(.*)</svg>\s*$", svg, re.S)
    assert inner, "no root <svg> in %s" % path
    return inner.group(1).strip()


def write(name, source_file, view_box, content):
    x, y, w, h = view_box
    svg = (
        HEADER
        + NOTE % source_file
        + '<svg xmlns="http://www.w3.org/2000/svg" '
        + 'viewBox="%g %g %g %g">\n' % (x, y, w, h)
        + content
        + "\n</svg>\n"
    )
    open(DIR + name, "w", encoding="utf-8", newline="\n").write(svg)
    print("written %s%s  viewBox=%g %g %g %g" % ((DIR, name) + view_box))


for mode, spec in SOURCES.items():
    content = body(DIR + spec["file"])

    x, y, w, h = spec["ink"]
    write(
        "logo_plataforma_%s.svg" % mode,
        spec["file"],
        (x - LOCKUP_PAD, y - LOCKUP_PAD, w + LOCKUP_PAD * 2, h + LOCKUP_PAD * 2),
        content,
    )

    # A square around the icon, so it drops into an avatar-shaped slot without
    # the container having to know the mark's proportions.
    ix, iy, iw, ih = spec["icon"]
    side = max(iw, ih) + ICON_PAD * 2
    write(
        "logo_plataforma_icon_%s.svg" % mode,
        spec["file"],
        (ix - (side - iw) / 2, iy - (side - ih) / 2, side, side),
        content,
    )
