--
-- Task module — Phase 1, step 3: assignment and polymorphic links.
--
-- Implements proposal §3.3 (task_assignments, task_links) + Appendix C step 4
-- (backfill from the legacy columns).
--
--   - `task_assignments`: who is attached to a task and in what role, with
--     `assigned_at` / `unassigned_at` / `assigned_by`. Rows are CLOSED, never
--     deleted — reassignment history is business-critical (§7.4).
--   - `task_links`: polymorphic N:N to contacts / leads / companies / deals,
--     with exactly one active `is_primary` link (§14.2). This replaces the
--     `contact_id not null` column (W1).
--

-- ---------------------------------------------------------------------------
-- teams (minimal) — `task_assignments.team_id` and the §7.3 access rule need
-- a team concept. Full team management (membership admin, digests) is Phase 2
-- (2.4); this is just the table the FK and the RLS predicate reference.
-- ---------------------------------------------------------------------------

create table public.teams (
    id          bigint generated by default as identity primary key,
    name        text not null,
    description text,
    created_at  timestamp with time zone not null default now()
);

create table public.team_members (
    id        bigint generated by default as identity primary key,
    team_id   bigint not null references public.teams(id) on delete cascade,
    sales_id  bigint not null references public.sales(id) on delete cascade,
    created_at timestamp with time zone not null default now(),
    unique (team_id, sales_id)
);

-- ---------------------------------------------------------------------------
-- task_assignments
-- ---------------------------------------------------------------------------

create table public.task_assignments (
    id            bigint generated by default as identity primary key,
    task_id       bigint not null references public.tasks(id) on delete restrict,
    sales_id      bigint references public.sales(id),
    team_id       bigint references public.teams(id),
    role          public.task_role not null,
    assigned_at   timestamp with time zone not null default now(),
    assigned_by   bigint not null references public.sales(id),
    unassigned_at timestamp with time zone,     -- closed, never deleted
    unassigned_by bigint references public.sales(id),
    reason        text,

    constraint task_assignments_subject
        check (num_nonnulls(sales_id, team_id) = 1)
);

-- Exactly one active owner at a time.
create unique index task_assignments_single_owner
    on public.task_assignments (task_id)
    where role = 'owner' and unassigned_at is null;

-- "My work" — the single most frequent query in the product.
create index task_assignments_active_by_sale
    on public.task_assignments (sales_id, role)
    where unassigned_at is null;

-- ---------------------------------------------------------------------------
-- task_links
-- ---------------------------------------------------------------------------

create table public.task_links (
    id          bigint generated by default as identity primary key,
    task_id     bigint not null references public.tasks(id) on delete restrict,
    entity_type public.task_entity not null,
    entity_id   bigint not null,
    is_primary  boolean not null default false,
    linked_at   timestamp with time zone not null default now(),
    linked_by   bigint not null references public.sales(id),
    unlinked_at timestamp with time zone,
    -- Denormalized snapshot so the timeline can still say "vinculada a Acme"
    -- after the record is gone (§14.3).
    entity_label text
);

create unique index task_links_unique_active
    on public.task_links (task_id, entity_type, entity_id)
    where unlinked_at is null;

create unique index task_links_single_primary
    on public.task_links (task_id)
    where is_primary and unlinked_at is null;

-- The reverse lookup: "tasks on this deal". Leading columns are the filter.
create index task_links_entity
    on public.task_links (entity_type, entity_id, task_id)
    where unlinked_at is null;

-- ---------------------------------------------------------------------------
-- Appendix C step 4 — backfill links and assignments from the old columns.
-- ---------------------------------------------------------------------------

-- Primary contact link from the legacy `contact_id`.
insert into public.task_links (task_id, entity_type, entity_id, is_primary, linked_by, entity_label)
select t.id, 'contact', t.contact_id, true, coalesce(t.owner_sales_id, t.created_by),
       nullif(btrim(concat_ws(' ', c.first_name, c.last_name)), '')
from public.tasks t
    left join public.contacts c on c.id = t.contact_id
where t.contact_id is not null;

-- Owner assignment from the legacy `sales_id`/`owner_sales_id`.
insert into public.task_assignments (task_id, sales_id, role, assigned_by, assigned_at)
select id, owner_sales_id, 'owner', created_by, created_at
from public.tasks
where owner_sales_id is not null;

-- ---------------------------------------------------------------------------
-- RLS and grants
-- ---------------------------------------------------------------------------

--
-- Access rule (§7.3): "A task is visible to you if any of these is true:
--   1. you are the owner, a collaborator or a watcher (active assignment), or
--   2. you are a member of an assigned team, or
--   3. you are the creator, or
--   4. you own a linked record (contact/lead/company/deal), or
--   5. can_manage_all() — admin or manager."
--
-- The `tasks` RLS policy inlines these `exists` clauses (so the planner can
-- drive them off `task_assignments_active_by_sale` / `task_links_entity` as
-- semi-joins, per the proposal's performance note). `can_see_task()` is kept
-- for edge functions, tests and the child tables' policies, which are always
-- joined back to a known task_id.
--

create or replace function public.can_see_task(p_task_id bigint) returns boolean
    language sql stable security definer set search_path to ''
    as $$
    select (select public.can_manage_all())
        or exists (select 1 from public.task_assignments a
                    where a.task_id = p_task_id and a.unassigned_at is null
                      and (a.sales_id = (select public.current_sale_id())
                           or a.team_id in (select team_id from public.team_members
                                             where sales_id = (select public.current_sale_id()))))
        or exists (select 1 from public.tasks t
                    where t.id = p_task_id and t.created_by = (select public.current_sale_id())
                      and t.deleted_at is null)
        or exists (select 1 from public.task_links l
                    where l.task_id = p_task_id and l.unlinked_at is null
                      and ((l.entity_type = 'contact'
                            and exists (select 1 from public.contacts c
                                        where c.id = l.entity_id
                                          and c.sales_id = (select public.current_sale_id())))
                           or (l.entity_type = 'lead'
                               and exists (select 1 from public.leads ld
                                           where ld.id = l.entity_id
                                             and ld.sales_id = (select public.current_sale_id())))
                           or (l.entity_type = 'company'
                               and exists (select 1 from public.companies co
                                           where co.id = l.entity_id
                                             and co.sales_id = (select public.current_sale_id())))
                           or (l.entity_type = 'deal'
                               and exists (select 1 from public.deals d
                                           where d.id = l.entity_id
                                             and d.sales_id = (select public.current_sale_id())))));
$$;

grant all on function public.can_see_task(bigint) to authenticated;
grant all on function public.can_see_task(bigint) to service_role;

-- Assignments are visible to whoever can see the task; the exact predicate is
-- inlined against `public.can_see_task()` (defined with the RLS rewrite in a
-- later migration). Writes require the same access as the task itself.
alter table public.task_assignments enable row level security;
alter table public.task_links enable row level security;

create policy "Assignments follow their task for reads"
    on public.task_assignments for select to authenticated
    using (public.can_see_task(task_id));

create policy "Assignments follow their task for writes"
    on public.task_assignments for insert to authenticated
    with check (public.can_see_task(task_id));

create policy "Assignments follow their task for updates"
    on public.task_assignments for update to authenticated
    using (public.can_see_task(task_id))
    with check (public.can_see_task(task_id));

create policy "Links follow their task for reads"
    on public.task_links for select to authenticated
    using (public.can_see_task(task_id));

create policy "Links follow their task for writes"
    on public.task_links for insert to authenticated
    with check (public.can_see_task(task_id));

create policy "Links follow their task for updates"
    on public.task_links for update to authenticated
    using (public.can_see_task(task_id))
    with check (public.can_see_task(task_id));

-- The frontend soft-unlinks instead of deleting (unlinked_at), so no DELETE
-- policy is granted to authenticated users.
grant select, insert, update on table public.task_assignments to authenticated;
grant select, insert, update on table public.task_links to authenticated;
grant all on table public.task_assignments to service_role;
grant all on table public.task_links to service_role;

grant usage, select on sequence public.task_assignments_id_seq to authenticated;
grant usage, select on sequence public.task_links_id_seq to authenticated;

-- Teams are read-only reference data for now (management UI ships in Phase 2).
alter table public.teams enable row level security;
alter table public.team_members enable row level security;

create policy "Teams are readable by every authenticated user"
    on public.teams for select to authenticated using (true);
create policy "Team memberships are readable by every authenticated user"
    on public.team_members for select to authenticated using (true);

grant select on table public.teams to authenticated;
grant select on table public.team_members to authenticated;
grant all on table public.teams to service_role;
grant all on table public.team_members to service_role;
