-- Customer portal slides and templates (docs/proposals/quote-portal-presentation.md §7).
--
-- Replaces the portal builder (brand kit, experiences, versions), which never
-- left this machine: admins keep portal TEMPLATES of free-form slides, one of
-- them active; the active one is frozen into `quote_versions.slides` at issue
-- and served to the customer by `quote_portal_document()`. The template the
-- portal always had ships as "Predeterminada", active and locked.
--
-- Hand-written from the sections appended to supabase/schemas/0{1,2,4,5,6,7}_*.sql
-- (`db diff` output is drowned in the known anon-grant drift).

--
-- Customer portal slides (docs/proposals/quote-portal-presentation.md §7)
--
-- The slides a customer reads before the quotation, grouped in TEMPLATES:
-- admins keep as many as they like, and exactly one is active -- the one every
-- quotation issued from then on shows, frozen into `quote_versions.slides` so
-- an open link never changes under the customer.
--
-- `is_system` marks the template the build ships (the presentation the portal
-- always had). It is never edited or deleted, so there is always one to go
-- back to; "save as" copies it into one that can be changed.
create table public.portal_templates (
    id          bigint generated by default as identity primary key,
    name        text not null check (char_length(btrim(name)) between 1 and 80),
    is_active   boolean not null default false,
    is_system   boolean not null default false,
    created_at  timestamp with time zone not null default now(),
    updated_at  timestamp with time zone not null default now()
);

-- At most one active template: "the one every quotation shows" must be one.
create unique index portal_templates_one_active
    on public.portal_templates (is_active) where is_active;
--
-- A slide is a free canvas: `elements` is an ordered list (first = bottom) of
-- boxes -- an image, a video or a text -- each placed with `x`, `y`, `w`, `h`
-- in percent of a 16:9 stage. The shape is checked by `portal_slides_guard()`
-- (a check constraint cannot call a function declared in a later file).
create table public.portal_slides (
    id          bigint generated by default as identity primary key,
    template_id bigint not null
        references public.portal_templates(id) on delete cascade,
    position    integer not null default 0,
    elements    jsonb not null default '[]'::jsonb,
    created_at  timestamp with time zone not null default now(),
    updated_at  timestamp with time zone not null default now()
);

create index portal_slides_template_position
    on public.portal_slides (template_id, position);

alter table public.quote_versions add column slides jsonb;
alter table public.quote_versions add column standard_presentation boolean not null default false;

-- One box of a slide. Everything a customer's browser will render is checked
-- here, keys included, because the snapshot reaches anybody holding a link.
-- Media paths are `slides/<uuid>.<ext>` in the public `portal-media` bucket:
-- the original file name never reaches the path, and there is no SVG (a
-- document that can carry script, on a public bucket). `builtin/<name>.webp`
-- names one of the pictures bundled with the app, which the default template
-- uses -- a closed list, resolved by the browser, never a URL.
create or replace function public.portal_slide_element_is_valid(p_element jsonb)
    returns boolean
    language plpgsql immutable
    set search_path to ''
as $$
declare
    v_key     text;
    v_pattern text;
begin
    if jsonb_typeof(p_element) is distinct from 'object' then
        return false;
    end if;
    if (p_element - array['id', 'kind', 'x', 'y', 'w', 'h', 'path', 'alt',
                          'text', 'size', 'align', 'color']) <> '{}'::jsonb then
        return false;
    end if;
    if coalesce(p_element ->> 'id', '') !~ '^[A-Za-z0-9_-]+$'
       or char_length(p_element ->> 'id') > 40 then
        return false;
    end if;
    foreach v_key in array array['x', 'y', 'w', 'h'] loop
        if jsonb_typeof(p_element -> v_key) is distinct from 'number' then
            return false;
        end if;
    end loop;
    if (p_element ->> 'x')::numeric not between 0 and 100
       or (p_element ->> 'y')::numeric not between 0 and 100
       or (p_element ->> 'w')::numeric not between 1 and 100
       or (p_element ->> 'h')::numeric not between 1 and 100 then
        return false;
    end if;

    if p_element ->> 'kind' = 'text' then
        return jsonb_typeof(p_element -> 'text') = 'string'
           and char_length(p_element ->> 'text') <= 2000
           and p_element ->> 'size' in ('sm', 'md', 'lg', 'xl')
           and p_element ->> 'align' in ('left', 'center', 'right')
           and p_element ->> 'color' in ('light', 'dark')
           and not (p_element ?| array['path', 'alt']);
    end if;
    if p_element ->> 'kind' in ('image', 'video') then
        -- The extension list follows the kind; a variable rather than an
        -- inline CASE, which the migration runner's splitter mis-cuts.
        v_pattern := '^(slides/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(webp|jpg|png|gif|avif)|builtin/(cover|company|purpose|certifications)\.webp)$';
        if p_element ->> 'kind' = 'video' then
            v_pattern := '^slides/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(mp4|webm)$';
        end if;
        return coalesce(p_element ->> 'path', '') ~ v_pattern
           and (not p_element ? 'alt'
                or (jsonb_typeof(p_element -> 'alt') = 'string'
                    and char_length(p_element ->> 'alt') <= 200))
           and not (p_element ?| array['text', 'size', 'align', 'color']);
    end if;
    return false;
end;
$$;

-- Whether a template is the one the build ships, which nobody changes. The
-- migration that seeds it opens `app.portal_template_seed` for the purpose.
create or replace function public.portal_template_is_locked(p_template_id bigint)
    returns boolean
    language sql stable
    set search_path to ''
as $$
    select coalesce(current_setting('app.portal_template_seed', true), '') <> 'on'
       and exists (select 1 from public.portal_templates t
                    where t.id = p_template_id and t.is_system);
$$;

-- A template's limits, the box shape, and the default template's lock. Raised
-- with a key rather than failing a constraint, so the editor can say what went
-- wrong.
create or replace function public.portal_slides_guard() returns trigger
    language plpgsql
    set search_path to ''
as $$
declare
    v_element jsonb;
begin
    if (tg_op <> 'INSERT' and public.portal_template_is_locked(old.template_id))
       or (tg_op <> 'DELETE' and public.portal_template_is_locked(new.template_id)) then
        raise exception 'the default template cannot be changed; save a copy instead'
            using errcode = 'check_violation', detail = 'portal_template_locked';
    end if;
    if tg_op = 'DELETE' then
        return old;
    end if;

    if tg_op = 'INSERT'
       and (select count(*) from public.portal_slides s
             where s.template_id = new.template_id) >= 30 then
        raise exception 'a template holds at most 30 slides'
            using errcode = 'check_violation', detail = 'portal_slide_limit';
    end if;

    if jsonb_typeof(new.elements) is distinct from 'array'
       or jsonb_array_length(new.elements) > 20 then
        raise exception 'a slide holds at most 20 boxes'
            using errcode = 'check_violation', detail = 'portal_slide_elements_invalid';
    end if;
    for v_element in select value from jsonb_array_elements(new.elements) loop
        if not public.portal_slide_element_is_valid(v_element) then
            raise exception 'invalid slide box: %', v_element
                using errcode = 'check_violation', detail = 'portal_slide_elements_invalid';
        end if;
    end loop;

    new.updated_at := now();
    return new;
end;
$$;

-- The default template: renamed, edited or deleted by nobody. The only thing
-- anybody may change on it is whether it is the active one.
create or replace function public.portal_templates_guard() returns trigger
    language plpgsql
    set search_path to ''
as $$
begin
    if coalesce(current_setting('app.portal_template_seed', true), '') = 'on' then
        if tg_op = 'DELETE' then return old; else return new; end if;
    end if;
    if tg_op = 'INSERT' and new.is_system then
        raise exception 'only the build ships a default template'
            using errcode = 'check_violation', detail = 'portal_template_locked';
    end if;
    if tg_op = 'DELETE' and old.is_system then
        raise exception 'the default template cannot be deleted'
            using errcode = 'check_violation', detail = 'portal_template_locked';
    end if;
    if tg_op = 'UPDATE'
       and (old.is_system or new.is_system)
       and (to_jsonb(old) - array['is_active', 'updated_at'])
           is distinct from (to_jsonb(new) - array['is_active', 'updated_at']) then
        raise exception 'the default template cannot be changed; save a copy instead'
            using errcode = 'check_violation', detail = 'portal_template_locked';
    end if;
    if tg_op = 'DELETE' then
        return old;
    end if;
    new.updated_at := now();
    return new;
end;
$$;

-- Makes one template the one every quotation issued from now on shows. One
-- statement per row, the old one first, so the one-active index never sees
-- two; security invoker, so the admin-only update policy is the gate.
create or replace function public.activate_portal_template(p_template_id bigint)
    returns void
    language plpgsql
    set search_path to ''
as $$
begin
    if not public.is_admin() then
        raise exception 'only admins choose the active template'
            using errcode = 'insufficient_privilege';
    end if;
    update public.portal_templates set is_active = false
     where is_active and id <> p_template_id;
    update public.portal_templates set is_active = true
     where id = p_template_id;
    if not found then
        raise exception 'portal template % does not exist', p_template_id
            using errcode = 'no_data_found', detail = 'portal_template_missing';
    end if;
end;
$$;

-- "Save as": a new template with a copy of every slide of another one. The
-- copy is never active and never the default; security invoker, so only an
-- admin's insert passes.
create or replace function public.duplicate_portal_template(p_template_id bigint, p_name text)
    returns bigint
    language plpgsql
    set search_path to ''
as $$
declare
    v_id bigint;
begin
    if not exists (select 1 from public.portal_templates where id = p_template_id) then
        raise exception 'portal template % does not exist', p_template_id
            using errcode = 'no_data_found', detail = 'portal_template_missing';
    end if;
    insert into public.portal_templates (name) values (btrim(p_name))
    returning id into v_id;
    insert into public.portal_slides (template_id, position, elements)
    select v_id, s.position, s.elements
      from public.portal_slides s
     where s.template_id = p_template_id
     order by s.position, s.id;
    return v_id;
end;
$$;

-- What `issue_quote_version()` freezes: the ACTIVE template's slides as they
-- stand, in order. The default template contributes none -- the page draws its
-- designed presentation from `standard_presentation` -- and with no active
-- template there are none either: the plain cover.
create or replace function public.portal_slides_snapshot()
    returns jsonb
    language sql stable
    set search_path to ''
as $$
    select coalesce(jsonb_agg(jsonb_build_object('elements', s.elements)
                              order by s.position, s.id), '[]'::jsonb)
      from public.portal_slides s
      join public.portal_templates t on t.id = s.template_id
     where t.is_active and not t.is_system;
$$;

--
-- The pipeline follows its quotations
--

create or replace function public.issue_quote_version(
    p_quote_id        bigint,
    p_token_days      integer default 30,
    p_token_label     text    default null,
    p_override_reason text    default null,
    p_reason          text    default null
) returns jsonb
    language plpgsql security definer
    set search_path to ''
as $$
declare
    v_quote    public.quotes;
    v_actor    bigint := public.current_sale_id();
    v_version  public.quote_versions;
    v_prev     public.quote_versions;
    v_gate     jsonb;
    v_override text := nullif(btrim(coalesce(p_override_reason, '')), '');
    v_reason   text := nullif(btrim(coalesce(p_reason, '')), '');
    v_link     jsonb;
begin
    select * into v_quote from public.quotes where id = p_quote_id for update;
    if not found then
        raise exception 'quote % not found', p_quote_id
            using errcode = 'no_data_found';
    end if;

    -- Same rule as the quotes UPDATE policy. Restated because SECURITY DEFINER
    -- bypasses RLS.
    if not (select public.can_manage_all())
       and v_quote.sales_id is distinct from v_actor then
        raise exception 'no permission to issue quote %', p_quote_id
            using errcode = 'insufficient_privilege';
    end if;

    select * into v_version
      from public.quote_versions v
     where v.quote_id = p_quote_id and v.issued_at is null
     for update;
    if not found then
        raise exception 'quote % has no editable draft to issue', p_quote_id
            using errcode = 'no_data_found', detail = 'quote_no_draft';
    end if;

    -- An empty document is not a quotation. Caught here rather than by the
    -- customer.
    if not exists (select 1 from public.quote_lines l
                    where l.version_id = v_version.id) then
        raise exception 'quote % has no lines to issue', p_quote_id
            using errcode = 'check_violation', detail = 'quote_empty';
    end if;

    -- An offer that has already lapsed cannot be sent. `mint_quote_token()`
    -- clamps a link to the day after `valid_until`, so issuing this draft would
    -- hand the customer a link that is dead on arrival -- exactly the case
    -- `create_quote_link()` already refuses with the same key. The two paths
    -- mint the same token and now refuse on the same condition (§13.6 #12).
    if v_version.valid_until < current_date then
        raise exception 'the offer in quote % expired on %', p_quote_id, v_version.valid_until
            using errcode = 'check_violation', detail = 'quote_validity_elapsed';
    end if;

    -- Evaluated inside the row lock taken above, so two concurrent issues
    -- cannot both pass the gate on the strength of the same state.
    v_gate := public.quote_discount_gate(p_quote_id);

    if not (v_gate->>'ok')::boolean then
        -- Only an admin overrides, and only in writing. A manager may issue
        -- anybody's quote, but not past the rule.
        if v_override is null
           or (select public.current_sales_role())
              is distinct from 'admin'::public.sales_role then
            raise exception 'quote % grants % percent discount, above the % percent allowed for %',
                    p_quote_id,
                    v_gate->>'effective_discount_percent',
                    v_gate->>'max_allowed',
                    v_gate->>'role'
                using errcode = 'check_violation',
                      detail  = 'quote_discount_exceeds_limit',
                      hint    = v_gate::text;
        end if;
    else
        -- The gate was satisfied, so nothing was overridden. Recording a motive
        -- here would put a skipped-the-rule marker on an issue that met it.
        v_override := null;

        if (v_gate->>'reason_required')::boolean and v_reason is null then
            raise exception 'quote % grants % percent discount, above the % percent that needs a written reason',
                    p_quote_id,
                    v_gate->>'effective_discount_percent',
                    v_gate->>'requires_reason_above'
                using errcode = 'check_violation',
                      detail  = 'quote_discount_reason_required',
                      hint    = v_gate::text;
        end if;
    end if;

    -- The previous document stops being current. One row at a time, with the
    -- GUC carrying its id, because the unfreeze hole is per version.
    for v_prev in
        select * from public.quote_versions v
         where v.quote_id = p_quote_id
           and v.issued_at is not null
           and v.superseded_at is null
    loop
        perform set_config('app.quote_version_unfreeze', v_prev.id::text, true);
        update public.quote_versions set superseded_at = now() where id = v_prev.id;
        perform set_config('app.quote_version_unfreeze', '', true);
    end loop;

    -- Recomputed rather than trusted: the totals are about to be frozen, and
    -- the figure a customer signs must be the one the lines add up to.
    perform public.refresh_quote_version_totals(v_version.id);

    -- Still a draft at this point, so the freeze guard lets it through once
    -- this function identifies itself as the owner of the stamped columns. From
    -- the next statement on, this row is immutable.
    perform set_config('app.quote_version_system_write', v_version.id::text, true);

    -- `valid_until` and `terms` are left alone: the draft already carries the
    -- document's own, and the header mirrors them (`quote_versions_sync_header`).
    update public.quote_versions v
       set issued_at      = now(),
           issued_by      = v_actor,
           party_snapshot = public.quote_party_snapshot(p_quote_id),
           slides         = public.portal_slides_snapshot(),
           standard_presentation = coalesce((select t.is_system
                                               from public.portal_templates t
                                              where t.is_active), false)
     where v.id = v_version.id
    returning * into v_version;

    perform set_config('app.quote_version_system_write', '', true);

    v_link := public.mint_quote_token(v_version.id, p_token_days, p_token_label);

    perform public.apply_quote_status(
        p_quote_id, 'sent', v_reason, 'internal', v_actor, null, v_override);

    return jsonb_build_object(
        'quote_id',       p_quote_id,
        'version_id',     v_version.id,
        'version_number', v_version.version_number) || v_link;
end;
$$;

create or replace function public.quote_portal_document(p_version_id bigint)
returns jsonb
    language sql stable security definer
    set search_path to ''
as $$
    select doc.body || jsonb_build_object(
               'etag', encode(sha256(convert_to(doc.body::text, 'UTF8')), 'hex'))
      from (
    select jsonb_build_object(
        'quote', jsonb_build_object(
            'number',         q.quote_number,
            'title',          q.title,
            'status',         q.status_key,
            'currency',       v.currency,
            'version_number', v.version_number,
            'issued_at',      v.issued_at,
            'valid_until',    v.valid_until,
            'is_superseded',  v.superseded_at is not null),
        'parties', jsonb_build_object(
            'company', case when jsonb_typeof(v.party_snapshot -> 'company') = 'object'
                then jsonb_build_object(
                    'name',           v.party_snapshot -> 'company' -> 'name',
                    'address',        v.party_snapshot -> 'company' -> 'address',
                    'zipcode',        v.party_snapshot -> 'company' -> 'zipcode',
                    'city',           v.party_snapshot -> 'company' -> 'city',
                    'state_abbr',     v.party_snapshot -> 'company' -> 'state_abbr',
                    'country',        v.party_snapshot -> 'company' -> 'country',
                    'tax_identifier', v.party_snapshot -> 'company' -> 'tax_identifier',
                    'phone_number',   v.party_snapshot -> 'company' -> 'phone_number',
                    'website',        v.party_snapshot -> 'company' -> 'website')
                end,
            'contact', case when jsonb_typeof(v.party_snapshot -> 'contact') = 'object'
                then jsonb_build_object(
                    'first_name', v.party_snapshot -> 'contact' -> 'first_name',
                    'last_name',  v.party_snapshot -> 'contact' -> 'last_name',
                    'title',      v.party_snapshot -> 'contact' -> 'title',
                    'email',      v.party_snapshot -> 'contact' -> 'email',
                    'phone',      v.party_snapshot -> 'contact' -> 'phone')
                end,
            'owner', jsonb_build_object(
                'name', v.party_snapshot -> 'owner' -> 'name')),
        'lines', coalesce((
            select jsonb_agg(jsonb_build_object(
                       'position',         l.position,
                       'sku',              l.sku,
                       'name',             l.name,
                       'description',      l.description,
                       'unit',             l.unit,
                       'quantity',         l.quantity,
                       'unit_price',       l.unit_price,
                       'discount_percent', l.discount_percent,
                       'tax_rate_percent', l.tax_rate_percent,
                       'line_total',       l.line_total)
                   order by l.position, l.id)
              from public.quote_lines l
             where l.version_id = v.id), '[]'::jsonb),
        'totals', jsonb_build_object(
            'subtotal',       v.subtotal,
            'discount_total', v.discount_total,
            'tax_total',      v.tax_total,
            'total',          v.total),
        'terms', v.terms,
        -- The shared thread of the QUOTE, every version's, oldest first (§2.5):
        -- a negotiation outlives the version it started on. Never an internal
        -- comment, never a deleted one, and of each author only what the page
        -- prints -- the kind and a display name. A team member is named by
        -- their `sales` row, as the owner is; a customer by the name they
        -- signed with. The customer's email stays with the team: whoever else
        -- holds the link has no business reading it.
        'comments', coalesce((
            select jsonb_agg(jsonb_build_object(
                       'author_kind', c.author_kind,
                       'author_name', case c.author_kind
                                          when 'customer' then c.author_name
                                          else nullif(btrim(concat_ws(' ', s.first_name, s.last_name)), '')
                                      end,
                       'body',        c.body,
                       'created_at',  c.created_at,
                       'edited_at',   c.edited_at)
                   order by c.created_at, c.id)
              from public.quote_comments c
              left join public.sales s on s.id = c.author_sales_id
             where c.quote_id = q.id
               and c.visibility = 'shared'
               and c.deleted_at is null), '[]'::jsonb),
        -- From the configuration singleton, because a page with no layout
        -- never loads it (F3). Null when the installation never set one; the
        -- page falls back to the build's own branding, never to a guess.
        'branding', jsonb_build_object(
            'title', (select nullif(btrim(c.config ->> 'title'), '')
                        from public.configuration c where c.id = 1),
            -- The settings screen stores the logo as `{src}`; a configuration
            -- written by hand holds a plain string.
            'logo_url', (select nullif(case jsonb_typeof(c.config -> 'lightModeLogo')
                                           when 'string' then c.config ->> 'lightModeLogo'
                                           when 'object' then c.config -> 'lightModeLogo' ->> 'src'
                                       end, '')
                           from public.configuration c where c.id = 1)),
        -- The slides frozen at issue; a version issued before the deck
        -- existed has none.
        'slides', coalesce(v.slides, '[]'::jsonb),
        -- The default template: the designed presentation the build ships.
        'standard_presentation', v.standard_presentation,
        'actions', jsonb_build_object(
            'can_accept', answerable.is_answerable and exists (
                select 1 from public.quote_transitions t
                 where t.from_status_key = q.status_key
                   and t.to_status_key = 'accepted'
                   and t.allowed_actor in ('customer', 'any')),
            'can_reject', answerable.is_answerable and exists (
                select 1 from public.quote_transitions t
                 where t.from_status_key = q.status_key
                   and t.to_status_key = 'rejected'
                   and t.allowed_actor in ('customer', 'any')),
            -- The thread stays open while the negotiation does: the live
            -- version of a quote whose status is not terminal. Read off
            -- `quote_statuses.is_terminal`, never a list of statuses, and read
            -- HERE by `quote_portal_comment()` too, so the form and the refusal
            -- are one predicate.
            'can_comment', v.superseded_at is null and exists (
                select 1 from public.quote_statuses st
                 where st.key = q.status_key
                   and not st.is_terminal)),
        'acceptance', jsonb_build_object(
            'accepted_at',      v.accepted_at,
            'accepted_by_name', v.accepted_by_name,
            'rejected_at',      v.rejected_at)) as body
      from public.quote_versions v
      join public.quotes q on q.id = v.quote_id
     cross join lateral (
        select v.superseded_at is null
               and v.accepted_at is null
               and v.rejected_at is null
               and (v.valid_until is null or v.valid_until >= current_date)
               as is_answerable
     ) answerable
     where v.id = p_version_id
       and v.issued_at is not null
      ) doc;
$$;

-- Customer portal slides: limits, box shape, the default template's lock.
create or replace trigger portal_slides_guard
    before insert or update or delete on public.portal_slides
    for each row execute function public.portal_slides_guard();

create or replace trigger portal_templates_guard
    before insert or update or delete on public.portal_templates
    for each row execute function public.portal_templates_guard();

--
-- Customer portal slides: everyone signed in reads them (a rep sees what the
-- customer will), only admins change them -- the deck is the company's voice.
--
alter table public.portal_templates enable row level security;

create policy "Portal templates are readable by authenticated users"
    on public.portal_templates for select to authenticated
    using (true);

create policy "Portal templates can be added by admins"
    on public.portal_templates for insert to authenticated
    with check ((select public.is_admin()));

create policy "Portal templates can be updated by admins"
    on public.portal_templates for update to authenticated
    using ((select public.is_admin()))
    with check ((select public.is_admin()));

create policy "Portal templates can be deleted by admins"
    on public.portal_templates for delete to authenticated
    using ((select public.is_admin()));

alter table public.portal_slides enable row level security;

create policy "Portal slides are readable by authenticated users"
    on public.portal_slides for select to authenticated
    using (true);

create policy "Portal slides can be added by admins"
    on public.portal_slides for insert to authenticated
    with check ((select public.is_admin()));

create policy "Portal slides can be updated by admins"
    on public.portal_slides for update to authenticated
    using ((select public.is_admin()))
    with check ((select public.is_admin()));

create policy "Portal slides can be deleted by admins"
    on public.portal_slides for delete to authenticated
    using ((select public.is_admin()));

--
-- Customer portal slides. No `anon` grant: the customer reads the frozen copy
-- through the `quote-portal` edge function, never this table.
--
revoke all on table public.portal_templates from anon, authenticated;
grant select, insert, update, delete on table public.portal_templates to authenticated;
grant all on table public.portal_templates to service_role;
revoke all on sequence public.portal_templates_id_seq from anon, authenticated;
grant usage on sequence public.portal_templates_id_seq to authenticated;
grant all on sequence public.portal_templates_id_seq to service_role;

revoke all on function public.portal_template_is_locked(bigint) from public, anon;
grant execute on function public.portal_template_is_locked(bigint) to authenticated;
grant execute on function public.portal_template_is_locked(bigint) to service_role;
revoke all on function public.portal_templates_guard() from public, anon, authenticated;
grant execute on function public.portal_templates_guard() to service_role;
revoke all on function public.activate_portal_template(bigint) from public, anon;
grant execute on function public.activate_portal_template(bigint) to authenticated;
grant execute on function public.activate_portal_template(bigint) to service_role;
revoke all on function public.duplicate_portal_template(bigint, text) from public, anon;
grant execute on function public.duplicate_portal_template(bigint, text) to authenticated;
grant execute on function public.duplicate_portal_template(bigint, text) to service_role;

revoke all on table public.portal_slides from anon, authenticated;
grant select, insert, update, delete on table public.portal_slides to authenticated;
grant all on table public.portal_slides to service_role;
revoke all on sequence public.portal_slides_id_seq from anon, authenticated;
grant usage on sequence public.portal_slides_id_seq to authenticated;
grant all on sequence public.portal_slides_id_seq to service_role;

revoke all on function public.portal_slide_element_is_valid(jsonb) from public, anon;
grant execute on function public.portal_slide_element_is_valid(jsonb) to authenticated;
grant execute on function public.portal_slide_element_is_valid(jsonb) to service_role;
revoke all on function public.portal_slides_guard() from public, anon, authenticated;
grant execute on function public.portal_slides_guard() to service_role;
revoke all on function public.portal_slides_snapshot() from public, anon;
grant execute on function public.portal_slides_snapshot() to authenticated;
grant execute on function public.portal_slides_snapshot() to service_role;

-- The bucket, with its limits on the bucket itself: 50 MB (the project's
-- global ceiling), pictures and videos only, no SVG.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('portal-media', 'portal-media', true, 52428800,
        array['image/webp', 'image/jpeg', 'image/png', 'image/gif', 'image/avif',
              'video/mp4', 'video/webm'])
on conflict (id) do nothing;

drop policy if exists "Portal media can be uploaded by admins" on storage.objects;
-- Customer portal media. A PUBLIC bucket (`portal-media`, created with its
-- size and type limits by the migration): the customer's browser has no
-- session and no policy grants `anon`, so the pictures and videos of a slide
-- must be readable by address. That is right for this content only -- it is
-- marketing, meant for customers. Paths are `slides/<uuid>.<ext>` and never
-- overwritten (no update policy), so a frozen snapshot keeps pointing at the
-- file it was issued with; nothing here deletes either.
create policy "Portal media can be uploaded by admins"
    on storage.objects for insert to authenticated
    with check (
        bucket_id = 'portal-media'
        and (select public.is_admin())
        and name ~ '^slides/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(webp|jpg|png|gif|avif|mp4|webm)$'
    );

-- The default template: the presentation the portal always had, with its
-- pictures bundled in the app (`builtin/...`). Active from the start, and
-- locked -- the seed flag is the only way past its guard.
select set_config('app.portal_template_seed', 'on', false);

insert into public.portal_templates (name, is_active, is_system)
values ('Predeterminada', true, true);

insert into public.portal_slides (template_id, position, elements)
select t.id, v.position, v.elements
  from public.portal_templates t,
       (values
  (0, '[{"id": "cover-photo", "kind": "image", "x": 0, "y": 0, "w": 100, "h": 100, "path": "builtin/cover.webp", "alt": "Plataforma Software - Event Production Company"}, {"id": "cover-eyebrow", "kind": "text", "x": 6, "y": 50, "w": 70, "h": 5, "text": "PLATAFORMA SOFTWARE · EVENT PRODUCTION COMPANY", "size": "sm", "align": "left", "color": "light"}, {"id": "cover-title", "kind": "text", "x": 6, "y": 56, "w": 72, "h": 24, "text": "Una propuesta pensada para {company}", "size": "xl", "align": "left", "color": "light"}, {"id": "cover-body", "kind": "text", "x": 6, "y": 80, "w": 60, "h": 16, "text": "Gracias por confiar en Plataforma Software. Hemos preparado esta propuesta para {company} con el fin de presentarte nuestra experiencia, nuestra forma de trabajar y, finalmente, el detalle de la solución y la inversión.", "size": "sm", "align": "left", "color": "light"}]'::jsonb),
  (1, '[{"id": "company-photo", "kind": "image", "x": 0, "y": 0, "w": 100, "h": 55, "path": "builtin/company.webp", "alt": "Plataforma Software en evento"}, {"id": "company-eyebrow", "kind": "text", "x": 6, "y": 59, "w": 40, "h": 5, "text": "NUESTRA EMPRESA", "size": "sm", "align": "left", "color": "light"}, {"id": "company-title", "kind": "text", "x": 6, "y": 64, "w": 88, "h": 11, "text": "Personas detrás de experiencias que conectan.", "size": "lg", "align": "left", "color": "light"}, {"id": "company-body", "kind": "text", "x": 6, "y": 76, "w": 55, "h": 20, "text": "Conoce al equipo y la experiencia que respaldan esta propuesta para {company}. Esta sección funciona como introducción corporativa y busca generar contexto antes de entrar en la solución.", "size": "sm", "align": "left", "color": "light"}, {"id": "company-highlights", "kind": "text", "x": 66, "y": 76, "w": 28, "h": 20, "text": "Experiencia\nInnovación\nEquipo\nResultados", "size": "sm", "align": "left", "color": "light"}]'::jsonb),
  (2, '[{"id": "purpose-eyebrow", "kind": "text", "x": 6, "y": 14, "w": 40, "h": 5, "text": "PROPÓSITO", "size": "sm", "align": "left", "color": "light"}, {"id": "purpose-title", "kind": "text", "x": 6, "y": 20, "w": 40, "h": 22, "text": "Tecnología aplicada a experiencias reales.", "size": "lg", "align": "left", "color": "light"}, {"id": "purpose-body", "kind": "text", "x": 6, "y": 44, "w": 40, "h": 50, "text": "Somos una compañía dedicada al desarrollo de soluciones tecnológicas propias aplicadas a la producción de eventos y a facilitar procesos de comunicación empresarial.\n\nNuestro objetivo es generar elementos diferenciadores en los productos y servicios donde son implementados.", "size": "sm", "align": "left", "color": "light"}, {"id": "purpose-photo", "kind": "image", "x": 50, "y": 0, "w": 50, "h": 100, "path": "builtin/purpose.webp", "alt": "Propósito de Plataforma Software"}]'::jsonb),
  (3, '[{"id": "certifications-photo", "kind": "image", "x": 3, "y": 8, "w": 55, "h": 84, "path": "builtin/certifications.webp", "alt": "Certificaciones y experiencia"}, {"id": "certifications-eyebrow", "kind": "text", "x": 62, "y": 12, "w": 34, "h": 5, "text": "CONFIANZA", "size": "sm", "align": "left", "color": "light"}, {"id": "certifications-title", "kind": "text", "x": 62, "y": 18, "w": 34, "h": 22, "text": "El respaldo también hace parte de la propuesta.", "size": "lg", "align": "left", "color": "light"}, {"id": "certifications-body", "kind": "text", "x": 62, "y": 42, "w": 34, "h": 54, "text": "ISO 9001:2015 — Procesos orientados a la calidad y mejora continua.\n\nISO 27001 — Seguridad y privacidad de la información.\n\nCapacitación — Equipo preparado en conocimiento especializado.\n\nServicio — Experiencia centrada en el cliente.", "size": "sm", "align": "left", "color": "light"}]'::jsonb)
       ) as v(position, elements)
 where t.is_system;

select set_config('app.portal_template_seed', '', false);
