--
-- Leads: unqualified prospects, with an atomic conversion into the CRM proper.
--
-- Decoupled from `companies` on purpose: a lead usually arrives with nothing
-- but a company name typed into a web form, long before there is a company
-- record to reference.
--

create table public.leads (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    first_name text,
    last_name text,
    email extensions.citext,
    phone text,
    company_name text,
    title text,
    source text,
    status text not null default 'new'::text,
    score smallint,
    notes text,
    tags bigint[],
    sales_id bigint,
    converted_at timestamp with time zone,
    converted_contact_id bigint,
    converted_company_id bigint,
    converted_deal_id bigint
);

alter table public.leads
    add constraint leads_sales_id_fkey foreign key (sales_id) references public.sales(id);

-- Provenance pointers, not ownership: deleting the produced record must not
-- delete the lead it came from.
alter table public.leads
    add constraint leads_converted_contact_id_fkey foreign key (converted_contact_id) references public.contacts(id) on delete set null;
alter table public.leads
    add constraint leads_converted_company_id_fkey foreign key (converted_company_id) references public.companies(id) on delete set null;
alter table public.leads
    add constraint leads_converted_deal_id_fkey foreign key (converted_deal_id) references public.deals(id) on delete set null;

create index if not exists leads_sales_id_idx on public.leads using btree (sales_id);
create index if not exists leads_created_at_idx on public.leads using btree (created_at desc);
create index if not exists leads_converted_contact_id_idx on public.leads using btree (converted_contact_id);

--
-- Ownership defaults and "last touched" bookkeeping
--

create or replace function public.set_updated_at() returns trigger
    language plpgsql
    set search_path to ''
    as $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

grant all on function public.set_updated_at() to anon;
grant all on function public.set_updated_at() to authenticated;
grant all on function public.set_updated_at() to service_role;

create or replace trigger set_lead_sales_id_trigger
    before insert on public.leads
    for each row execute function public.set_sales_id_default();

create or replace trigger set_lead_updated_at_trigger
    before update on public.leads
    for each row execute function public.set_updated_at();

--
-- Conversion
--
-- SECURITY INVOKER: row level security decides who may convert what. One
-- statement, so a failure half-way leaves nothing behind, and a row lock on
-- the lead so two simultaneous clicks cannot produce two contacts.
--
create or replace function public.convert_lead(
    lead_id bigint,
    create_deal boolean default false,
    deal_name text default null,
    deal_amount bigint default 0
) returns bigint
    language plpgsql
    set search_path to ''
    as $$
declare
  l public.leads%rowtype;
  v_company_id bigint;
  v_contact_id bigint;
  v_deal_id bigint;
begin
  select * into l from public.leads where id = lead_id for update;

  if not found then
    raise exception 'Lead % not found', lead_id using errcode = 'no_data_found';
  end if;

  if l.converted_at is not null then
    raise exception 'Lead % has already been converted', lead_id using errcode = 'unique_violation';
  end if;

  -- Reuse an existing company with the same name before creating a new one:
  -- lead forms are the main source of duplicate company records.
  if nullif(btrim(coalesce(l.company_name, '')), '') is not null then
    select id into v_company_id
    from public.companies
    where lower(name) = lower(btrim(l.company_name))
    limit 1;

    if v_company_id is null then
      insert into public.companies (name, sales_id)
      values (btrim(l.company_name), l.sales_id)
      returning id into v_company_id;
    end if;
  end if;

  insert into public.contacts (
    first_name, last_name, title, company_id, sales_id, status, tags,
    email_jsonb, phone_jsonb, first_seen, last_seen, background
  )
  values (
    l.first_name,
    l.last_name,
    l.title,
    v_company_id,
    l.sales_id,
    'warm',
    coalesce(l.tags, '{}'::bigint[]),
    case when l.email is null then '[]'::jsonb
         else jsonb_build_array(jsonb_build_object('email', l.email::text, 'type', 'Work')) end,
    case when l.phone is null then '[]'::jsonb
         else jsonb_build_array(jsonb_build_object('number', l.phone, 'type', 'Work')) end,
    coalesce(l.created_at, now()),
    now(),
    l.notes
  )
  returning id into v_contact_id;

  if create_deal then
    insert into public.deals (name, company_id, contact_ids, stage, amount, sales_id, index)
    values (
      coalesce(
        nullif(btrim(coalesce(deal_name, '')), ''),
        btrim(coalesce(l.first_name, '') || ' ' || coalesce(l.last_name, ''))
      ),
      v_company_id,
      array[v_contact_id],
      'opportunity',
      coalesce(deal_amount, 0),
      l.sales_id,
      0
    )
    returning id into v_deal_id;
  end if;

  update public.leads
  set converted_at = now(),
      status = 'converted',
      converted_contact_id = v_contact_id,
      converted_company_id = v_company_id,
      converted_deal_id = v_deal_id
  where id = lead_id;

  return v_contact_id;
end;
$$;

grant all on function public.convert_lead(bigint, boolean, text, bigint) to anon;
grant all on function public.convert_lead(bigint, boolean, text, bigint) to authenticated;
grant all on function public.convert_lead(bigint, boolean, text, bigint) to service_role;

--
-- Row level security: same ownership model as contacts and deals.
--
alter table public.leads enable row level security;

create policy "Leads are visible to their owner or a manager"
    on public.leads for select to authenticated
    using (
        (select public.can_manage_all())
        or sales_id = (select public.current_sale_id())
    );

create policy "Leads are created for their own owner"
    on public.leads for insert to authenticated
    with check (
        (select public.can_manage_all())
        or sales_id = (select public.current_sale_id())
    );

create policy "Leads are updated by their owner or a manager"
    on public.leads for update to authenticated
    using (
        (select public.can_manage_all())
        or sales_id = (select public.current_sale_id())
    )
    with check (
        (select public.can_manage_all())
        or sales_id = (select public.current_sale_id())
    );

create policy "Leads are deleted by their owner or a manager"
    on public.leads for delete to authenticated
    using (
        (select public.can_manage_all())
        or sales_id = (select public.current_sale_id())
    );

grant all on table public.leads to anon;
grant all on table public.leads to authenticated;
grant all on table public.leads to service_role;

grant all on sequence public.leads_id_seq to anon;
grant all on sequence public.leads_id_seq to authenticated;
grant all on sequence public.leads_id_seq to service_role;
