--
-- Deal stage history: why a deal moved, who moved it, and the files that
-- justified it.
--
-- Hand-written and additive. A generated diff would drop and recreate
-- `timeline_events` along with everything that depends on it; here the view is
-- replaced in place with one extra UNION branch, so nothing else is touched.
--

create table if not exists public.deal_stage_changes (
    id bigint generated by default as identity primary key,
    deal_id bigint not null references public.deals(id) on update cascade on delete cascade,
    from_stage text,
    to_stage text not null,
    reason text,
    sales_id bigint references public.sales(id),
    changed_at timestamp with time zone not null default now(),
    attachments jsonb[],
    constraint deal_stage_changes_to_stage_not_blank check (btrim(to_stage) <> ''),
    constraint deal_stage_changes_stages_differ check (from_stage is distinct from to_stage)
);

create index if not exists deal_stage_changes_deal_id_idx
    on public.deal_stage_changes (deal_id, changed_at desc);
create index if not exists deal_stage_changes_sales_id_idx
    on public.deal_stage_changes (sales_id);

--
-- The single insertion point for the history, so it cannot disagree with
-- `deals.stage`. SECURITY DEFINER because the table grants no INSERT to
-- `authenticated`: the caller was already authorised by the deals UPDATE
-- policy, and routing through the trigger is what stops a forged entry.
--
create or replace function public.deals_log_stage_change() returns trigger
    language plpgsql security definer
    set search_path to ''
as $$
declare
    v_reason      text  := nullif(btrim(coalesce(current_setting('app.deal_stage_reason', true), '')), '');
    v_attachments jsonb := nullif(coalesce(current_setting('app.deal_stage_attachments', true), ''), '')::jsonb;
    v_for_deal    text  := coalesce(current_setting('app.deal_stage_deal_id', true), '');
begin
    -- The settings belong to one specific deal. Without this check a second
    -- deal updated later in the same transaction (the kanban reindexes its
    -- neighbours on every drop) would inherit the first one's reason.
    if v_for_deal <> new.id::text then
        v_reason := null;
        v_attachments := null;
    end if;

    insert into public.deal_stage_changes
        (deal_id, from_stage, to_stage, reason, sales_id, attachments)
    values (
        new.id,
        old.stage,
        new.stage,
        v_reason,
        public.current_sale_id(),
        case
            when v_attachments is null or jsonb_typeof(v_attachments) <> 'array' then null
            else (select array_agg(element)
                    from jsonb_array_elements(v_attachments) as element)
        end
    );

    return null;
end;
$$;

create or replace trigger deals_log_stage_change
    after update of stage on public.deals
    for each row
    when (old.stage is distinct from new.stage)
    execute function public.deals_log_stage_change();

--
-- The documented write path: the move and its justification in one
-- transaction. Two client writes can half-fail, and the half that survives is
-- always the one that moves the card.
--
create or replace function public.move_deal_stage(
    p_deal_id     bigint,
    p_to_stage    text,
    p_reason      text,
    p_index       integer default null,
    p_attachments jsonb   default '[]'::jsonb
) returns public.deals
    language plpgsql security definer
    set search_path to ''
as $$
declare
    v_deal  public.deals;
    v_actor bigint := public.current_sale_id();
begin
    if coalesce(btrim(p_to_stage), '') = '' then
        raise exception 'a target stage is required'
            using errcode = 'check_violation';
    end if;

    if coalesce(btrim(p_reason), '') = '' then
        raise exception 'a reason is required to move a deal to another stage'
            using errcode = 'check_violation';
    end if;

    select * into v_deal from public.deals where id = p_deal_id for update;
    if not found then
        raise exception 'deal % not found', p_deal_id
            using errcode = 'no_data_found';
    end if;

    -- Same rule as the deals UPDATE policy. Restated because SECURITY DEFINER
    -- bypasses RLS: without this a rep could move somebody else's deal.
    if not (select public.can_manage_all()) and v_deal.sales_id is distinct from v_actor then
        raise exception 'no permission to move deal %', p_deal_id
            using errcode = 'insufficient_privilege';
    end if;

    if v_deal.stage = p_to_stage then
        raise exception 'deal % is already in stage %', p_deal_id, p_to_stage
            using errcode = 'check_violation';
    end if;

    perform set_config('app.deal_stage_deal_id', p_deal_id::text, true);
    perform set_config('app.deal_stage_reason', p_reason, true);
    perform set_config('app.deal_stage_attachments', coalesce(p_attachments, '[]'::jsonb)::text, true);

    update public.deals
       set stage = p_to_stage,
           index = coalesce(p_index, index),
           updated_at = now()
     where id = p_deal_id
    returning * into v_deal;

    perform set_config('app.deal_stage_deal_id', '', true);
    perform set_config('app.deal_stage_reason', '', true);
    perform set_config('app.deal_stage_attachments', '', true);

    return v_deal;
end;
$$;

--
-- Visibility follows the deal. No insert / update / delete policy on purpose:
-- an audit trail a client can edit answers no question worth asking.
--
alter table public.deal_stage_changes enable row level security;

drop policy if exists "Deal stage changes follow their deal for reads" on public.deal_stage_changes;
create policy "Deal stage changes follow their deal for reads"
    on public.deal_stage_changes for select to authenticated
    using (
        (select public.can_manage_all())
        or exists (
            select 1 from public.deals d
            where d.id = deal_stage_changes.deal_id
              and d.sales_id = (select public.current_sale_id())
        )
    );

grant select on table public.deal_stage_changes to authenticated;
grant all on table public.deal_stage_changes to service_role;
revoke all on function public.deals_log_stage_change() from public, anon, authenticated;
grant all on function public.deals_log_stage_change() to service_role;
revoke all on function public.move_deal_stage(bigint, text, text, integer, jsonb) from public, anon;
grant execute on function public.move_deal_stage(bigint, text, text, integer, jsonb) to authenticated, service_role;

--
-- The timeline gains the stage transitions. Replaced in place (same column
-- list) rather than dropped: `timeline_events` is what the deal page reads.
--
create or replace view public.timeline_events with (security_invoker = on) as
select
    'task_event:' || e.id            as id,
    e.occurred_at                    as occurred_at,
    e.event_type::text               as event_type,
    'task'                           as source,
    e.task_id                        as task_id,
    e.actor_sales_id                 as actor_sales_id,
    e.actor_kind                     as actor_kind,
    pl.entity_type::text             as entity_type,
    pl.entity_id                     as entity_id,
    jsonb_build_object('field', e.field, 'old', e.old_value,
                       'new', e.new_value, 'meta', e.metadata,
                       'note', e.note)  as payload
from public.task_events e
    left join lateral (
        select l.entity_type, l.entity_id
        from public.task_links l
        where l.task_id = e.task_id
          and l.is_primary
          and l.unlinked_at is null
        limit 1
    ) pl on true

union all

select
    'contact_note:' || n.id, n.date, 'note.created', 'contact_note',
    null::bigint, n.sales_id, 'user',
    'contact', n.contact_id,
    jsonb_build_object('text', n.text, 'status', n.status,
                       'contact_id', n.contact_id)
from public.contact_notes n

union all

select
    'deal_note:' || dn.id, dn.date, 'note.created', 'deal_note',
    null::bigint, dn.sales_id, 'user',
    'deal', dn.deal_id,
    jsonb_build_object('text', dn.text, 'deal_id', dn.deal_id)
from public.deal_notes dn

union all

select
    'deal_stage_change:' || sc.id, sc.changed_at, 'deal.stage_changed',
    'deal_stage_change',
    null::bigint, sc.sales_id, 'user',
    'deal', sc.deal_id,
    jsonb_build_object('from_stage', sc.from_stage, 'to_stage', sc.to_stage,
                       'reason', sc.reason, 'deal_id', sc.deal_id,
                       'attachments', to_jsonb(sc.attachments))
from public.deal_stage_changes sc;

grant select on table public.timeline_events to authenticated;
grant select on table public.timeline_events to service_role;

notify pgrst, 'reload schema';
