--
-- The pipeline follows its quotations (quotes module, deal sync).
--
-- A quotation tied to a deal now moves it: sent/viewed → the proposal stage,
-- negotiating or a customer comment → negotiation, accepted → won, rejected →
-- lost, expired → delayed (the last two only when no other quotation of the
-- deal is still open). A deal in a closing stage is never reopened. The deal's
-- amount follows the total of the version sent, and is fixed once accepted.
-- Every automatic move is recorded in `deal_stage_changes` with
-- `source = 'quote'` and the quotation, and shown on the deal's timeline.
--
-- Hand-written, expanded verbatim from the sections added to
-- supabase/schemas/0{1,2,3,4,5,6}_*.sql. The rule rows at the end are data.
--

--
-- The pipeline follows its quotations (quotes module, deal sync)
--
-- A quotation raised against a deal moves the deal on the board: sent → the
-- proposal stage, the customer answers → won or lost, and so on. The mapping is
-- DATA, one row per quotation event, for the reason `deal_stage_requirements`
-- is a table: `deals.stage` is free text and the stage list is frontend
-- configuration, so a function full of literal 'won' is wrong for the first
-- customer who renames a column. An event with no row moves nothing.
--
-- `closes` marks the stages a quotation event CLOSES a deal into (won, lost).
-- They are also the stages no quotation ever moves a deal OUT of: a deal a
-- person closed stays closed. `only_if_no_open_quote` is for the bad news
-- (rejected, expired): with another quotation still open on the deal, one
-- refusal is not the end of the deal.
create table public.deal_quote_stage_rules (
    -- A surrogate key for the admin screen (react-admin addresses rows by
    -- `id`); the event is what the rows are unique on.
    id                    bigint generated by default as identity primary key,
    trigger_key           text not null unique
        check (trigger_key in ('sent', 'viewed', 'negotiating', 'commented',
                               'accepted', 'rejected', 'expired')),
    to_stage              text not null check (btrim(to_stage) <> ''),
    closes                boolean not null default false,
    only_if_no_open_quote boolean not null default false,
    updated_at            timestamp with time zone not null default now()
);

-- Why a stage moved: `manual` (the kanban, the edit form, an import) or
-- `quote` (a quotation's own event, `sync_deal_from_quote()`), and which one.
alter table public.deal_stage_changes
    add column source text not null default 'manual'
        check (source in ('manual', 'quote')),
    add column quote_id bigint references public.quotes(id) on delete set null;

create index deal_stage_changes_quote_id_idx
    on public.deal_stage_changes (quote_id) where quote_id is not null;

-- Where the deal's amount comes from: null = typed by a person; a quotation =
-- the total of its current issued version, kept in step when it is sent and
-- fixed once it is accepted.
alter table public.deals
    add column amount_source_quote_id bigint
        references public.quotes(id) on delete set null;

create index deals_amount_source_quote_id_idx
    on public.deals (amount_source_quote_id)
    where amount_source_quote_id is not null;

create or replace function public.deals_log_stage_change() returns trigger
    language plpgsql security definer
    set search_path to ''
as $$
declare
    v_reason      text  := nullif(btrim(coalesce(current_setting('app.deal_stage_reason', true), '')), '');
    v_attachments jsonb := nullif(coalesce(current_setting('app.deal_stage_attachments', true), ''), '')::jsonb;
    v_override    text  := nullif(btrim(coalesce(current_setting('app.deal_stage_override', true), '')), '');
    v_for_deal    text  := coalesce(current_setting('app.deal_stage_deal_id', true), '');
    -- Set by `sync_deal_from_quote()`: the move was a quotation's event.
    v_source      text  := nullif(coalesce(current_setting('app.deal_stage_source', true), ''), '');
    v_quote_id    text  := nullif(coalesce(current_setting('app.deal_stage_quote_id', true), ''), '');
begin
    -- The settings belong to one specific deal. Without this check a second
    -- deal updated later in the same transaction (the kanban reindexes its
    -- neighbours on every drop) would inherit the first one's reason.
    if v_for_deal <> new.id::text then
        v_reason := null;
        v_attachments := null;
        v_override := null;
        v_source := null;
        v_quote_id := null;
    end if;

    insert into public.deal_stage_changes
        (deal_id, from_stage, to_stage, reason, sales_id, attachments,
         override_reason, source, quote_id)
    values (
        new.id,
        old.stage,
        new.stage,
        v_reason,
        public.current_sale_id(),
        case
            when v_attachments is null or jsonb_typeof(v_attachments) <> 'array' then null
            else (select array_agg(element)
                    from jsonb_array_elements(v_attachments) as element)
        end,
        v_override,
        coalesce(v_source, 'manual'),
        v_quote_id::bigint
    );

    return null;
end;
$$;

--
-- The pipeline follows its quotations
--

-- Moves a quotation's deal for one of its events, and keeps the deal's amount
-- on the quotation's total. The ONE place a quotation touches its deal; called
-- by the two triggers below, so no path that changes a quotation's status (or
-- lets the customer write) can forget to move the deal.
--
-- Deliberately NOT `move_deal_stage()`: that function asks a person for a
-- reason and for the completed-task rule, and the actor here is often the
-- customer or the expiry sweeper. The cause is recorded instead
-- (`deal_stage_changes.source = 'quote'` and the quotation), which is what
-- makes the automatic move auditable without being blockable.
create or replace function public.sync_deal_from_quote(
    p_quote_id bigint,
    p_trigger  text
) returns void
    language plpgsql security definer
    set search_path to ''
as $$
declare
    v_quote       public.quotes;
    v_rule        public.deal_quote_stage_rules;
    v_deal        public.deals;
    v_is_closed   boolean;
    v_total       numeric;
    v_is_fixed    boolean;
    v_index       integer;
begin
    select * into v_quote from public.quotes where id = p_quote_id;
    if not found or v_quote.deal_id is null then
        return;
    end if;

    select * into v_rule from public.deal_quote_stage_rules where trigger_key = p_trigger;
    if not found then
        return;
    end if;

    -- Serialises two quotations acting on one deal at the same time.
    select * into v_deal from public.deals where id = v_quote.deal_id for update;
    if not found or v_deal.archived_at is not null then
        return;
    end if;

    v_is_closed := exists (
        select 1 from public.deal_quote_stage_rules r
         where r.closes and r.to_stage = v_deal.stage);

    -- The amount: the total of the version the customer was sent, and fixed
    -- once a quotation of this deal was accepted (a later proposal on the same
    -- deal does not rewrite a sale already made).
    if p_trigger in ('sent', 'accepted') and not v_is_closed then
        v_is_fixed := exists (
            select 1 from public.quotes q
              join public.quote_statuses st on st.key = q.status_key
             where q.id = v_deal.amount_source_quote_id
               and q.id <> p_quote_id
               and st.counts_as_won);
        if not v_is_fixed then
            select v.total into v_total
              from public.quote_versions v
             where v.quote_id = p_quote_id
               and v.issued_at is not null
               and v.superseded_at is null
             order by v.version_number desc
             limit 1;
            if v_total is not null then
                -- `deals.amount` is a whole number; the quotation keeps the cents.
                update public.deals
                   set amount = round(v_total)::bigint,
                       amount_source_quote_id = p_quote_id,
                       updated_at = now()
                 where id = v_deal.id
                   and (amount is distinct from round(v_total)::bigint
                        or amount_source_quote_id is distinct from p_quote_id);
            end if;
        end if;
    end if;

    if v_is_closed or v_deal.stage = v_rule.to_stage then
        return;
    end if;

    if v_rule.only_if_no_open_quote and exists (
        select 1 from public.quotes q
          join public.quote_statuses st on st.key = q.status_key
         where q.deal_id = v_deal.id
           and q.id <> p_quote_id
           and st.is_open) then
        return;
    end if;

    -- On top of its new column, where the board shows what just happened.
    select coalesce(min(d.index), 0) - 1 into v_index
      from public.deals d
     where d.stage = v_rule.to_stage and d.archived_at is null;

    perform set_config('app.deal_stage_reason', 'quote:' || p_trigger, true);
    perform set_config('app.deal_stage_deal_id', v_deal.id::text, true);
    perform set_config('app.deal_stage_source', 'quote', true);
    perform set_config('app.deal_stage_quote_id', p_quote_id::text, true);

    update public.deals
       set stage = v_rule.to_stage,
           index = greatest(v_index, -32768),
           updated_at = now()
     where id = v_deal.id;

    perform set_config('app.deal_stage_reason', '', true);
    perform set_config('app.deal_stage_deal_id', '', true);
    perform set_config('app.deal_stage_source', '', true);
    perform set_config('app.deal_stage_quote_id', '', true);
end;
$$;

-- AFTER UPDATE OF status_key ON quotes: every status change of a quotation,
-- whoever made it (the rep, the customer on the portal, the sweeper), reaches
-- its deal. Every status change goes through `apply_quote_status()`, and every
-- one of those lands here.
create or replace function public.quotes_sync_deal() returns trigger
    language plpgsql security definer
    set search_path to ''
as $$
begin
    perform public.sync_deal_from_quote(new.id, new.status_key);
    return null;
end;
$$;

-- AFTER INSERT ON quote_portal_events: the customer writing back is what opens
-- a negotiation. Portal events are the customer's by construction (the team
-- writes in `quote_comments`).
create or replace function public.quote_portal_events_sync_deal() returns trigger
    language plpgsql security definer
    set search_path to ''
as $$
begin
    if new.event_type = 'commented' then
        perform public.sync_deal_from_quote(new.quote_id, 'commented');
    end if;
    return null;
end;
$$;

-- The deal follows its quotations (`sync_deal_from_quote()`).
create or replace trigger quotes_sync_deal
    after update of status_key on public.quotes
    for each row
    when (old.status_key is distinct from new.status_key)
    execute function public.quotes_sync_deal();

create or replace trigger quote_portal_events_sync_deal
    after insert on public.quote_portal_events
    for each row execute function public.quote_portal_events_sync_deal();

create or replace view public.timeline_events with (security_invoker = on) as
select
    'task_event:' || e.id            as id,
    e.occurred_at                    as occurred_at,
    e.event_type::text               as event_type,
    'task'                           as source,
    e.task_id                        as task_id,
    e.actor_sales_id                 as actor_sales_id,
    e.actor_kind                     as actor_kind,
    -- The entity the event hangs off, so a contact or deal page can filter
    -- without joining task_links itself.
    pl.entity_type::text             as entity_type,
    pl.entity_id                     as entity_id,
    jsonb_build_object('field', e.field, 'old', e.old_value,
                       'new', e.new_value, 'meta', e.metadata,
                       'note', e.note)  as payload
from public.task_events e
    left join lateral (
        select l.entity_type, l.entity_id
        from public.task_links l
        where l.task_id = e.task_id
          and l.is_primary
          and l.unlinked_at is null
        limit 1
    ) pl on true

union all

select
    'contact_note:' || n.id, n.date, 'note.created', 'contact_note',
    null::bigint, n.sales_id, 'user',
    'contact', n.contact_id,
    jsonb_build_object('text', n.text, 'status', n.status,
                       'contact_id', n.contact_id)
from public.contact_notes n

union all

select
    'deal_note:' || dn.id, dn.date, 'note.created', 'deal_note',
    null::bigint, dn.sales_id, 'user',
    'deal', dn.deal_id,
    jsonb_build_object('text', dn.text, 'deal_id', dn.deal_id)
from public.deal_notes dn

union all

-- Stage transitions. The one event on this timeline the user did not write as
-- prose: the reason and the files travel in the payload so the deal page can
-- render "why" next to "when", without a second query per row.
select
    'deal_stage_change:' || sc.id, sc.changed_at, 'deal.stage_changed',
    'deal_stage_change',
    null::bigint, sc.sales_id,
    -- A quotation's event moved it with nobody signed in (the customer, the
    -- sweeper): the system acted, not a user.
    case when sc.source = 'quote' and sc.sales_id is null then 'system' else 'user' end,
    'deal', sc.deal_id,
    jsonb_build_object('from_stage', sc.from_stage, 'to_stage', sc.to_stage,
                       'reason', sc.reason, 'deal_id', sc.deal_id,
                       'attachments', to_jsonb(sc.attachments),
                       'override_reason', sc.override_reason,
                       'source', sc.source, 'quote_id', sc.quote_id,
                       'quote_number', sq.quote_number)
from public.deal_stage_changes sc
    left join public.quotes sq on sq.id = sc.quote_id

union all

-- Quote transitions, surfaced on the DEAL the quote was raised against, so the
-- deal page tells the whole commercial story without a second query per row.
-- Only quotes that still have a deal: `quotes.deal_id` is `on delete set null`.
--
-- The three quote arms take this view from four to seven, which is what makes
-- the materialized `timeline` table named in the caveat above due. They are the
-- cheapest kind -- small tables, indexed on `(quote_id, … desc)` -- and every
-- filter stays on plain columns.
select
    'quote_status_change:deal:' || sc.id, sc.changed_at, 'quote.status_changed',
    'quote_status_change',
    null::bigint, sc.sales_id,
    -- 'system' rather than inventing a 'customer' value, so the switch in
    -- `timeline/EntityTimeline.tsx` cannot fall through. Who acted lives in
    -- `payload.actor_kind`.
    case when sc.actor_kind = 'internal' then 'user' else 'system' end,
    'deal', q.deal_id,
    jsonb_build_object('quote_id', sc.quote_id, 'quote_number', q.quote_number,
                       'from_status', sc.from_status, 'to_status', sc.to_status,
                       'reason', sc.reason, 'actor_kind', sc.actor_kind,
                       'override_reason', sc.override_reason)
from public.quote_status_changes sc
    join public.quotes q on q.id = sc.quote_id
where q.deal_id is not null

union all

-- The same transitions, on the quote itself.
select
    'quote_status_change:' || sc.id, sc.changed_at, 'quote.status_changed',
    'quote_status_change',
    null::bigint, sc.sales_id,
    case when sc.actor_kind = 'internal' then 'user' else 'system' end,
    'quote', sc.quote_id,
    jsonb_build_object('quote_id', sc.quote_id, 'quote_number', q.quote_number,
                       'from_status', sc.from_status, 'to_status', sc.to_status,
                       'reason', sc.reason, 'actor_kind', sc.actor_kind,
                       'attachments', to_jsonb(sc.attachments),
                       'override_reason', sc.override_reason)
from public.quote_status_changes sc
    join public.quotes q on q.id = sc.quote_id

union all

-- What the customer did on the portal. `ip_address` and `user_agent` are
-- deliberately absent from the payload: they belong in the audit table, not on
-- a screen a whole sales team reads.
select
    'quote_portal_event:' || e.id, e.occurred_at, 'quote.' || e.event_type,
    'quote_portal_event',
    null::bigint, null::bigint, 'system',
    'quote', e.quote_id,
    jsonb_build_object('quote_id', e.quote_id, 'version_id', e.version_id,
                       'actor_name', e.actor_name, 'detail', e.payload)
from public.quote_portal_events e

union all

-- The customer writing back, on the DEAL too: it is what moves a deal into
-- negotiation, so its history must say so. Only comments: a view and an
-- answer already reach the deal as the status change they caused, and the
-- same event twice on one timeline is noise.
select
    'quote_portal_event:deal:' || e.id, e.occurred_at, 'quote.' || e.event_type,
    'quote_portal_event',
    null::bigint, null::bigint, 'system',
    'deal', q.deal_id,
    jsonb_build_object('quote_id', e.quote_id, 'quote_number', q.quote_number,
                       'version_id', e.version_id,
                       'actor_name', e.actor_name, 'detail', e.payload)
from public.quote_portal_events e
    join public.quotes q on q.id = e.quote_id
where q.deal_id is not null
  and e.event_type = 'commented';


-- The quotation→stage rules: read by everybody (the board explains why a deal
-- moved), written by admins only — like `deal_stage_requirements`, a change
-- here moves every deal of the organisation, and it leaves no trace.
alter table public.deal_quote_stage_rules enable row level security;

create policy "Deal quote stage rules are readable by everyone"
    on public.deal_quote_stage_rules for select to authenticated
    using (true);

create policy "Deal quote stage rules are maintained by admins"
    on public.deal_quote_stage_rules for all to authenticated
    using ((select public.is_admin()))
    with check ((select public.is_admin()));


-- The deal follows its quotations.
revoke all on table public.deal_quote_stage_rules from anon, authenticated;
grant select, insert, update, delete on table public.deal_quote_stage_rules to authenticated;
grant all on table public.deal_quote_stage_rules to service_role;
revoke all on sequence public.deal_quote_stage_rules_id_seq from anon, authenticated;
grant usage, select on sequence public.deal_quote_stage_rules_id_seq to authenticated;
grant all on sequence public.deal_quote_stage_rules_id_seq to service_role;

revoke all on function public.sync_deal_from_quote(bigint, text) from public, anon, authenticated;
revoke all on function public.quotes_sync_deal() from public, anon, authenticated;
revoke all on function public.quote_portal_events_sync_deal() from public, anon, authenticated;
grant execute on function public.sync_deal_from_quote(bigint, text) to service_role;
grant execute on function public.quotes_sync_deal() to service_role;
grant execute on function public.quote_portal_events_sync_deal() to service_role;

--
-- Data: the mapping, for the default stages (`root/defaultConfiguration.ts`).
-- An installation that renamed its stages edits these rows in the settings.
--
insert into public.deal_quote_stage_rules
    (trigger_key, to_stage, closes, only_if_no_open_quote)
values
    ('sent',        'proposal-sent',  false, false),
    ('viewed',      'proposal-sent',  false, false),
    ('negotiating', 'in-negociation', false, false),
    ('commented',   'in-negociation', false, false),
    ('accepted',    'won',            true,  false),
    ('rejected',    'lost',           true,  true),
    ('expired',     'delayed',        false, true)
on conflict (trigger_key) do nothing;
