--
-- Team budgets, and the deal -> team link the budget dashboard reports on.
--
-- Hand-written and ADD-only. Nothing here drops a column or retypes one, so no
-- dependent view has to be recreated: `activity_log` reaches into the deal
-- rowtype with `to_json(d.*)`, and Postgres re-resolves that on ADD COLUMN.
-- `teams_summary` is extended with CREATE OR REPLACE, which is legal because
-- every new column is appended AFTER the existing ones, in order.
--

--
-- 1. Overlap detection for budget periods needs bigint equality and range
--    overlap in the same GiST index. Plain GiST cannot do the equality half.
--
create extension if not exists "btree_gist" with schema "extensions";

--
-- 2. Which team a deal counts for.
--
--    Deliberately its own column rather than a lookup through the owner's
--    membership: a rep in two teams would make the same amount count twice,
--    and moving a rep between teams would retroactively rewrite the numbers of
--    quarters that are already closed.
--
alter table public.deals add column if not exists team_id bigint;

alter table public.deals drop constraint if exists deals_team_id_fkey;
alter table public.deals
    add constraint deals_team_id_fkey foreign key (team_id)
    references public.teams(id);

-- The dashboard never sums archived deals, so neither does the index.
create index if not exists deals_team_id_idx
    on public.deals (team_id) where archived_at is null;

--
-- 3. What a team is expected to sell, per period.
--
--    A table rather than a column on `teams`: a budget with no period cannot
--    answer "how did we do in Q3", and overwriting the number to set the next
--    target would destroy the only record of the previous one.
--
create table if not exists public.team_budgets (
    id           bigint generated by default as identity primary key,
    team_id      bigint not null references public.teams(id) on delete cascade,
    period_start date not null,
    period_end   date not null,
    amount       numeric(14,2) not null check (amount >= 0),
    created_at   timestamp with time zone not null default now(),
    constraint team_budgets_period_order check (period_end > period_start),
    constraint team_budgets_no_overlap exclude using gist (
        team_id with =,
        daterange(period_start, period_end, '[]') with &&
    )
);

--
-- 4. Access. Unlike `teams` — readable by everyone so a rep can see which team
--    a task is assigned to — a quota is commercially sensitive and a rep has no
--    product reason to read one. Read is gated with write: admins and managers.
--
alter table public.team_budgets enable row level security;

drop policy if exists "Team budgets are readable and manageable by managers and admins"
    on public.team_budgets;
create policy "Team budgets are readable and manageable by managers and admins"
    on public.team_budgets for all to authenticated
    using ((select public.can_manage_all()))
    with check ((select public.can_manage_all()));

grant select, insert, update, delete on table public.team_budgets to authenticated;
grant all on table public.team_budgets to service_role;

--
-- 5. Seed the link from the owner's current membership.
--
--    A starting point, not the truth: `order by tm.team_id limit 1` picks
--    deterministically for a rep who belongs to several teams, and from here on
--    the field is edited on the deal itself.
--
update public.deals d
   set team_id = (
        select tm.team_id
          from public.team_members tm
         where tm.sales_id = d.sales_id
         order by tm.team_id
         limit 1
   )
 where d.team_id is null
   and d.sales_id is not null;

--
-- 6. The reporting projection.
--
--    Budget columns come from the period containing today, picked with
--    LATERAL ... LIMIT 1 — evaluated only for the rows that survive
--    ORDER BY ... LIMIT. The amounts are scalar subqueries for the reason
--    documented on `contacts_summary`: a join plus GROUP BY here aggregates the
--    whole deals table before the LIMIT can discard it.
--
--    Amounts are scoped to the budget period, so won_amount against
--    budget_amount is like-for-like. A team with no vigente budget gets NULL
--    bounds, every `between` is false, and the amounts come back 0 — the
--    dashboard shows "no budget set", not a team that sold nothing.
--
--    security_invoker stays on: a rep reading this aggregates only the deals
--    their own RLS lets them see, a manager sees the whole team.
--
create or replace view public.teams_summary with (security_invoker = on) as
select
    t.id,
    t.name,
    t.description,
    t.created_at,
    (select count(*) from public.team_members m where m.team_id = t.id) as nb_members,
    b.id           as budget_id,
    b.amount       as budget_amount,
    b.period_start as budget_period_start,
    b.period_end   as budget_period_end,
    (select coalesce(sum(d.amount), 0) from public.deals d
      where d.team_id = t.id
        and d.archived_at is null
        and d.stage <> 'won'
        and d.expected_closing_date between b.period_start and b.period_end
    ) as pipeline_amount,
    (select coalesce(sum(d.amount), 0) from public.deals d
      where d.team_id = t.id
        and d.archived_at is null
        and d.stage = 'won'
        and d.expected_closing_date between b.period_start and b.period_end
    ) as won_amount,
    (select count(*) from public.deals d
      where d.team_id = t.id and d.archived_at is null
    ) as nb_deals
from public.teams t
left join lateral (
    select tb.id, tb.amount, tb.period_start, tb.period_end
      from public.team_budgets tb
     where tb.team_id = t.id
       and current_date between tb.period_start and tb.period_end
     order by tb.period_start desc
     limit 1
) b on true;

grant select on table public.teams_summary to authenticated;
grant select on table public.teams_summary to service_role;
