--
-- Task module — Phase 1, step 1: enums and catalogues.
--
-- Implements proposal §3.3 (DDL) + Appendix C step 1:
--
--   - `task_statuses`: the 9 lifecycle states (§4.1). `key` is the machine
--     value the state machine and the UI work with; `label` is the default
--     display text (the frontend translates by `key` through i18n).
--   - `task_priorities`: low / normal / high / urgent, with a display rank
--     and an optional SLA in hours.
--   - `task_types`: replaces the free-text `type` column (fixes W11). Seeded
--     from the defaults in `root/defaultConfiguration.ts` plus whatever the
--     current `tasks.type` values contain, so no existing data is orphaned.
--
-- The enums (`task_role`, `task_entity`, `task_event_type`) are declared here
-- as well because the subsequent migrations reference them; Postgres enum
-- values cannot be added inside a transaction, so each migration that uses a
-- new value must be in its own file.
--

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------

create type public.task_role as enum ('owner', 'collaborator', 'watcher', 'team');

-- Polymorphic link targets. Only the four that exist today are exercised by
-- the code, but the enum is the extension point for future entities (§14.1).
create type public.task_entity as enum
    ('contact', 'lead', 'company', 'deal', 'project', 'ticket', 'invoice', 'quote', 'order');

create type public.task_event_type as enum (
    -- lifecycle
    'task.created', 'task.updated', 'task.scheduled', 'task.started', 'task.waiting',
    'task.resumed', 'task.blocked', 'task.unblocked', 'task.completed', 'task.reopened',
    'task.canceled', 'task.archived', 'task.unarchived', 'task.deleted', 'task.restored',
    -- planning
    'task.rescheduled', 'task.priority_changed', 'task.type_changed', 'task.title_changed',
    'task.description_changed', 'task.due_removed',
    -- people
    'task.assigned', 'task.unassigned', 'task.reassigned', 'task.watcher_added',
    'task.watcher_removed', 'task.team_assigned',
    -- collaboration
    'comment.created', 'comment.edited', 'comment.deleted', 'comment.reaction_added',
    'comment.reaction_removed', 'mention.created',
    -- artefacts
    'attachment.added', 'attachment.removed',
    'checklist.item_added', 'checklist.item_completed', 'checklist.item_reopened',
    'checklist.item_removed', 'checklist.item_reordered',
    -- links & graph
    'link.added', 'link.removed', 'link.primary_changed',
    'dependency.added', 'dependency.removed', 'dependency.satisfied',
    -- time & reminders
    'timelog.started', 'timelog.stopped', 'timelog.edited',
    'reminder.created', 'reminder.updated', 'reminder.canceled',
    'reminder.sent', 'reminder.failed', 'reminder.acknowledged',
    -- system
    'automation.applied', 'sla.breached', 'sla.warning', 'import.applied'
);

-- ---------------------------------------------------------------------------
-- task_statuses
-- ---------------------------------------------------------------------------

create table public.task_statuses (
    id             bigint generated by default as identity primary key,
    key            text not null unique,             -- 'pending', 'in_progress', …
    label          text not null,
    color          text not null default 'gray',
    rank           smallint not null,                -- display order
    is_open        boolean not null default true,    -- counts as "open work"
    is_terminal    boolean not null default false,   -- no transitions out (except reopen)
    counts_as_done boolean not null default false,
    is_system      boolean not null default false    -- system states cannot be deleted
);

insert into public.task_statuses (key, label, color, rank, is_open, is_terminal, counts_as_done, is_system)
values ('pending',     'Pending',            'gray',  10, true,  false, false, true),
       ('scheduled',   'Scheduled',          'blue',  20, true,  false, false, true),
       ('in_progress', 'In progress',        'green', 30, true,  false, false, true),
       ('waiting',     'Waiting on response','amber', 40, true,  false, false, true),
       ('blocked',     'Blocked',            'red',   50, true,  false, false, true),
       ('rescheduled', 'Rescheduled',        'teal',  60, true,  false, false, true),
       ('completed',   'Completed',          'green', 70, false, true,  true,  true),
       ('canceled',    'Canceled',           'gray',  80, false, true,  false, true),
       ('archived',    'Archived',           'gray',  90, false, true,  false, true);

-- ---------------------------------------------------------------------------
-- task_priorities
-- ---------------------------------------------------------------------------

create table public.task_priorities (
    id        bigint generated by default as identity primary key,
    key       text not null unique,             -- 'low' | 'normal' | 'high' | 'urgent'
    label     text not null,
    color     text not null,
    rank      smallint not null,
    sla_hours integer                            -- null = no SLA
);

insert into public.task_priorities (key, label, color, rank, sla_hours)
values ('low',    'Low',    'gray',  10, null),
       ('normal', 'Normal', 'blue',  20, null),
       ('high',   'High',   'amber', 30, 24),
       ('urgent', 'Urgent', 'red',   40, 4);

-- ---------------------------------------------------------------------------
-- task_types
-- ---------------------------------------------------------------------------

create table public.task_types (
    id        bigint generated by default as identity primary key,
    key       text not null unique,             -- 'call', 'email', 'demo', …
    label     text not null,
    icon      text,
    is_active boolean not null default true
);

-- The same set the frontend ships in `root/defaultConfiguration.ts`.
insert into public.task_types (key, label, icon, is_active)
values ('none',       'None',       null, true),
       ('email',      'Email',      null, true),
       ('demo',       'Demo',       null, true),
       ('lunch',      'Lunch',      null, true),
       ('meeting',    'Meeting',    null, true),
       ('follow-up',  'Follow-up',  null, true),
       ('thank-you',  'Thank you',  null, true),
       ('ship',       'Ship',       null, true),
       ('call',       'Call',       null, true);

-- Adopt any legacy `type` values that are not in the default set, so the
-- existing rows keep their type after the migration (Appendix C step 1).
insert into public.task_types (key, label, icon, is_active)
select distinct coalesce(nullif(type, ''), 'none'), initcap(coalesce(nullif(type, ''), 'none')), null, true
from public.tasks
where coalesce(nullif(type, ''), 'none') not in
      ('none', 'email', 'demo', 'lunch', 'meeting', 'follow-up', 'thank-you', 'ship', 'call');

-- ---------------------------------------------------------------------------
-- RLS and grants
-- ---------------------------------------------------------------------------

-- Catalogues are shared reference data: readable by every authenticated user,
-- writable only by admins (`task.manage_catalogs` capability, §17.1).
alter table public.task_statuses enable row level security;
alter table public.task_priorities enable row level security;
alter table public.task_types enable row level security;

create policy "Catalogues are readable by every authenticated user"
    on public.task_statuses for select to authenticated
    using (true);
create policy "Catalogues are manageable by admins only"
    on public.task_statuses for all to authenticated
    using (public.is_admin())
    with check (public.is_admin());

create policy "Catalogues are readable by every authenticated user"
    on public.task_priorities for select to authenticated
    using (true);
create policy "Catalogues are manageable by admins only"
    on public.task_priorities for all to authenticated
    using (public.is_admin())
    with check (public.is_admin());

create policy "Catalogues are readable by every authenticated user"
    on public.task_types for select to authenticated
    using (true);
create policy "Catalogues are manageable by admins only"
    on public.task_types for all to authenticated
    using (public.is_admin())
    with check (public.is_admin());

-- Following the existing pattern (`grant all ... to anon/authenticated/...`),
-- but scoped to authenticated for the task tables (§17.3 P1: grant only what
-- PostgREST needs, to `authenticated`).
grant select, insert, update, delete on table public.task_statuses to authenticated;
grant select, insert, update, delete on table public.task_priorities to authenticated;
grant select, insert, update, delete on table public.task_types to authenticated;
grant select, insert, update, delete on table public.task_statuses to service_role;
grant select, insert, update, delete on table public.task_priorities to service_role;
grant select, insert, update, delete on table public.task_types to service_role;
