--
-- Per-member budget allocation, and the drill-down statistics the team
-- dashboard reports on.
--
-- Hand-written and ADD-only. One new table, two unique constraints that exist
-- only to be foreign-key targets, two columns appended to existing views
-- (legal for CREATE OR REPLACE because they come after every existing column,
-- in order) and one new view. Nothing is dropped or retyped, so no dependent
-- object has to be recreated.
--

--
-- 1. Composite keys, so an allocation cannot belong to two teams at once.
--
--    A plain `references team_budgets(id)` plus `references team_members(id)`
--    would happily accept team A's budget paired with team B's member. That
--    row is invisible in every screen — it sums into one team's allocated
--    total while the roster it should appear in never shows it — so the first
--    symptom is a total that does not match its own breakdown. The composite
--    foreign keys below make it unrepresentable instead of merely unlikely.
--
alter table public.team_budgets drop constraint if exists team_budgets_id_team_id_key;
alter table public.team_budgets
    add constraint team_budgets_id_team_id_key unique (id, team_id);

alter table public.team_members drop constraint if exists team_members_id_team_id_key;
alter table public.team_members
    add constraint team_members_id_team_id_key unique (id, team_id);

--
-- 2. What each member of a team is expected to sell out of the team's target.
--
--    Keyed on the BUDGET, not on the team: an allocation with no period is the
--    mistake `team_budgets` exists to avoid — it would follow the team into the
--    next period and silently restate what was promised for the last one.
--    Hanging it off `team_budgets.id` makes "open a new period" mean "start
--    from a blank allocation", which is the honest default.
--
--    Keyed on the MEMBERSHIP rather than on the person: somebody removed from
--    the team carries no quota in it, so the roster quotas always sum to the
--    team's allocated total and the breakdown reconciles with the figure it
--    sits under.
--
--    The sum is deliberately NOT constrained to the team budget. Reallocating
--    between two members is two writes, and an invariant enforced per row would
--    reject the first one purely for being first. Over- and under-allocation
--    are reported by the UI instead, which is also the only place that can say
--    by how much.
--
create table if not exists public.team_member_budgets (
    id             bigint generated by default as identity primary key,
    team_id        bigint not null,
    budget_id      bigint not null,
    team_member_id bigint not null,
    amount         numeric(14,2) not null check (amount >= 0),
    created_at     timestamp with time zone not null default now(),
    unique (budget_id, team_member_id),
    foreign key (budget_id, team_id)
        references public.team_budgets (id, team_id) on delete cascade,
    foreign key (team_member_id, team_id)
        references public.team_members (id, team_id) on delete cascade
);

-- "What is this person's quota", asked by the member drill-down. The unique
-- index above leads with `budget_id` and cannot serve it.
create index if not exists team_member_budgets_team_member_id_idx
    on public.team_member_budgets (team_member_id);

--
-- 3. Access. A per-person quota is at least as sensitive as the team target it
--    is carved out of, so it gets the same answer: admin and manager only,
--    read included. Letting a rep read their own is a product decision, not a
--    default — it would take a second `for select` policy joined through
--    `team_members`.
--
alter table public.team_member_budgets enable row level security;

drop policy if exists "Member budgets are readable and manageable by managers and admins"
    on public.team_member_budgets;
create policy "Member budgets are readable and manageable by managers and admins"
    on public.team_member_budgets for all to authenticated
    using ((select public.can_manage_all()))
    with check ((select public.can_manage_all()));

-- No sequence grant: `id` is an identity column, so INSERT on the table is
-- enough. `team_budgets` is granted the same way.
grant select, insert, update, delete on table public.team_member_budgets to authenticated;
grant all on table public.team_member_budgets to service_role;

--
-- 4. `teams_summary` gains how much of the target is already handed out.
--
--    Appended after `nb_deals`, so CREATE OR REPLACE accepts it. A team with no
--    budget for the period has no allocations either — they cascade off the
--    budget row — so this reads 0 rather than null: nothing has been handed
--    out, which is a fact, unlike "there is no target".
--
create or replace view public.teams_summary with (security_invoker = on) as
select
    t.id,
    t.name,
    t.description,
    t.created_at,
    (select count(*) from public.team_members m where m.team_id = t.id) as nb_members,
    b.id           as budget_id,
    b.amount       as budget_amount,
    b.period_start as budget_period_start,
    b.period_end   as budget_period_end,
    (select coalesce(sum(d.amount), 0) from public.deals d
      where d.team_id = t.id
        and d.archived_at is null
        and d.stage <> 'won'
        and d.expected_closing_date between b.period_start and b.period_end
    ) as pipeline_amount,
    (select coalesce(sum(d.amount), 0) from public.deals d
      where d.team_id = t.id
        and d.archived_at is null
        and d.stage = 'won'
        and d.expected_closing_date between b.period_start and b.period_end
    ) as won_amount,
    (select count(*) from public.deals d
      where d.team_id = t.id and d.archived_at is null
    ) as nb_deals,
    (select coalesce(sum(mb.amount), 0) from public.team_member_budgets mb
      where mb.budget_id = b.id
    ) as allocated_amount
from public.teams t
left join lateral (
    select tb.id, tb.amount, tb.period_start, tb.period_end
      from public.team_budgets tb
     where tb.team_id = t.id
       and current_date between tb.period_start and tb.period_end
     order by tb.period_start desc
     limit 1
) b on true;

grant select on table public.teams_summary to authenticated;
grant select on table public.teams_summary to service_role;

--
-- 5. `team_members_summary` gains the member's own quota for that period.
--
--    Null, not zero, when nothing was allocated: "no target" and "a target of
--    nothing" render differently, and only one of them is true here. It is
--    appended after `nb_open_tasks`; the lateral now also selects `tb.id`,
--    which is internal to the view and not an output column, so the replace
--    stays legal.
--
create or replace view public.team_members_summary
with (security_invoker = on) as
select
    m.id,
    m.team_id,
    m.sales_id,
    m.created_at,
    s.first_name,
    s.last_name,
    s.email,
    s.role,
    s.disabled,
    (select count(*) from public.contacts c
      where c.sales_id = m.sales_id) as nb_contacts,
    (select count(*) from public.companies co
      where co.sales_id = m.sales_id) as nb_companies,
    (select count(*) from public.deals d
      where d.sales_id = m.sales_id and d.archived_at is null) as nb_deals_all,
    (select count(*) from public.deals d
      where d.sales_id = m.sales_id
        and d.team_id = m.team_id
        and d.archived_at is null) as nb_deals,
    (select coalesce(sum(d.amount), 0) from public.deals d
      where d.sales_id = m.sales_id
        and d.team_id = m.team_id
        and d.archived_at is null
        and d.stage <> 'won'
        and d.expected_closing_date between b.period_start and b.period_end
    ) as pipeline_amount,
    (select coalesce(sum(d.amount), 0) from public.deals d
      where d.sales_id = m.sales_id
        and d.team_id = m.team_id
        and d.archived_at is null
        and d.stage = 'won'
        and d.expected_closing_date between b.period_start and b.period_end
    ) as won_amount,
    (select count(*) from public.tasks tk
      join public.task_statuses st on st.id = tk.status_id
     where tk.owner_sales_id = m.sales_id
       and st.is_open
       and tk.deleted_at is null
       and tk.archived_at is null) as nb_open_tasks,
    (select mb.amount from public.team_member_budgets mb
      where mb.budget_id = b.id and mb.team_member_id = m.id) as budget_amount
from public.team_members m
join public.sales s on s.id = m.sales_id
left join lateral (
    select tb.id, tb.period_start, tb.period_end
      from public.team_budgets tb
     where tb.team_id = m.team_id
       and current_date between tb.period_start and tb.period_end
     order by tb.period_start desc
     limit 1
) b on true;

grant select on table public.team_members_summary to authenticated;
grant select on table public.team_members_summary to service_role;

--
-- 6. The drill-down cube: one row per team, member, month and stage.
--
--    A GROUP BY here rather than the scalar subqueries the list views use, and
--    for the opposite reason: this view IS the aggregate, there is no
--    ORDER BY ... LIMIT for a premature grouping to defeat, and both filters
--    the UI applies (`team_id`, `sales_id`) are grouping columns, so the
--    predicate reaches the deals scan.
--
--    One cube instead of a monthly view plus a by-stage view: the drill-down
--    pages read it once and fold it two ways in the browser, over the tens of
--    rows a single team's period produces.
--
--    Scoped to the team's current budget period so the charts reconcile with
--    the header they sit under, falling back to the calendar year for a team
--    with no budget — an empty chart there would read as "sold nothing"
--    rather than "no period to report on".
--
create or replace view public.team_deal_stats with (security_invoker = on) as
select
    t.id || '-' || coalesce(d.sales_id, 0) || '-'
        || to_char(date_trunc('month', d.expected_closing_date), 'YYYY-MM')
        || '-' || d.stage as id,
    t.id       as team_id,
    d.sales_id,
    date_trunc('month', d.expected_closing_date)::date as month,
    d.stage,
    count(*)                   as nb_deals,
    coalesce(sum(d.amount), 0) as amount
from public.teams t
join public.deals d
  on d.team_id = t.id
 and d.archived_at is null
 and d.expected_closing_date is not null
left join lateral (
    select tb.period_start, tb.period_end
      from public.team_budgets tb
     where tb.team_id = t.id
       and current_date between tb.period_start and tb.period_end
     order by tb.period_start desc
     limit 1
) b on true
where d.expected_closing_date
        between coalesce(b.period_start, date_trunc('year', current_date)::date)
            and coalesce(b.period_end,
                         (date_trunc('year', current_date) + interval '1 year - 1 day')::date)
group by t.id, d.sales_id, date_trunc('month', d.expected_closing_date), d.stage;

grant select on table public.team_deal_stats to authenticated;
grant select on table public.team_deal_stats to service_role;
