-- Task module — checklists (§11).
--
-- Phase 2.7 of docs/proposals/enterprise-task-module.md. Also the first thing
-- to actually maintain tasks.checklist_total / checklist_done: the columns
-- shipped with Phase 1 but nothing wrote to them until now.


  create table "public"."task_checklist_items" (
    "id" bigint generated by default as identity not null,
    "task_id" bigint not null,
    "label" text not null,
    "position" numeric not null,
    "is_done" boolean not null default false,
    "done_at" timestamp with time zone,
    "done_by" bigint,
    "due_at" timestamp with time zone,
    "assignee_id" bigint,
    "created_by" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "deleted_at" timestamp with time zone
      );


alter table "public"."task_checklist_items" enable row level security;

CREATE UNIQUE INDEX task_checklist_items_pkey ON public.task_checklist_items USING btree (id);

CREATE INDEX task_checklist_items_task ON public.task_checklist_items USING btree (task_id, "position") WHERE (deleted_at IS NULL);

alter table "public"."task_checklist_items" add constraint "task_checklist_items_pkey" PRIMARY KEY using index "task_checklist_items_pkey";

alter table "public"."task_checklist_items" add constraint "checklist_done_consistency" CHECK ((((is_done = false) AND (done_at IS NULL) AND (done_by IS NULL)) OR ((is_done = true) AND (done_at IS NOT NULL) AND (done_by IS NOT NULL)))) not valid;

alter table "public"."task_checklist_items" validate constraint "checklist_done_consistency";

alter table "public"."task_checklist_items" add constraint "task_checklist_items_assignee_id_fkey" FOREIGN KEY (assignee_id) REFERENCES public.sales(id) not valid;

alter table "public"."task_checklist_items" validate constraint "task_checklist_items_assignee_id_fkey";

alter table "public"."task_checklist_items" add constraint "task_checklist_items_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.sales(id) not valid;

alter table "public"."task_checklist_items" validate constraint "task_checklist_items_created_by_fkey";

alter table "public"."task_checklist_items" add constraint "task_checklist_items_done_by_fkey" FOREIGN KEY (done_by) REFERENCES public.sales(id) not valid;

alter table "public"."task_checklist_items" validate constraint "task_checklist_items_done_by_fkey";

alter table "public"."task_checklist_items" add constraint "task_checklist_items_label_not_blank" CHECK ((btrim(label) <> ''::text)) not valid;

alter table "public"."task_checklist_items" validate constraint "task_checklist_items_label_not_blank";

alter table "public"."task_checklist_items" add constraint "task_checklist_items_task_id_fkey" FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE RESTRICT not valid;

alter table "public"."task_checklist_items" validate constraint "task_checklist_items_task_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.refresh_checklist_counters(p_task_id bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
    update public.tasks t
       set checklist_total = c.total,
           checklist_done  = c.done
      from (
        select count(*) as total,
               count(*) filter (where is_done) as done
          from public.task_checklist_items
         where task_id = p_task_id
           and deleted_at is null
      ) c
     where t.id = p_task_id
       and (t.checklist_total, t.checklist_done) is distinct from (c.total, c.done);
end;
$function$
;

CREATE OR REPLACE FUNCTION public.task_checklist_items_audit()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
    v_actor bigint := (select public.current_sale_id());
    v_type  public.task_event_type;
begin
    if tg_op = 'INSERT' then
        v_type := 'checklist.item_added';
    elsif old.deleted_at is null and new.deleted_at is not null then
        v_type := 'checklist.item_removed';
    elsif new.is_done is distinct from old.is_done then
        v_type := case when new.is_done then 'checklist.item_completed'
                       else 'checklist.item_reopened' end;
    elsif new.position is distinct from old.position then
        v_type := 'checklist.item_reordered';
    elsif new.label is distinct from old.label then
        -- A relabelled step is a content change, recorded as an add of the new
        -- text; there is no dedicated event type for it in the enum (§5.2).
        v_type := 'checklist.item_added';
    else
        -- Nothing worth a line in the timeline (an assignee or due-date tweak).
        perform public.refresh_checklist_counters(new.task_id);
        return new;
    end if;

    perform public.emit_task_event(
        new.task_id, v_type, coalesce(v_actor, new.created_by), null, null,
        jsonb_build_object('item_id', new.id, 'label', new.label),
        null,
        case when coalesce(v_actor, new.created_by) is null then 'system' else 'user' end
    );

    perform public.refresh_checklist_counters(new.task_id);

    return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.task_checklist_items_before_insert()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
    new.created_by := coalesce((select public.current_sale_id()), new.created_by);

    if new.position is null then
        select coalesce(max(position), 0) + 1 into new.position
          from public.task_checklist_items
         where task_id = new.task_id
           and deleted_at is null;
    end if;

    -- An item created already ticked still needs its attribution.
    if new.is_done and new.done_at is null then
        new.done_at := now();
        new.done_by := coalesce(new.done_by, new.created_by);
    end if;

    return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.task_checklist_items_before_update()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
    v_actor bigint := (select public.current_sale_id());
begin
    if new.is_done is distinct from old.is_done then
        if new.is_done then
            new.done_at := now();
            new.done_by := coalesce(v_actor, old.created_by);
        else
            new.done_at := null;
            new.done_by := null;
        end if;
    end if;

    new.task_id    := old.task_id;
    new.created_at := old.created_at;

    return new;
end;
$function$
;

--
-- Row level security (§11)
--

  create policy "Checklist items are readable with their task"
  on "public"."task_checklist_items"
  as permissive
  for select
  to authenticated
using (public.can_see_task(task_id));



  create policy "Checklist items are updated by users who can see the task"
  on "public"."task_checklist_items"
  as permissive
  for update
  to authenticated
using (public.can_see_task(task_id))
with check (public.can_see_task(task_id));



  create policy "Checklist items are written by users who can see the task"
  on "public"."task_checklist_items"
  as permissive
  for insert
  to authenticated
with check (public.can_see_task(task_id));


--
-- Triggers
--

CREATE TRIGGER task_checklist_items_audit AFTER INSERT OR UPDATE ON public.task_checklist_items FOR EACH ROW EXECUTE FUNCTION public.task_checklist_items_audit();

CREATE TRIGGER task_checklist_items_before_insert BEFORE INSERT ON public.task_checklist_items FOR EACH ROW EXECUTE FUNCTION public.task_checklist_items_before_insert();

CREATE TRIGGER task_checklist_items_before_update BEFORE UPDATE ON public.task_checklist_items FOR EACH ROW EXECUTE FUNCTION public.task_checklist_items_before_update();


--
-- Grants (§17.3 P1). No `delete`: removal is a soft delete via update.
--
grant select, insert, update on table "public"."task_checklist_items" to "authenticated";
grant all on table "public"."task_checklist_items" to "service_role";
revoke all on table "public"."task_checklist_items" from "anon";

grant usage, select on sequence "public"."task_checklist_items_id_seq" to "authenticated";
grant all on sequence "public"."task_checklist_items_id_seq" to "service_role";

grant all on function "public"."refresh_checklist_counters"(bigint) to "service_role";
grant all on function "public"."task_checklist_items_before_insert"() to "service_role";
grant all on function "public"."task_checklist_items_before_update"() to "service_role";
grant all on function "public"."task_checklist_items_audit"() to "service_role";
