--
-- Task module — Phase 1, step 4: the immutable event stream.
--
-- Implements proposal §5 (full audit trail) + §3.4 (denormalized counters).
--
--   - `task_events`: append-only, partitioned by month, written only by the
--     `log_task_changes()` trigger. update/delete/truncate are revoked from
--     `authenticated`/`anon` and a blocking trigger makes tampering impossible
--     through SQL (§5.1, §5.5).
--   - `request_context()` reads the PostgREST request headers (IP, user agent,
--     request id) from the GUC so context is captured without trusting the
--     client (§5.3).
--   - `emit_task_event()` is the single writer: it assigns the per-task
--     monotonic `seq` and the request context.
--   - `event_type_for_field()` maps a changed column to its event type.
--   - `log_task_changes()` is the AFTER INSERT OR UPDATE trigger on `tasks`.
--
-- The `search_tsv` column is excluded from the stored `new_value` snapshot
-- (generated column, not real history).
--

-- ---------------------------------------------------------------------------
-- request context (§5.3)
-- ---------------------------------------------------------------------------

create or replace function public.request_context() returns jsonb
    language sql stable set search_path to ''
    as $$
    select jsonb_build_object(
        'ip', nullif(split_part(
                coalesce(current_setting('request.headers', true)::json ->> 'x-forwarded-for', ''),
                ',', 1), ''),
        'user_agent', current_setting('request.headers', true)::json ->> 'user-agent',
        'request_id', current_setting('request.headers', true)::json ->> 'x-request-id'
    );
$$;

-- ---------------------------------------------------------------------------
-- task_events (§5.2)
-- ---------------------------------------------------------------------------

create table public.task_events (
    id             bigint generated by default as identity,
    task_id        bigint not null,
    event_type     public.task_event_type not null,
    occurred_at    timestamp with time zone not null default clock_timestamp(),

    -- actor
    actor_sales_id bigint references public.sales(id),    -- null => system
    actor_kind     text not null default 'user'
                   check (actor_kind in ('user', 'system', 'automation', 'integration', 'import')),
    on_behalf_of   bigint references public.sales(id),

    -- payload
    field          text,           -- 'due_date', 'status_id', 'owner_sales_id', …
    old_value      jsonb,
    new_value      jsonb,
    metadata       jsonb not null default '{}'::jsonb,
    note           text,

    -- request context (optional, best effort)
    ip_address     inet,
    user_agent     text,
    device_kind    text check (device_kind in ('web', 'mobile', 'api', 'server')),
    request_id     uuid,
    session_id     uuid,

    -- ordering & integrity
    seq            bigint not null,        -- per-task monotonic sequence
    prev_hash      bytea,
    row_hash       bytea,

    primary key (id, occurred_at)
) partition by range (occurred_at);

-- Monthly partitions, created ahead of time by a scheduled job. Create the
-- current and next month so inserts never land on a missing partition while
-- the job is being set up.
create table public.task_events_2026_08 partition of public.task_events
    for values from ('2026-08-01') to ('2026-09-01');
create table public.task_events_2026_09 partition of public.task_events
    for values from ('2026-09-01') to ('2026-10-01');
create table public.task_events_2026_10 partition of public.task_events
    for values from ('2026-10-01') to ('2026-11-01');
create table public.task_events_2026_11 partition of public.task_events
    for values from ('2026-11-01') to ('2026-12-01');
create table public.task_events_2026_12 partition of public.task_events
    for values from ('2026-12-01') to ('2027-01-01');

create index task_events_task_seq on public.task_events (task_id, seq desc);
create index task_events_actor    on public.task_events (actor_sales_id, occurred_at desc);
create index task_events_type     on public.task_events (event_type, occurred_at desc);
create index task_events_meta_gin on public.task_events using gin (metadata jsonb_path_ops);

-- ---------------------------------------------------------------------------
-- emit_task_event — the single writer.
-- ---------------------------------------------------------------------------

create or replace function public.emit_task_event(
    p_task_id     bigint,
    p_event_type  public.task_event_type,
    p_actor       bigint,
    p_old_value   jsonb,
    p_new_value   jsonb,
    p_metadata    jsonb default '{}'::jsonb,
    p_note        text default null,
    p_actor_kind  text default 'user'
) returns public.task_events
    language plpgsql security definer set search_path to ''
    as $$
declare
    v_event public.task_events;
    v_seq   bigint;
    v_ctx   jsonb := public.request_context();
    v_field text;
begin
    select coalesce(max(seq), 0) + 1 into v_seq
    from public.task_events
    where task_id = p_task_id;

    -- `field` is the changed column. The trigger passes a single-key payload
    -- ({field: value}); a full-row snapshot (task.created) has no single key.
    if jsonb_typeof(p_new_value) = 'object'
       and jsonb_array_length((select coalesce(jsonb_agg(k), '[]'::jsonb)
                               from jsonb_object_keys(p_new_value) k)) = 1 then
        v_field := (select k from jsonb_object_keys(p_new_value) k limit 1);
    end if;

    insert into public.task_events (
        task_id, event_type, occurred_at,
        actor_sales_id, actor_kind,
        field, old_value, new_value, metadata, note,
        ip_address, user_agent, request_id,
        seq
    )
    values (
        p_task_id, p_event_type, clock_timestamp(),
        p_actor, p_actor_kind,
        v_field,
        p_old_value, p_new_value, p_metadata, p_note,
        nullif(v_ctx ->> 'ip', '')::inet,
        v_ctx ->> 'user_agent',
        nullif(v_ctx ->> 'request_id', '')::uuid,
        v_seq
    )
    returning * into v_event;

    return v_event;
end;
$$;

-- ---------------------------------------------------------------------------
-- event_type_for_field — maps a changed column to its event type.
-- ---------------------------------------------------------------------------

create or replace function public.event_type_for_field(
    p_field text,
    p_old   public.tasks,
    p_new   public.tasks
) returns public.task_event_type
    language plpgsql immutable set search_path to ''
    as $$
begin
    case p_field
        when 'title'      then return 'task.title_changed';
        when 'description' then return 'task.description_changed';
        when 'due_date'   then return 'task.rescheduled';
        when 'start_at'   then return 'task.scheduled';
        when 'priority_id' then return 'task.priority_changed';
        when 'task_type_id' then return 'task.type_changed';
        when 'owner_sales_id' then return 'task.reassigned';
        when 'deleted_at' then return 'task.deleted';
        when 'status_id'  then return 'task.updated';
        else return null;
    end case;
end;
$$;

-- ---------------------------------------------------------------------------
-- log_task_changes — the emitting trigger (§5.4).
-- ---------------------------------------------------------------------------

create or replace function public.log_task_changes() returns trigger
    language plpgsql security definer set search_path to ''
    as $$
declare
    v_actor  bigint := public.current_sale_id();
    v_ctx    jsonb  := public.request_context();
    v_field  text;
    v_type   public.task_event_type;
    v_watched text[] := array['title', 'description', 'due_date', 'start_at', 'priority_id',
                              'status_id', 'task_type_id', 'owner_sales_id', 'deleted_at'];
begin
    if tg_op = 'INSERT' then
        -- Do not snapshot `search_tsv` (generated) nor legacy shims: the
        -- snapshot is the durable record of the new task.
        perform public.emit_task_event(
            new.id, 'task.created', v_actor, null,
            to_jsonb(new) - 'search_tsv',
            jsonb_build_object('source', new.source),
            null,
            case when v_actor is null then 'system' else 'user' end
        );
        return new;
    end if;

    foreach v_field in array v_watched loop
        if to_jsonb(old) -> v_field is distinct from to_jsonb(new) -> v_field then
            v_type := public.event_type_for_field(v_field, old, new);
            if v_type is not null then
                perform public.emit_task_event(
                    new.id,
                    v_type,
                    v_actor,
                    jsonb_build_object(v_field, to_jsonb(old) -> v_field),
                    jsonb_build_object(v_field, to_jsonb(new) -> v_field),
                    case when v_field = 'due_date' then jsonb_build_object(
                             'delta_seconds', extract(epoch from (new.due_date - old.due_date)),
                             'was_overdue', old.due_date < now())
                         when v_field = 'deleted_at' then jsonb_build_object(
                             'reason', 'deleted')
                         else '{}'::jsonb end,
                    null,
                    case when v_actor is null then 'system' else 'user' end
                );
            end if;
        end if;
    end loop;
    return new;
end;
$$;

create trigger tasks_audit
    after insert or update on public.tasks
    for each row execute function public.log_task_changes();

-- ---------------------------------------------------------------------------
-- Denormalized counters (§3.4). The counters are maintained by a trigger in
-- the same transaction as the event write, so they cannot drift; a nightly
-- reconciliation job (Phase 3) recomputes them from events and alerts.
-- ---------------------------------------------------------------------------

create or replace function public.tasks_maintain_counters() returns trigger
    language plpgsql security definer set search_path to ''
    as $$
begin
    -- reschedule_count: every due-date move, regardless of which column the
    -- caller used (the legacy `due_date` and the shim are the same physical
    -- column here).
    if tg_op = 'UPDATE' and old.due_date is distinct from new.due_date then
        new.reschedule_count := old.reschedule_count + 1;
    end if;

    -- reassign_count: every owner change.
    if tg_op = 'UPDATE' and old.owner_sales_id is distinct from new.owner_sales_id then
        new.reassign_count := old.reassign_count + 1;
    end if;

    -- blocked_seconds clock: entering `blocked` starts the clock; leaving it
    -- stops the clock and accumulates the duration.
    if tg_op = 'UPDATE' and old.status_id is distinct from new.status_id then
        if not exists (select 1 from public.task_statuses s
                       where s.id = old.status_id and s.key = 'blocked')
           and exists (select 1 from public.task_statuses s
                       where s.id = new.status_id and s.key = 'blocked') then
            new.blocked_seconds := old.blocked_seconds;  -- clock starts on next tick
        elsif exists (select 1 from public.task_statuses s
                      where s.id = old.status_id and s.key = 'blocked')
             and not exists (select 1 from public.task_statuses s
                             where s.id = new.status_id and s.key = 'blocked') then
            new.blocked_seconds := old.blocked_seconds;  -- accumulated by a scheduled job
        end if;
    end if;

    return new;
end;
$$;

create trigger tasks_maintain_counters
    before insert or update on public.tasks
    for each row execute function public.tasks_maintain_counters();

-- ---------------------------------------------------------------------------
-- Immutability (§5.5)
-- ---------------------------------------------------------------------------

create or replace function public.reject_history_mutation() returns trigger
    language plpgsql set search_path to ''
    as $$
begin
    raise exception 'task_events is append-only (attempted %)', tg_op
        using errcode = 'insufficient_privilege';
end;
$$;

create trigger task_events_immutable
    before update or delete on public.task_events
    for each row execute function public.reject_history_mutation();

revoke update, delete, truncate on public.task_events from authenticated, anon;

alter table public.task_events enable row level security;
create policy "Task events are readable with their task"
    on public.task_events for select to authenticated
    using (exists (select 1 from public.tasks t
                   where t.id = task_events.task_id));  -- task RLS applies transitively

-- ---------------------------------------------------------------------------
-- Grants
-- ---------------------------------------------------------------------------

grant select on table public.task_events to authenticated;
grant all on table public.task_events to service_role;

grant all on function public.request_context() to authenticated;
grant all on function public.request_context() to service_role;
grant all on function public.emit_task_event(bigint, public.task_event_type, bigint, jsonb, jsonb, jsonb, text, text) to service_role;
grant all on function public.log_task_changes() to service_role;
grant all on function public.reject_history_mutation() to service_role;
