-- Task module — collaboration: comments, revisions, mentions, reactions (§8).
--
-- Phase 2.1/2.2 of docs/proposals/enterprise-task-module.md. Comments are the
-- first collaboration primitive: coordination that used to happen in a chat
-- tool becomes part of the task's own audit trail.


  create table "public"."task_comment_mentions" (
    "id" bigint generated by default as identity not null,
    "comment_id" bigint not null,
    "mentioned_sales_id" bigint,
    "mentioned_team_id" bigint,
    "notified_at" timestamp with time zone,
    "read_at" timestamp with time zone
      );


alter table "public"."task_comment_mentions" enable row level security;


  create table "public"."task_comment_reactions" (
    "comment_id" bigint not null,
    "sales_id" bigint not null,
    "emoji" text not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."task_comment_reactions" enable row level security;


  create table "public"."task_comment_revisions" (
    "id" bigint generated by default as identity not null,
    "comment_id" bigint not null,
    "body" text not null,
    "edited_by" bigint not null,
    "edited_at" timestamp with time zone not null default now(),
    "revision" integer not null
      );


alter table "public"."task_comment_revisions" enable row level security;


  create table "public"."task_comments" (
    "id" bigint generated by default as identity not null,
    "task_id" bigint not null,
    "parent_id" bigint,
    "author_id" bigint not null,
    "body" text not null,
    "is_private" boolean not null default false,
    "edited_at" timestamp with time zone,
    "edit_count" integer not null default 0,
    "deleted_at" timestamp with time zone,
    "deleted_by" bigint,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."task_comments" enable row level security;

CREATE INDEX task_comment_mentions_inbox ON public.task_comment_mentions USING btree (mentioned_sales_id, read_at);

CREATE UNIQUE INDEX task_comment_mentions_pkey ON public.task_comment_mentions USING btree (id);

CREATE UNIQUE INDEX task_comment_mentions_unique_sale ON public.task_comment_mentions USING btree (comment_id, mentioned_sales_id) WHERE (mentioned_sales_id IS NOT NULL);

CREATE UNIQUE INDEX task_comment_mentions_unique_team ON public.task_comment_mentions USING btree (comment_id, mentioned_team_id) WHERE (mentioned_team_id IS NOT NULL);

CREATE UNIQUE INDEX task_comment_reactions_pkey ON public.task_comment_reactions USING btree (comment_id, sales_id, emoji);

CREATE UNIQUE INDEX task_comment_revisions_comment_id_revision_key ON public.task_comment_revisions USING btree (comment_id, revision);

CREATE UNIQUE INDEX task_comment_revisions_pkey ON public.task_comment_revisions USING btree (id);

CREATE UNIQUE INDEX task_comments_pkey ON public.task_comments USING btree (id);

CREATE INDEX task_comments_task ON public.task_comments USING btree (task_id, created_at) WHERE (deleted_at IS NULL);

CREATE INDEX task_comments_thread ON public.task_comments USING btree (parent_id, created_at) WHERE (deleted_at IS NULL);

alter table "public"."task_comment_mentions" add constraint "task_comment_mentions_pkey" PRIMARY KEY using index "task_comment_mentions_pkey";

alter table "public"."task_comment_reactions" add constraint "task_comment_reactions_pkey" PRIMARY KEY using index "task_comment_reactions_pkey";

alter table "public"."task_comment_revisions" add constraint "task_comment_revisions_pkey" PRIMARY KEY using index "task_comment_revisions_pkey";

alter table "public"."task_comments" add constraint "task_comments_pkey" PRIMARY KEY using index "task_comments_pkey";

alter table "public"."task_comment_mentions" add constraint "mention_subject" CHECK ((num_nonnulls(mentioned_sales_id, mentioned_team_id) = 1)) not valid;

alter table "public"."task_comment_mentions" validate constraint "mention_subject";

alter table "public"."task_comment_mentions" add constraint "task_comment_mentions_comment_id_fkey" FOREIGN KEY (comment_id) REFERENCES public.task_comments(id) ON DELETE CASCADE not valid;

alter table "public"."task_comment_mentions" validate constraint "task_comment_mentions_comment_id_fkey";

alter table "public"."task_comment_mentions" add constraint "task_comment_mentions_mentioned_sales_id_fkey" FOREIGN KEY (mentioned_sales_id) REFERENCES public.sales(id) not valid;

alter table "public"."task_comment_mentions" validate constraint "task_comment_mentions_mentioned_sales_id_fkey";

alter table "public"."task_comment_mentions" add constraint "task_comment_mentions_mentioned_team_id_fkey" FOREIGN KEY (mentioned_team_id) REFERENCES public.teams(id) not valid;

alter table "public"."task_comment_mentions" validate constraint "task_comment_mentions_mentioned_team_id_fkey";

alter table "public"."task_comment_reactions" add constraint "task_comment_reactions_comment_id_fkey" FOREIGN KEY (comment_id) REFERENCES public.task_comments(id) ON DELETE CASCADE not valid;

alter table "public"."task_comment_reactions" validate constraint "task_comment_reactions_comment_id_fkey";

alter table "public"."task_comment_reactions" add constraint "task_comment_reactions_sales_id_fkey" FOREIGN KEY (sales_id) REFERENCES public.sales(id) not valid;

alter table "public"."task_comment_reactions" validate constraint "task_comment_reactions_sales_id_fkey";

alter table "public"."task_comment_revisions" add constraint "task_comment_revisions_comment_id_fkey" FOREIGN KEY (comment_id) REFERENCES public.task_comments(id) ON DELETE RESTRICT not valid;

alter table "public"."task_comment_revisions" validate constraint "task_comment_revisions_comment_id_fkey";

alter table "public"."task_comment_revisions" add constraint "task_comment_revisions_comment_id_revision_key" UNIQUE using index "task_comment_revisions_comment_id_revision_key";

alter table "public"."task_comment_revisions" add constraint "task_comment_revisions_edited_by_fkey" FOREIGN KEY (edited_by) REFERENCES public.sales(id) not valid;

alter table "public"."task_comment_revisions" validate constraint "task_comment_revisions_edited_by_fkey";

alter table "public"."task_comments" add constraint "task_comments_author_id_fkey" FOREIGN KEY (author_id) REFERENCES public.sales(id) not valid;

alter table "public"."task_comments" validate constraint "task_comments_author_id_fkey";

alter table "public"."task_comments" add constraint "task_comments_body_not_blank" CHECK ((btrim(body) <> ''::text)) not valid;

alter table "public"."task_comments" validate constraint "task_comments_body_not_blank";

alter table "public"."task_comments" add constraint "task_comments_deleted_by_fkey" FOREIGN KEY (deleted_by) REFERENCES public.sales(id) not valid;

alter table "public"."task_comments" validate constraint "task_comments_deleted_by_fkey";

alter table "public"."task_comments" add constraint "task_comments_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES public.task_comments(id) not valid;

alter table "public"."task_comments" validate constraint "task_comments_parent_id_fkey";

alter table "public"."task_comments" add constraint "task_comments_task_id_fkey" FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE RESTRICT not valid;

alter table "public"."task_comments" validate constraint "task_comments_task_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.sync_comment_mentions(p_comment_id bigint, p_task_id bigint, p_body text, p_actor bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
    v_sales_ids bigint[];
    v_team_ids  bigint[];
    v_inserted  bigint[];
    v_new_id    bigint;
begin
    select coalesce(array_agg(distinct m[1]::bigint), '{}')
      into v_sales_ids
      from regexp_matches(coalesce(p_body, ''), '\(sales:(\d+)\)', 'g') m;

    select coalesce(array_agg(distinct m[1]::bigint), '{}')
      into v_team_ids
      from regexp_matches(coalesce(p_body, ''), '\(team:(\d+)\)', 'g') m;

    -- Mentions the author removed from the body are no longer mentions.
    delete from public.task_comment_mentions
     where comment_id = p_comment_id
       and (
            (mentioned_sales_id is not null
             and not (mentioned_sales_id = any (v_sales_ids)))
         or (mentioned_team_id is not null
             and not (mentioned_team_id = any (v_team_ids)))
       );

    -- Only real, active people: a stale id in the body must not create an
    -- inbox row nobody can ever read. The insert is drained into an array
    -- before any event is emitted, so the emitting loop never runs while the
    -- insert that feeds it is still in flight.
    with inserted as (
        insert into public.task_comment_mentions (comment_id, mentioned_sales_id)
        select p_comment_id, s.id
          from public.sales s
         where s.id = any (v_sales_ids)
           and s.disabled = false
        on conflict do nothing
        returning mentioned_sales_id
    )
    select coalesce(array_agg(mentioned_sales_id), '{}')
      into v_inserted from inserted;

    foreach v_new_id in array v_inserted loop
        perform public.emit_task_event(
            p_task_id, 'mention.created', p_actor, null, null,
            jsonb_build_object('comment_id', p_comment_id,
                               'mentioned_sales_id', v_new_id),
            null,
            case when p_actor is null then 'system' else 'user' end
        );
    end loop;

    with inserted as (
        insert into public.task_comment_mentions (comment_id, mentioned_team_id)
        select p_comment_id, t.id
          from public.teams t
         where t.id = any (v_team_ids)
        on conflict do nothing
        returning mentioned_team_id
    )
    select coalesce(array_agg(mentioned_team_id), '{}')
      into v_inserted from inserted;

    foreach v_new_id in array v_inserted loop
        perform public.emit_task_event(
            p_task_id, 'mention.created', p_actor, null, null,
            jsonb_build_object('comment_id', p_comment_id,
                               'mentioned_team_id', v_new_id),
            null,
            case when p_actor is null then 'system' else 'user' end
        );
    end loop;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.task_comment_reactions_audit()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
    v_row     public.task_comment_reactions := coalesce(new, old);
    v_task_id bigint;
    v_actor   bigint := (select public.current_sale_id());
begin
    select task_id into v_task_id
      from public.task_comments where id = v_row.comment_id;

    perform public.emit_task_event(
        v_task_id,
        (case when tg_op = 'INSERT' then 'comment.reaction_added'
              else 'comment.reaction_removed' end)::public.task_event_type,
        coalesce(v_actor, v_row.sales_id),
        null, null,
        jsonb_build_object('comment_id', v_row.comment_id, 'emoji', v_row.emoji),
        null,
        case when coalesce(v_actor, v_row.sales_id) is null then 'system' else 'user' end
    );

    return v_row;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.task_comment_reactions_set_sale()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
    new.sales_id := coalesce((select public.current_sale_id()), new.sales_id);
    return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.task_comments_after_insert()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
    update public.tasks
       set comment_count = comment_count + 1
     where id = new.task_id;

    -- The body goes in `note`, not in `new_value`: `emit_task_event` reads a
    -- single-key `new_value` as a field-level diff, and a comment is not one.
    perform public.emit_task_event(
        new.task_id, 'comment.created', new.author_id, null, null,
        jsonb_build_object('comment_id', new.id,
                           'parent_id', new.parent_id,
                           'is_private', new.is_private),
        left(new.body, 500),
        case when new.author_id is null then 'system' else 'user' end
    );

    perform public.sync_comment_mentions(new.id, new.task_id, new.body, new.author_id);

    return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.task_comments_after_update()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
    v_actor bigint := (select public.current_sale_id());
begin
    if old.deleted_at is null and new.deleted_at is not null then
        update public.tasks
           set comment_count = greatest(comment_count - 1, 0)
         where id = new.task_id;

        perform public.emit_task_event(
            new.task_id, 'comment.deleted', coalesce(v_actor, new.deleted_by),
            null, null,
            jsonb_build_object('comment_id', new.id),
            null,
            case when coalesce(v_actor, new.deleted_by) is null then 'system' else 'user' end
        );

    elsif old.deleted_at is not null and new.deleted_at is null then
        update public.tasks
           set comment_count = comment_count + 1
         where id = new.task_id;
    end if;

    if new.body is distinct from old.body then
        -- A single-key old/new pair renders as a before/after diff in the
        -- history tab, which is exactly what "ver cambios" needs to show.
        perform public.emit_task_event(
            new.task_id, 'comment.edited', coalesce(v_actor, new.author_id),
            jsonb_build_object('body', old.body),
            jsonb_build_object('body', new.body),
            jsonb_build_object('comment_id', new.id, 'revision', new.edit_count),
            null,
            case when v_actor is null then 'system' else 'user' end
        );

        perform public.sync_comment_mentions(
            new.id, new.task_id, new.body, coalesce(v_actor, new.author_id));
    end if;

    return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.task_comments_before_insert()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
    v_grandparent bigint;
    v_parent_task bigint;
begin
    new.author_id := coalesce((select public.current_sale_id()), new.author_id);

    if new.parent_id is not null then
        select parent_id, task_id into v_grandparent, v_parent_task
          from public.task_comments
         where id = new.parent_id;

        if v_parent_task is distinct from new.task_id then
            raise exception 'comment % belongs to another task', new.parent_id
                using errcode = 'check_violation';
        end if;

        new.parent_id := coalesce(v_grandparent, new.parent_id);
    end if;

    return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.task_comments_before_update()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
    v_actor bigint := (select public.current_sale_id());
begin
    if new.body is distinct from old.body then
        insert into public.task_comment_revisions (comment_id, body, edited_by, revision)
        values (old.id, old.body, coalesce(v_actor, old.author_id), old.edit_count + 1);

        new.edit_count := old.edit_count + 1;
        new.edited_at  := now();
    end if;

    if old.deleted_at is null and new.deleted_at is not null then
        new.deleted_by := coalesce(v_actor, new.deleted_by);
    end if;

    -- Authorship and the creation date are not editable, whatever the client
    -- sends: they are the two facts the whole audit trail hangs off.
    new.author_id  := old.author_id;
    new.created_at := old.created_at;
    new.task_id    := old.task_id;

    return new;
end;
$function$
;

--
-- Row level security (§8.2)
--

  create policy "Mentions are readable with their comment"
  on "public"."task_comment_mentions"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.task_comments c
  WHERE (c.id = task_comment_mentions.comment_id))));



  create policy "You mark your own mentions as read"
  on "public"."task_comment_mentions"
  as permissive
  for update
  to authenticated
using ((mentioned_sales_id = ( SELECT public.current_sale_id() AS current_sale_id)))
with check ((mentioned_sales_id = ( SELECT public.current_sale_id() AS current_sale_id)));



  create policy "Reactions are readable with their comment"
  on "public"."task_comment_reactions"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.task_comments c
  WHERE (c.id = task_comment_reactions.comment_id))));



  create policy "You add your own reactions"
  on "public"."task_comment_reactions"
  as permissive
  for insert
  to authenticated
with check (((sales_id = ( SELECT public.current_sale_id() AS current_sale_id)) AND (EXISTS ( SELECT 1
   FROM public.task_comments c
  WHERE (c.id = task_comment_reactions.comment_id)))));



  create policy "You remove your own reactions"
  on "public"."task_comment_reactions"
  as permissive
  for delete
  to authenticated
using ((sales_id = ( SELECT public.current_sale_id() AS current_sale_id)));



  create policy "Comment revisions are readable with their comment"
  on "public"."task_comment_revisions"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.task_comments c
  WHERE (c.id = task_comment_revisions.comment_id))));



  create policy "Comments are edited by their author or a manager"
  on "public"."task_comments"
  as permissive
  for update
  to authenticated
using (((author_id = ( SELECT public.current_sale_id() AS current_sale_id)) OR ( SELECT public.can_manage_all() AS can_manage_all)))
with check (((author_id = ( SELECT public.current_sale_id() AS current_sale_id)) OR ( SELECT public.can_manage_all() AS can_manage_all)));



  create policy "Comments are readable with their task"
  on "public"."task_comments"
  as permissive
  for select
  to authenticated
using ((public.can_see_task(task_id) AND ((is_private = false) OR (author_id = ( SELECT public.current_sale_id() AS current_sale_id)) OR ( SELECT public.can_manage_all() AS can_manage_all))));



  create policy "Comments are written by users who can see the task"
  on "public"."task_comments"
  as permissive
  for insert
  to authenticated
with check (public.can_see_task(task_id));


--
-- Triggers
--

CREATE TRIGGER task_comment_reactions_audit AFTER INSERT OR DELETE ON public.task_comment_reactions FOR EACH ROW EXECUTE FUNCTION public.task_comment_reactions_audit();

CREATE TRIGGER task_comment_reactions_set_sale BEFORE INSERT ON public.task_comment_reactions FOR EACH ROW EXECUTE FUNCTION public.task_comment_reactions_set_sale();

CREATE TRIGGER task_comment_revisions_immutable BEFORE DELETE OR UPDATE ON public.task_comment_revisions FOR EACH ROW EXECUTE FUNCTION public.reject_history_mutation();

CREATE TRIGGER task_comments_after_insert AFTER INSERT ON public.task_comments FOR EACH ROW EXECUTE FUNCTION public.task_comments_after_insert();

CREATE TRIGGER task_comments_after_update AFTER UPDATE ON public.task_comments FOR EACH ROW EXECUTE FUNCTION public.task_comments_after_update();

CREATE TRIGGER task_comments_before_insert BEFORE INSERT ON public.task_comments FOR EACH ROW EXECUTE FUNCTION public.task_comments_before_insert();

CREATE TRIGGER task_comments_before_update BEFORE UPDATE ON public.task_comments FOR EACH ROW EXECUTE FUNCTION public.task_comments_before_update();



--
-- Grants (§17.3 P1)
--
-- No `delete` on comments: deletion is a soft delete performed as an update, so
-- the body survives for the audit view. Revisions and mentions are written by
-- SECURITY DEFINER triggers, so `authenticated` only reads them.
--
grant select, insert, update on table "public"."task_comments" to "authenticated";
grant all on table "public"."task_comments" to "service_role";

grant select on table "public"."task_comment_revisions" to "authenticated";
grant all on table "public"."task_comment_revisions" to "service_role";

grant select, update on table "public"."task_comment_mentions" to "authenticated";
grant all on table "public"."task_comment_mentions" to "service_role";

grant select, insert, delete on table "public"."task_comment_reactions" to "authenticated";
grant all on table "public"."task_comment_reactions" to "service_role";

-- `alter default privileges` hands `anon` every new table in the schema. RLS
-- already refuses anon, but §17.3 P1 asks for no anon grants on task tables.
revoke all on table "public"."task_comments" from "anon";
revoke all on table "public"."task_comment_revisions" from "anon";
revoke all on table "public"."task_comment_mentions" from "anon";
revoke all on table "public"."task_comment_reactions" from "anon";

grant usage, select on sequence "public"."task_comments_id_seq" to "authenticated";
grant all on sequence "public"."task_comments_id_seq" to "service_role";
grant all on sequence "public"."task_comment_revisions_id_seq" to "service_role";
grant all on sequence "public"."task_comment_mentions_id_seq" to "service_role";

grant all on function "public"."sync_comment_mentions"(bigint, bigint, text, bigint) to "service_role";
grant all on function "public"."task_comments_before_insert"() to "service_role";
grant all on function "public"."task_comments_after_insert"() to "service_role";
grant all on function "public"."task_comments_before_update"() to "service_role";
grant all on function "public"."task_comments_after_update"() to "service_role";
grant all on function "public"."task_comment_reactions_set_sale"() to "service_role";
grant all on function "public"."task_comment_reactions_audit"() to "service_role";
