--
-- Task module — Phase 1, step 6: the state machine.
--
-- Implements proposal §4: `task_transitions` (the transition table), the
-- `transition_task()` function as the ONLY write path for status changes, and
-- a BEFORE UPDATE guard trigger that rejects any direct `status_id` change.
--
-- The guard uses a transaction-local GUC: `transition_task()` sets
-- `app.task_transition_to` right before its own UPDATE, the trigger checks it
-- and clears it. Any other path (REST, edge function, psql) is rejected with
-- a clear error — the transition rules cannot be bypassed (§4.5).
--

-- ---------------------------------------------------------------------------
-- task_transitions
-- ---------------------------------------------------------------------------

create table public.task_transitions (
    id              bigint generated by default as identity primary key,
    from_status_key text not null,
    to_status_key   text not null,
    label           text,
    requires_reason boolean not null default false,
    is_system       boolean not null default false,
    unique (from_status_key, to_status_key)
);

-- §4.2 state machine, one row per allowed edge.
insert into public.task_transitions (from_status_key, to_status_key, label, requires_reason, is_system) values
    ('pending',      'scheduled',   'schedule',  false, true),
    ('scheduled',    'pending',     'unschedule', false, true),
    ('pending',      'in_progress', 'start',     false, true),
    ('scheduled',    'in_progress', 'start',     false, true),
    ('in_progress',  'waiting',     'wait',      false, true),
    ('waiting',      'in_progress', 'resume',    false, true),
    ('in_progress',  'blocked',     'block',     false, true),
    ('pending',      'blocked',     'block',     false, true),
    ('blocked',      'in_progress', 'unblock',   false, true),
    ('blocked',      'pending',     'unblock',   false, true),
    ('in_progress',  'completed',   'complete',  false, true),
    ('pending',      'completed',   'complete (quick-check)', false, true),
    ('scheduled',    'completed',   'complete',  false, true),
    ('waiting',      'completed',   'complete',  false, true),
    ('pending',      'canceled',    'cancel',    true,  true),
    ('scheduled',    'canceled',    'cancel',    true,  true),
    ('in_progress',  'canceled',    'cancel',    true,  true),
    ('waiting',      'canceled',    'cancel',    true,  true),
    ('blocked',      'canceled',    'cancel',    true,  true),
    ('completed',    'in_progress', 'reopen',    true,  true),
    ('canceled',     'pending',     'reopen',    true,  true),
    ('completed',    'archived',    'archive',   false, true),
    ('canceled',     'archived',    'archive',   false, true),
    ('archived',     'pending',     'unarchive', false, true),
    -- `rescheduled` is a marker, not a resting state (§4.3), but orgs may want
    -- an explicit "parked" bucket; the edges are kept open.
    ('pending',      'rescheduled', 'mark rescheduled', false, false),
    ('scheduled',    'rescheduled', 'mark rescheduled', false, false),
    ('in_progress',  'rescheduled', 'mark rescheduled', false, false),
    ('rescheduled',  'pending',     're-plan',   false, false),
    ('rescheduled',  'scheduled',   're-plan',   false, false),
    ('rescheduled',  'in_progress', 're-plan',   false, false);

-- ---------------------------------------------------------------------------
-- transition_task — the only write path for status changes.
-- ---------------------------------------------------------------------------

create or replace function public.transition_task(
    p_task_id   bigint,
    p_to_status text,
    p_reason    text default null,
    p_metadata  jsonb default '{}'::jsonb
) returns public.tasks
    language plpgsql security definer set search_path to ''
    as $$
declare
    v_task      public.tasks;
    v_from      text;
    v_actor     bigint := public.current_sale_id();
    v_status_id bigint;
    v_event     public.task_event_type;
    v_meta      jsonb := p_metadata;
begin
    select * into v_task from public.tasks where id = p_task_id for update;
    if not found then
        raise exception 'task % not found or not visible', p_task_id
            using errcode = 'no_data_found';
    end if;

    select key into v_from from public.task_statuses where id = v_task.status_id;

    if not exists (select 1 from public.task_transitions
                   where from_status_key = v_from and to_status_key = p_to_status) then
        raise exception 'illegal transition % -> %', v_from, p_to_status
            using errcode = 'check_violation';
    end if;

    if p_to_status in ('canceled') and coalesce(p_reason, '') = '' then
        raise exception 'a reason is required to cancel a task'
            using errcode = 'check_violation';
    end if;

    -- Capabilities (§17.1): owner / collaborator / manager may transition.
    -- Cancellation additionally requires the owner (or a manager), never a
    -- mere collaborator. `can_manage_all()` covers admins and managers.
    if not (select public.can_manage_all())
       and not exists (select 1 from public.task_assignments a
                       where a.task_id = v_task.id and a.unassigned_at is null
                         and a.sales_id = v_actor
                         and a.role in ('owner', 'collaborator'))
       and v_task.created_by <> v_actor then
        raise exception 'no permission to transition task %', p_task_id
            using errcode = 'insufficient_privilege';
    end if;

    if p_to_status = 'canceled'
       and not (select public.can_manage_all())
       and not exists (select 1 from public.task_assignments a
                       where a.task_id = v_task.id and a.unassigned_at is null
                         and a.sales_id = v_actor and a.role = 'owner')
       and v_task.created_by <> v_actor then
        raise exception 'only the owner or a manager may cancel task %', p_task_id
            using errcode = 'insufficient_privilege';
    end if;

    select id into v_status_id from public.task_statuses where key = p_to_status;

    -- Which event does this transition emit?
    case p_to_status
        when 'completed'   then v_event := 'task.completed';
        when 'canceled'    then v_event := 'task.canceled';
        when 'archived'    then v_event := 'task.archived';
        when 'blocked'     then v_event := 'task.blocked';
        when 'waiting'     then v_event := 'task.waiting';
        when 'rescheduled' then v_event := 'task.rescheduled';
        when 'scheduled'   then v_event := 'task.scheduled';
        else
            if v_from = 'completed' or v_from = 'canceled' then
                v_event := 'task.reopened';
            elsif v_from = 'waiting' then
                v_event := 'task.resumed';
            elsif v_from = 'blocked' then
                v_event := 'task.unblocked';
            else
                v_event := 'task.started';
            end if;
    end case;

    if coalesce(p_reason, '') <> '' then
        v_meta := v_meta || jsonb_build_object('reason', p_reason);
    end if;

    -- The row update. `tasks_keep_legacy_shims` keeps `done_date` in sync with
    -- the completed state, `tasks_maintain_counters` bumps the counters, and
    -- `tasks_audit` emits per-field events. The GUC tells the guard trigger
    -- this status change is legitimate.
    perform set_config('app.task_transition_to', p_to_status, true);

    update public.tasks set
        status_id      = v_status_id,
        completed_at   = case when p_to_status = 'completed' then now() else null end,
        completed_by   = case when p_to_status = 'completed' then v_actor else null end,
        canceled_at    = case when p_to_status = 'canceled' then now() else null end,
        cancel_reason  = case when p_to_status = 'canceled' then p_reason else null end,
        start_at       = case when p_to_status = 'in_progress'
                               and v_task.start_at is null then now()
                          else v_task.start_at end,
        archived_at    = case when p_to_status = 'archived' then now()
                          when v_from = 'archived' then null
                          else v_task.archived_at end
    where id = v_task.id
    returning * into v_task;

    perform set_config('app.task_transition_to', '', false);

    -- The transition's own event, with the reason and the from/to keys.
    perform public.emit_task_event(
        v_task.id,
        v_event,
        v_actor,
        jsonb_build_object('status_id', to_jsonb((select id from public.task_statuses where key = v_from))),
        jsonb_build_object('status_id', to_jsonb(v_status_id)),
        v_meta || jsonb_build_object(
            'from_status', v_from,
            'to_status',   p_to_status
        ),
        p_reason,
        case when v_actor is null then 'system' else 'user' end
    );

    return v_task;
end;
$$;

-- ---------------------------------------------------------------------------
-- Guard: reject any status_id change that did not go through transition_task.
-- ---------------------------------------------------------------------------

create or replace function public.tasks_status_guard() returns trigger
    language plpgsql security definer set search_path to ''
    as $$
begin
    if old.status_id is distinct from new.status_id
       and coalesce(current_setting('app.task_transition_to', true), '') = '' then
        raise exception 'status changes must go through public.transition_task()'
            using errcode = 'check_violation';
    end if;
    return new;
end;
$$;

create trigger tasks_status_guard
    before update on public.tasks
    for each row
    when (old.status_id is distinct from new.status_id)
    execute function public.tasks_status_guard();

-- ---------------------------------------------------------------------------
-- Grants
-- ---------------------------------------------------------------------------

grant all on table public.task_transitions to authenticated;
grant all on table public.task_transitions to service_role;
grant usage, select on sequence public.task_transitions_id_seq to authenticated;

grant all on function public.transition_task(bigint, text, text, jsonb) to authenticated;
grant all on function public.transition_task(bigint, text, text, jsonb) to service_role;
grant all on function public.tasks_status_guard() to service_role;
