-- Task module — dependencies, auto-unblock and the blocked clock (§10).
--
-- Phase 2.6 of docs/proposals/enterprise-task-module.md. Also closes the
-- Phase 1 gap where tasks.blocked_seconds existed but never moved: the
-- trigger deferred the arithmetic to a scheduled job that was never written.
-- Recording blocked_since makes the duration exact with no job at all.

create type "public"."task_dependency_kind" as enum ('blocks', 'parent', 'related', 'duplicates');

drop view if exists "public"."contacts_summary";

drop view if exists "public"."tasks_summary";


  create table "public"."task_dependencies" (
    "id" bigint generated by default as identity not null,
    "source_task_id" bigint not null,
    "target_task_id" bigint not null,
    "kind" public.task_dependency_kind not null,
    "created_by" bigint not null,
    "created_at" timestamp with time zone not null default now(),
    "removed_at" timestamp with time zone,
    "removed_by" bigint
      );


alter table "public"."task_dependencies" enable row level security;

alter table "public"."tasks" add column "blocked_since" timestamp with time zone;

--
-- BOTH summary views were dropped above so the column could be added: they
-- read `public.tasks`, so Postgres refuses the ALTER while they exist.
-- `contacts_summary.nb_tasks` is why the contact list depends on it at all.
-- Recreate both unchanged, with their grants — dropping a view without
-- restoring it takes the whole list page down with a schema-cache miss.
--
create or replace view public.contacts_summary with (security_invoker = on) as
select
    co.id,
    co.first_name,
    co.last_name,
    co.gender,
    co.title,
    co.background,
    co.avatar,
    co.first_seen,
    co.last_seen,
    co.has_newsletter,
    co.status,
    co.tags,
    co.company_id,
    co.sales_id,
    co.linkedin_url,
    co.email_jsonb,
    co.phone_jsonb,
    (jsonb_path_query_array(co.email_jsonb, '$[*]."email"'))::text as email_fts,
    (jsonb_path_query_array(co.phone_jsonb, '$[*]."number"'))::text as phone_fts,
    c.name as company_name,
    -- Same rewrite as companies_summary: the previous join + GROUP BY over
    -- tasks aggregated all 200k contacts before the LIMIT (~1.1 s per page for
    -- a manager). As a subquery, page 1 costs well under a millisecond.
    -- Soft-deleted tasks do not count as open work.
    (select count(*) from public.tasks t
      where t.contact_id = co.id
        and t.done_date is null
        and t.deleted_at is null) as nb_tasks
from public.contacts co
    left join public.companies c on co.company_id = c.id;

--
-- The list/detail projection of a task (proposal §3.4, §15).
--
-- Every task list has to render a status chip, a priority badge, a type icon
-- and the record the task hangs off. Resolving those from the client would be
-- four extra round trips per page; resolving them with a join + GROUP BY would
-- reintroduce exactly the regression documented on `companies_summary`. The
-- catalogues are small, so they are plain joins;
grant all on table public.contacts_summary to anon;
grant all on table public.contacts_summary to authenticated;
grant all on table public.contacts_summary to service_role;

--
-- `tasks_summary` was dropped above so the column could be added; recreate it
-- unchanged, with its grants. `blocked_since` is deliberately NOT exposed: the
-- view serves the list, and the accumulated `blocked_seconds` is what a list
-- renders — the raw clock instant is bookkeeping.
--
create or replace view public.tasks_summary with (security_invoker = on) as
select
    t.id,

    -- content
    t.title,
    t.description,

    -- classification
    t.task_type_id,
    t.status_id,
    t.priority_id,

    -- scheduling
    t.due_date,
    t.start_at,
    t.completed_at,
    t.completed_by,
    t.canceled_at,
    t.cancel_reason,

    -- ownership
    t.owner_sales_id,
    t.created_by,

    -- lifecycle bookkeeping
    t.created_at,
    t.updated_at,
    t.deleted_at,
    t.deleted_by,
    t.archived_at,

    -- traceability counters (§3.4) — what the list badges render
    t.reschedule_count,
    t.reassign_count,
    t.comment_count,
    t.attachment_count,
    t.checklist_total,
    t.checklist_done,
    t.blocked_seconds,
    t.total_open_seconds,
    t.source,

    -- legacy shims: the current frontend still reads these (Appendix C step 7)
    t.contact_id,
    t.text,
    t.type,
    t.done_date,
    t.sales_id,

    -- denormalized catalogues
    s.key as status_key,
    s.label as status_label,
    s.color as status_color,
    s.is_open as status_is_open,
    s.is_terminal as status_is_terminal,
    s.counts_as_done,

    p.key as priority_key,
    p.label as priority_label,
    p.color as priority_color,
    p.rank as priority_rank,
    p.sla_hours,

    ty.key as type_key,
    ty.label as type_label,
    ty.icon as type_icon,

    -- Same reasoning as contacts_summary.company_name: the owner's name is on
    -- every row of every list, so it is resolved once here.
    nullif(btrim(concat_ws(' ', o.first_name, o.last_name)), '') as owner_name,

    -- The primary link drives the breadcrumb and the "regarding" label (§14.2).
    pl.entity_type::text as primary_entity_type,
    pl.entity_id         as primary_entity_id,
    pl.entity_label      as primary_entity_label,

    -- Display-only. Real filtering uses the raw columns so the partial indexes
    -- `tasks_overdue` / `tasks_owner_open_due` still apply (§18.3).
    (t.due_date < now()
     and t.completed_at is null
     and t.canceled_at is null
     and t.deleted_at is null) as is_overdue
from public.tasks t
    join public.task_statuses s on s.id = t.status_id
    join public.task_priorities p on p.id = t.priority_id
    join public.task_types ty on ty.id = t.task_type_id
    left join public.sales o on o.id = t.owner_sales_id
    left join lateral (
        select l.entity_type, l.entity_id, l.entity_label
        from public.task_links l
        where l.task_id = t.id
          and l.is_primary
          and l.unlinked_at is null
        limit 1
    ) pl on true;

grant select on table "public"."tasks_summary" to "authenticated";
grant select on table "public"."tasks_summary" to "service_role";

CREATE UNIQUE INDEX task_dependencies_pkey ON public.task_dependencies USING btree (id);

CREATE INDEX task_dependencies_reverse ON public.task_dependencies USING btree (target_task_id, kind) WHERE (removed_at IS NULL);

CREATE UNIQUE INDEX task_dependencies_unique_active ON public.task_dependencies USING btree (source_task_id, target_task_id, kind) WHERE (removed_at IS NULL);

alter table "public"."task_dependencies" add constraint "task_dependencies_pkey" PRIMARY KEY using index "task_dependencies_pkey";

alter table "public"."task_dependencies" add constraint "no_self_dependency" CHECK ((source_task_id <> target_task_id)) not valid;

alter table "public"."task_dependencies" validate constraint "no_self_dependency";

alter table "public"."task_dependencies" add constraint "task_dependencies_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.sales(id) not valid;

alter table "public"."task_dependencies" validate constraint "task_dependencies_created_by_fkey";

alter table "public"."task_dependencies" add constraint "task_dependencies_removed_by_fkey" FOREIGN KEY (removed_by) REFERENCES public.sales(id) not valid;

alter table "public"."task_dependencies" validate constraint "task_dependencies_removed_by_fkey";

alter table "public"."task_dependencies" add constraint "task_dependencies_source_task_id_fkey" FOREIGN KEY (source_task_id) REFERENCES public.tasks(id) ON DELETE RESTRICT not valid;

alter table "public"."task_dependencies" validate constraint "task_dependencies_source_task_id_fkey";

alter table "public"."task_dependencies" add constraint "task_dependencies_target_task_id_fkey" FOREIGN KEY (target_task_id) REFERENCES public.tasks(id) ON DELETE RESTRICT not valid;

alter table "public"."task_dependencies" validate constraint "task_dependencies_target_task_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.assert_no_dependency_cycle()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
    if new.kind not in ('blocks', 'parent') or new.removed_at is not null then
        return new;
    end if;

    if exists (
        with recursive walk(id, depth) as (
            select new.target_task_id, 1
            union all
            select d.target_task_id, w.depth + 1
              from public.task_dependencies d
              join walk w on d.source_task_id = w.id
             where d.removed_at is null
               and d.kind in ('blocks', 'parent')
               and w.depth < 50
        )
        select 1 from walk where id = new.source_task_id
    ) then
        raise exception 'dependency cycle detected (% -> %)',
              new.source_task_id, new.target_task_id
            using errcode = 'check_violation';
    end if;

    return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.set_task_status_system(p_task_id bigint, p_to_status text, p_event_type public.task_event_type, p_metadata jsonb DEFAULT '{}'::jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
    v_from      text;
    v_status_id bigint;
begin
    select s.key into v_from
      from public.tasks t join public.task_statuses s on s.id = t.status_id
     where t.id = p_task_id;

    select id into v_status_id
      from public.task_statuses where key = p_to_status;

    if v_status_id is null or v_from is null or v_from = p_to_status then
        return;
    end if;

    perform set_config('app.task_transition_to', p_to_status, true);
    update public.tasks set status_id = v_status_id where id = p_task_id;
    perform set_config('app.task_transition_to', '', false);

    perform public.emit_task_event(
        p_task_id, p_event_type, null, null, null,
        p_metadata || jsonb_build_object('from_status', v_from,
                                         'to_status', p_to_status),
        null,
        'system'
    );
end;
$function$
;

CREATE OR REPLACE FUNCTION public.task_dependencies_audit()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
    v_actor bigint := (select public.current_sale_id());
    v_meta  jsonb;
begin
    v_meta := jsonb_build_object(
        'dependency_id', new.id,
        'kind', new.kind,
        'source_task_id', new.source_task_id,
        'target_task_id', new.target_task_id);

    if tg_op = 'INSERT' then
        -- Recorded on BOTH tasks: each timeline should show the relationship.
        perform public.emit_task_event(
            new.target_task_id, 'dependency.added', v_actor, null, null, v_meta, null,
            case when v_actor is null then 'system' else 'user' end);
        perform public.emit_task_event(
            new.source_task_id, 'dependency.added', v_actor, null, null, v_meta, null,
            case when v_actor is null then 'system' else 'user' end);

        if new.kind = 'blocks' and public.task_has_open_blockers(new.target_task_id) then
            perform public.set_task_status_system(
                new.target_task_id, 'blocked', 'task.blocked', v_meta);
        end if;

    elsif old.removed_at is null and new.removed_at is not null then
        perform public.emit_task_event(
            new.target_task_id, 'dependency.removed', v_actor, null, null, v_meta, null,
            case when v_actor is null then 'system' else 'user' end);

        -- Removing the last blocker releases the task, like satisfying it would.
        if new.kind = 'blocks'
           and not public.task_has_open_blockers(new.target_task_id) then
            perform public.set_task_status_system(
                new.target_task_id, 'pending', 'task.unblocked', v_meta);
        end if;
    end if;

    return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.task_dependencies_before_insert()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
    new.created_by := coalesce((select public.current_sale_id()), new.created_by);
    return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.task_has_open_blockers(p_task_id bigint)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
    select exists (
        select 1
          from public.task_dependencies d
          join public.tasks t on t.id = d.source_task_id
          join public.task_statuses s on s.id = t.status_id
         where d.target_task_id = p_task_id
           and d.kind = 'blocks'
           and d.removed_at is null
           and t.deleted_at is null
           and s.is_open
    );
$function$
;

CREATE OR REPLACE FUNCTION public.tasks_unblock_dependents()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
    v_dependent bigint;
    v_was_open  boolean;
    v_is_open   boolean;
begin
    select s.is_open into v_was_open
      from public.task_statuses s where s.id = old.status_id;
    select s.is_open into v_is_open
      from public.task_statuses s where s.id = new.status_id;

    -- Only the open -> closed edge releases anything.
    if not coalesce(v_was_open, false) or coalesce(v_is_open, false) then
        return new;
    end if;

    for v_dependent in
        select d.target_task_id
          from public.task_dependencies d
         where d.source_task_id = new.id
           and d.kind = 'blocks'
           and d.removed_at is null
    loop
        perform public.emit_task_event(
            v_dependent, 'dependency.satisfied', null, null, null,
            jsonb_build_object('source_task_id', new.id), null, 'system');

        -- A task with another open blocker stays blocked; only the last one
        -- to clear actually releases it.
        if not public.task_has_open_blockers(v_dependent) then
            perform public.set_task_status_system(
                v_dependent, 'pending', 'task.unblocked',
                jsonb_build_object('source_task_id', new.id));
        end if;
    end loop;

    return new;
end;
$function$
;

--
-- The blocked clock now accumulates (§10.2).
--
CREATE OR REPLACE FUNCTION public.tasks_maintain_counters()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
    -- reschedule_count: every due-date move, regardless of which column the
    -- caller used (the legacy `due_date` and the shim are the same physical
    -- column here).
    if tg_op = 'UPDATE' and old.due_date is distinct from new.due_date then
        new.reschedule_count := old.reschedule_count + 1;
    end if;

    -- reassign_count: every owner change.
    if tg_op = 'UPDATE' and old.owner_sales_id is distinct from new.owner_sales_id then
        new.reassign_count := old.reassign_count + 1;
    end if;

    -- blocked_seconds clock (§10.2): entering `blocked` records the instant,
    -- leaving it accumulates the elapsed time. Phase 1 deferred this to a
    -- scheduled job that was never written, so the counter stayed at zero;
    -- doing the arithmetic on the way out is exact and needs no job.
    if tg_op = 'UPDATE' and old.status_id is distinct from new.status_id then
        if not exists (select 1 from public.task_statuses s
                       where s.id = old.status_id and s.key = 'blocked')
           and exists (select 1 from public.task_statuses s
                       where s.id = new.status_id and s.key = 'blocked') then
            new.blocked_since := now();
        elsif exists (select 1 from public.task_statuses s
                      where s.id = old.status_id and s.key = 'blocked')
             and not exists (select 1 from public.task_statuses s
                             where s.id = new.status_id and s.key = 'blocked') then
            new.blocked_seconds := old.blocked_seconds
                + greatest(0, extract(epoch from (now() - coalesce(old.blocked_since, now())))::bigint);
            new.blocked_since := null;
        end if;
    end if;

    return new;
end;
$function$
;

--
-- Row level security (§10)
--
  create policy "Dependencies are closed by users who can see either end"
  on "public"."task_dependencies"
  as permissive
  for update
  to authenticated
using ((public.can_see_task(source_task_id) OR public.can_see_task(target_task_id)))
with check ((public.can_see_task(source_task_id) OR public.can_see_task(target_task_id)));



  create policy "Dependencies are created by users who can see both ends"
  on "public"."task_dependencies"
  as permissive
  for insert
  to authenticated
with check ((public.can_see_task(source_task_id) AND public.can_see_task(target_task_id)));



  create policy "Dependencies are readable from either end"
  on "public"."task_dependencies"
  as permissive
  for select
  to authenticated
using ((public.can_see_task(source_task_id) OR public.can_see_task(target_task_id)));


--
-- Triggers
--

CREATE TRIGGER task_dependencies_audit AFTER INSERT OR UPDATE ON public.task_dependencies FOR EACH ROW EXECUTE FUNCTION public.task_dependencies_audit();

CREATE TRIGGER task_dependencies_before_insert BEFORE INSERT ON public.task_dependencies FOR EACH ROW EXECUTE FUNCTION public.task_dependencies_before_insert();

CREATE TRIGGER task_dependencies_no_cycle BEFORE INSERT OR UPDATE ON public.task_dependencies FOR EACH ROW EXECUTE FUNCTION public.assert_no_dependency_cycle();

CREATE TRIGGER tasks_unblock_dependents AFTER UPDATE ON public.tasks FOR EACH ROW WHEN ((old.status_id IS DISTINCT FROM new.status_id)) EXECUTE FUNCTION public.tasks_unblock_dependents();


--
-- Grants (§17.3 P1). No `delete`: an edge is closed with `removed_at`.
--
grant select, insert, update on table "public"."task_dependencies" to "authenticated";
grant all on table "public"."task_dependencies" to "service_role";
revoke all on table "public"."task_dependencies" from "anon";

grant usage, select on sequence "public"."task_dependencies_id_seq" to "authenticated";
grant all on sequence "public"."task_dependencies_id_seq" to "service_role";

-- Read-only and useful to the UI ("why is this blocked?").
grant all on function "public"."task_has_open_blockers"(bigint) to "authenticated";
grant all on function "public"."task_has_open_blockers"(bigint) to "service_role";

grant all on function "public"."set_task_status_system"(bigint, text, public.task_event_type, jsonb) to "service_role";
grant all on function "public"."assert_no_dependency_cycle"() to "service_role";
grant all on function "public"."task_dependencies_before_insert"() to "service_role";
grant all on function "public"."task_dependencies_audit"() to "service_role";
grant all on function "public"."tasks_unblock_dependents"() to "service_role";
