--
-- Anti-fatigue rules for reminders (§9.5).
--
-- The proposal calls these non-negotiable: "a reminder system without
-- throttling is uninstalled within a week". Until the external-channel worker
-- shipped this was theoretical — nothing left the database. Now that email
-- actually sends, an unthrottled reminder rule is a way to make somebody mute
-- the product.
--
-- The design rule that shapes everything below: **a suppressed notification is
-- still a row**. Quiet hours and digest mode DEFER `scheduled_for`; a muted
-- channel or a duplicate is inserted as `skipped` with the reason. Never a
-- silent non-insert — that is exactly the invisible failure O6 exists to
-- remove, and it would make "why did I not get pinged?" unanswerable.
--
-- Hand-written, ADD-only apart from replacing two functions: no column of
-- `public.tasks` changes, so `db diff` cannot drop the views that read it.
--

--
-- 1. One row per user. Absent means "the defaults", so nobody has to be
--    backfilled and a new hire behaves sensibly on day one.
--
create table public.notification_preferences (
    id          bigint generated by default as identity primary key,
    sales_id    bigint not null unique references public.sales(id) on delete cascade,

    -- Quiet hours are expressed in the user's own timezone; storing them as
    -- `time` plus a zone is what makes "no pings before 08:00" mean the same
    -- thing in Bogota and in Madrid.
    timezone    text not null default 'UTC',
    quiet_hours_start time,
    quiet_hours_end   time,

    -- Digest: one message at a fixed hour instead of N pings through the day.
    digest_mode boolean not null default false,
    digest_at   time not null default '08:00',

    -- Per-channel opt-out. Per-EVENT-TYPE preferences are deliberately not
    -- modelled yet: every row in the outbox comes from a reminder today, so a
    -- second axis would have exactly one value to key on (YAGNI). Add it when
    -- automations start writing notifications (Phase 3).
    muted_channels public.reminder_channel[] not null default '{}',

    -- Hard ceiling on deliveries per rolling hour, enforced at claim time.
    max_per_hour integer not null default 20 check (max_per_hour > 0),

    -- "Same task, several rules fired" collapses inside this window.
    dedupe_window_minutes integer not null default 60
        check (dedupe_window_minutes >= 0),

    created_at  timestamp with time zone not null default now(),
    updated_at  timestamp with time zone not null default now()
);

create index notification_preferences_sales_id_idx
    on public.notification_preferences (sales_id);

alter table public.notification_preferences enable row level security;

create policy "Notification preferences are readable by their owner"
    on public.notification_preferences for select to authenticated
    using (sales_id = (select public.current_sale_id())
           or (select public.can_manage_all()));

-- Deliberately owner-only for writes, including admins: quiet hours are a
-- personal setting, and an admin silently muting somebody's reminders would be
-- indistinguishable from a bug.
create policy "Notification preferences are written by their owner"
    on public.notification_preferences for all to authenticated
    using (sales_id = (select public.current_sale_id()))
    with check (sales_id = (select public.current_sale_id()));

grant select, insert, update, delete
    on table public.notification_preferences to authenticated;
grant all on table public.notification_preferences to service_role;
grant usage, select on sequence public.notification_preferences_id_seq to authenticated;
grant all on sequence public.notification_preferences_id_seq to service_role;

create or replace trigger notification_preferences_set_updated_at
    before update on public.notification_preferences
    for each row execute function public.set_updated_at();

--
-- 2. Reading the preferences, with the defaults materialized for a user who
--    never opened the settings screen.
--
-- The literals here MUST match the column defaults above. `task_module_
-- notification_prefs.test.sql` asserts they do, so the duplication is a tested
-- invariant rather than a trap.
--
create or replace function public.notification_prefs_for(p_sales_id bigint)
returns public.notification_preferences
    language plpgsql stable security definer
    set search_path to ''
as $$
declare
    v_prefs public.notification_preferences;
begin
    select * into v_prefs
      from public.notification_preferences
     where sales_id = p_sales_id;

    if found then
        return v_prefs;
    end if;

    v_prefs.sales_id              := p_sales_id;
    v_prefs.timezone              := 'UTC';
    v_prefs.digest_mode           := false;
    v_prefs.digest_at             := '08:00';
    v_prefs.muted_channels        := '{}';
    v_prefs.max_per_hour          := 20;
    v_prefs.dedupe_window_minutes := 60;

    return v_prefs;
end;
$$;

--
-- 3. When may this actually be sent?
--
-- Handles the wrap-around case, which is the one people actually configure:
-- 22:00–07:00 is a window that crosses midnight, and treating it as a plain
-- `between` silences the whole day instead of the night.
--
create or replace function public.next_allowed_send_at(
    p_at          timestamp with time zone,
    p_timezone    text,
    p_quiet_start time,
    p_quiet_end   time
)
returns timestamp with time zone
    language plpgsql immutable
    set search_path to ''
as $$
declare
    v_local timestamp;
    v_time  time;
    v_day   date;
begin
    if p_quiet_start is null or p_quiet_end is null
       or p_quiet_start = p_quiet_end then
        return p_at;
    end if;

    v_local := p_at at time zone coalesce(p_timezone, 'UTC');
    v_time  := v_local::time;
    v_day   := v_local::date;

    if p_quiet_start < p_quiet_end then
        -- A window inside one day, e.g. 13:00–14:00.
        if v_time >= p_quiet_start and v_time < p_quiet_end then
            return (v_day + p_quiet_end) at time zone coalesce(p_timezone, 'UTC');
        end if;
    else
        -- A window that crosses midnight, e.g. 22:00–07:00.
        if v_time >= p_quiet_start then
            return ((v_day + 1) + p_quiet_end) at time zone coalesce(p_timezone, 'UTC');
        elsif v_time < p_quiet_end then
            return (v_day + p_quiet_end) at time zone coalesce(p_timezone, 'UTC');
        end if;
    end if;

    return p_at;
end;
$$;

--
-- 4. The next digest slot at or after a given instant.
--
create or replace function public.next_digest_at(
    p_at        timestamp with time zone,
    p_timezone  text,
    p_digest_at time
)
returns timestamp with time zone
    language plpgsql immutable
    set search_path to ''
as $$
declare
    v_local timestamp;
    v_slot  timestamp;
begin
    v_local := p_at at time zone coalesce(p_timezone, 'UTC');
    v_slot  := v_local::date + coalesce(p_digest_at, '08:00'::time);

    if v_slot < v_local then
        v_slot := v_slot + interval '1 day';
    end if;

    return v_slot at time zone coalesce(p_timezone, 'UTC');
end;
$$;

revoke all on function public.notification_prefs_for(bigint) from public, anon;
grant all on function public.notification_prefs_for(bigint) to authenticated, service_role;
grant all on function public.next_allowed_send_at(timestamp with time zone, text, time, time) to authenticated, service_role;
grant all on function public.next_digest_at(timestamp with time zone, text, time) to authenticated, service_role;

--
-- 5. The dispatcher now consults the recipient before queueing.
--
-- In-app is exempt from quiet hours, digest and the hourly cap on purpose: it
-- is a badge inside a page the user chose to open, not something that buzzes a
-- phone at 03:00. It still honours an explicit mute — opting out has to mean
-- opting out.
--
create or replace function public.dispatch_due_reminders(p_limit integer default 200)
returns integer
    language plpgsql security definer
    set search_path to ''
as $$
declare
    v_reminder   public.task_reminders;
    v_occurrence timestamp with time zone;
    v_recipient  bigint;
    v_channel    public.reminder_channel;
    v_task       public.tasks;
    v_is_open    boolean;
    v_next       timestamp with time zone;
    v_sent       integer := 0;
    v_prefs      public.notification_preferences;
    v_send_at    timestamp with time zone;
    v_status     text;
    v_error      text;
begin
    for v_reminder in
        select r.*
          from public.task_reminders r
         where r.is_active
           and r.next_fire_at is not null
           and r.next_fire_at <= now()
         order by r.next_fire_at
         limit p_limit
           for update skip locked
    loop
        v_occurrence := v_reminder.next_fire_at;

        select * into v_task from public.tasks where id = v_reminder.task_id;
        select s.is_open into v_is_open
          from public.task_statuses s where s.id = v_task.status_id;

        -- A closed or deleted task stops chasing its owner. `stop_on_complete`
        -- is the default precisely because the opposite is how a reminder
        -- system gets muted (§9.5).
        if v_task.id is null
           or v_task.deleted_at is not null
           or (v_reminder.stop_on_complete and not coalesce(v_is_open, false)) then
            update public.task_reminders
               set is_active = false, next_fire_at = null
             where id = v_reminder.id;
            continue;
        end if;

        for v_recipient in
            select * from public.reminder_recipient_ids(to_jsonb(v_reminder))
        loop
            v_prefs := public.notification_prefs_for(v_recipient);

            foreach v_channel in array v_reminder.channels loop
                v_send_at := v_occurrence;
                v_status  := 'queued';
                v_error   := null;

                if v_channel = any (v_prefs.muted_channels) then
                    v_status := 'skipped';
                    v_error  := format('channel %s muted by recipient', v_channel);

                elsif v_channel <> 'in_app' then
                    -- Several rules firing on one task inside the window are
                    -- one ping, not N. The row still exists, marked, so the
                    -- suppression is auditable.
                    if v_prefs.dedupe_window_minutes > 0
                       and exists (select 1 from public.task_notifications n
                                    where n.task_id = v_reminder.task_id
                                      and n.recipient_id = v_recipient
                                      and n.channel = v_channel
                                      and n.status <> 'skipped'
                                      and n.created_at > now()
                                          - make_interval(mins => v_prefs.dedupe_window_minutes))
                    then
                        v_status := 'skipped';
                        v_error  := 'deduplicated: same task already notified in this window';
                    else
                        v_send_at := public.next_allowed_send_at(
                            v_send_at, v_prefs.timezone,
                            v_prefs.quiet_hours_start, v_prefs.quiet_hours_end);

                        if v_prefs.digest_mode then
                            v_send_at := greatest(
                                v_send_at,
                                public.next_digest_at(v_send_at, v_prefs.timezone,
                                                      v_prefs.digest_at));
                        end if;
                    end if;
                end if;

                insert into public.task_notifications (
                    reminder_id, task_id, recipient_id, channel, scheduled_for,
                    title, body, dedupe_key, status,
                    -- An in-app notification IS the row: inserting it delivers
                    -- it, because Realtime pushes it to the client. Only the
                    -- external channels need a worker to move them along.
                    sent_at, delivered_at, error)
                values (
                    v_reminder.id, v_reminder.task_id, v_recipient, v_channel,
                    v_send_at, v_task.title,
                    coalesce(nullif(btrim(v_reminder.message_template), ''),
                             v_task.description),
                    format('%s:%s:%s:%s', v_reminder.id,
                           extract(epoch from v_occurrence)::bigint,
                           v_recipient, v_channel),
                    case when v_status <> 'queued' then v_status
                         when v_channel = 'in_app' then 'delivered'
                         else 'queued' end,
                    case when v_status = 'queued' and v_channel = 'in_app' then now() end,
                    case when v_status = 'queued' and v_channel = 'in_app' then now() end,
                    v_error)
                on conflict (dedupe_key) do nothing;
            end loop;
        end loop;

        v_reminder.fired_count := v_reminder.fired_count + 1;
        v_next := public.compute_reminder_next_fire(
            to_jsonb(v_reminder), v_occurrence);

        update public.task_reminders
           set fired_count  = v_reminder.fired_count,
               next_fire_at = v_next,
               is_active    = (v_next is not null)
         where id = v_reminder.id;

        perform public.emit_task_event(
            v_reminder.task_id, 'reminder.sent', null, null, null,
            jsonb_build_object('reminder_id', v_reminder.id,
                               'occurrence', v_occurrence,
                               'channels', to_jsonb(v_reminder.channels)),
            null, 'system');

        v_sent := v_sent + 1;
    end loop;

    return v_sent;
end;
$$;

--
-- 6. The hourly cap, enforced where deliveries actually happen.
--
-- A capped row is simply not claimed this tick. It stays `queued` and is picked
-- up once older sends age out of the rolling window — a sliding throttle that
-- needs no extra write and no bookkeeping column.
--
-- The claim also reports whether the recipient is in digest mode, so the worker
-- can collapse their batch into one message instead of N.
--
-- Dropped first: adding `recipient_digest` changes the OUT row type, and
-- `create or replace` refuses that (SQLSTATE 42P13). Safe here because only
-- `service_role` was ever granted on it — no view or policy depends on it.
--
drop function if exists public.claim_task_notifications(public.reminder_channel[], integer);

create or replace function public.claim_task_notifications(
    p_channels public.reminder_channel[] default
        array['email', 'push', 'whatsapp', 'sms', 'webhook']::public.reminder_channel[],
    p_limit integer default 50
)
returns table (
    id            bigint,
    task_id       bigint,
    channel       public.reminder_channel,
    recipient_id  bigint,
    recipient_email text,
    recipient_name  text,
    recipient_digest boolean,
    title         text,
    body          text,
    scheduled_for timestamp with time zone,
    attempt       smallint,
    task_title    text,
    task_due_date timestamp with time zone
)
    language plpgsql security definer
    set search_path to ''
as $$
begin
    return query
    with claimed as (
        update public.task_notifications n
           set status  = 'sending',
               attempt = n.attempt + 1
         where n.id in (
                   select c.id
                     from public.task_notifications c
                    where c.status = 'queued'
                      and c.channel = any (p_channels)
                      and c.scheduled_for <= now()
                      and (select count(*)
                             from public.task_notifications s
                            where s.recipient_id = c.recipient_id
                              and s.status in ('sent', 'delivered')
                              and s.sent_at > now() - interval '1 hour')
                          < (public.notification_prefs_for(c.recipient_id)).max_per_hour
                    order by c.scheduled_for
                    limit p_limit
                      for update skip locked)
        returning n.*
    )
    select c.id, c.task_id, c.channel, c.recipient_id,
           -- `sales.email` is citext; the declared return type is text, and
           -- Postgres compares those structurally, not by implicit cast.
           s.email::text,
           nullif(btrim(concat_ws(' ', s.first_name, s.last_name)), ''),
           (public.notification_prefs_for(c.recipient_id)).digest_mode,
           c.title, c.body, c.scheduled_for, c.attempt,
           t.title, t.due_date
      from claimed c
      join public.sales s on s.id = c.recipient_id
      join public.tasks t on t.id = c.task_id;
end;
$$;

revoke all on function public.claim_task_notifications(public.reminder_channel[], integer) from public, anon, authenticated;
grant all on function public.claim_task_notifications(public.reminder_channel[], integer) to service_role;

notify pgrst, 'reload schema';
