--
-- Reminders and the notification outbox (proposal §9, deliverable 2.5).
--
-- Hand-written rather than `db diff`-generated: this migration only ADDS
-- objects and never touches `public.tasks`, so it cannot trip the drop-view
-- trap that an auto-generated diff hits whenever a column is added to a table
-- the summary views read.
--

create type public.reminder_channel as enum
    ('in_app', 'email', 'push', 'whatsapp', 'sms', 'webhook');

create table public.task_reminders (
    id             bigint generated by default as identity primary key,
    task_id        bigint not null references public.tasks(id) on delete restrict,
    created_by     bigint not null references public.sales(id),
    created_at     timestamp with time zone not null default now(),

    schedule_kind  text not null check (schedule_kind in
                     ('absolute', 'relative_before_due', 'relative_after_due', 'recurring')),
    absolute_at    timestamp with time zone,
    offset_minutes integer,
    rrule          text,
    timezone       text not null default 'UTC',
    until_at       timestamp with time zone,
    max_occurrences integer,

    channels       public.reminder_channel[] not null default '{in_app}',
    recipients     text not null default 'owner'
                   check (recipients in ('owner', 'assignees', 'watchers', 'all', 'custom')),
    custom_recipients bigint[],
    message_template text,

    is_active      boolean not null default true,
    next_fire_at   timestamp with time zone,
    fired_count    integer not null default 0,
    stop_on_complete boolean not null default true,

    constraint task_reminders_schedule_shape check (
        (schedule_kind = 'absolute' and absolute_at is not null)
        or (schedule_kind in ('relative_before_due', 'relative_after_due')
            and offset_minutes is not null and offset_minutes >= 0)
        or (schedule_kind = 'recurring' and btrim(coalesce(rrule, '')) <> '')
    ),
    constraint task_reminders_channels_not_empty
        check (array_length(channels, 1) >= 1),
    constraint task_reminders_custom_recipients check (
        recipients <> 'custom'
        or coalesce(array_length(custom_recipients, 1), 0) >= 1
    )
);

create index task_reminders_due
    on public.task_reminders (next_fire_at)
    where is_active and next_fire_at is not null;

create index task_reminders_task
    on public.task_reminders (task_id)
    where is_active;

create table public.task_notifications (
    id            bigint generated by default as identity primary key,
    reminder_id   bigint references public.task_reminders(id),
    task_id       bigint not null references public.tasks(id) on delete restrict,
    recipient_id  bigint not null references public.sales(id),
    channel       public.reminder_channel not null,
    scheduled_for timestamp with time zone not null,
    sent_at       timestamp with time zone,
    delivered_at  timestamp with time zone,
    read_at       timestamp with time zone,
    acknowledged_at timestamp with time zone,
    title         text,
    body          text,
    status        text not null default 'queued'
                  check (status in ('queued', 'sending', 'sent', 'delivered',
                                    'failed', 'bounced', 'skipped', 'canceled')),
    attempt       smallint not null default 0,
    error         text,
    provider_message_id text,
    dedupe_key    text unique,
    created_at    timestamp with time zone not null default now()
);

create index task_notifications_outbox
    on public.task_notifications (status, scheduled_for)
    where status in ('queued', 'sending');

create index task_notifications_inbox
    on public.task_notifications (recipient_id, created_at desc)
    where channel = 'in_app' and read_at is null;

create index task_notifications_task
    on public.task_notifications (task_id, created_at desc);

--
-- Functions (see supabase/schemas/02_functions.sql for the commentary)
--

create or replace function public.next_rrule_occurrence(
    p_rrule    text,
    p_after    timestamp with time zone,
    p_timezone text default 'UTC',
    p_anchor   timestamp with time zone default null
) returns timestamp with time zone
    language plpgsql stable
    set search_path to ''
as $$
declare
    v_part       text;
    v_key        text;
    v_val        text;
    v_freq       text := 'DAILY';
    v_interval   integer := 1;
    v_byhour     integer[];
    v_byminute   integer[];
    v_byday      text[];
    v_bymonthday integer[];
    v_tz         text := coalesce(nullif(btrim(p_timezone), ''), 'UTC');
    v_anchor     timestamp with time zone := coalesce(p_anchor, p_after);
    v_anchor_local timestamp;
    v_after_local  timestamp;
    v_day        date;
    v_hour       integer;
    v_minute     integer;
    v_cand       timestamp with time zone;
    v_i          integer;
    v_dow        text;
    v_dow_names  text[] := array['SU', 'MO', 'TU', 'WE', 'TH', 'FR', 'SA'];
begin
    if btrim(coalesce(p_rrule, '')) = '' then
        return null;
    end if;

    foreach v_part in array string_to_array(
        upper(replace(btrim(p_rrule), ' ', '')), ';')
    loop
        v_key := split_part(v_part, '=', 1);
        v_val := split_part(v_part, '=', 2);
        if v_val = '' then
            continue;
        end if;
        case v_key
            when 'FREQ'       then v_freq := v_val;
            when 'INTERVAL'   then v_interval := greatest(1, v_val::integer);
            when 'BYHOUR'     then v_byhour := string_to_array(v_val, ',')::integer[];
            when 'BYMINUTE'   then v_byminute := string_to_array(v_val, ',')::integer[];
            when 'BYDAY'      then v_byday := string_to_array(v_val, ',');
            when 'BYMONTHDAY' then v_bymonthday := string_to_array(v_val, ',')::integer[];
            else null;
        end case;
    end loop;

    v_anchor_local := timezone(v_tz, v_anchor);
    v_after_local  := timezone(v_tz, p_after);
    v_byminute := coalesce(
        (select array_agg(x order by x) from unnest(v_byminute) x), array[0]);

    if v_freq = 'HOURLY' and v_byhour is null then
        v_cand := timezone(v_tz, date_trunc('hour', v_anchor_local)
                                 + make_interval(mins => v_byminute[1]));
        while v_cand <= p_after loop
            v_cand := v_cand + make_interval(hours => v_interval);
        end loop;
        return v_cand;
    end if;

    if v_byhour is null then
        v_byhour := array[extract(hour from v_anchor_local)::integer];
        if array_length(v_byminute, 1) = 1 and v_byminute[1] = 0 then
            v_byminute := array[extract(minute from v_anchor_local)::integer];
        end if;
    else
        v_byhour := (select array_agg(x order by x) from unnest(v_byhour) x);
    end if;

    for v_i in 0..400 loop
        v_day := v_after_local::date + v_i;

        if v_freq = 'WEEKLY' then
            v_dow := v_dow_names[extract(dow from v_day)::integer + 1];
            if v_byday is not null then
                if not (v_dow = any(v_byday)) then
                    continue;
                end if;
            elsif extract(dow from v_day) <> extract(dow from v_anchor_local) then
                continue;
            end if;
            if v_interval > 1
               and (floor((v_day - v_anchor_local::date) / 7.0)::integer % v_interval) <> 0 then
                continue;
            end if;

        elsif v_freq = 'MONTHLY' then
            if v_bymonthday is not null then
                if not (extract(day from v_day)::integer = any(v_bymonthday)) then
                    continue;
                end if;
            elsif extract(day from v_day) <> extract(day from v_anchor_local) then
                continue;
            end if;
            if v_interval > 1
               and (((extract(year from v_day)::integer * 12 + extract(month from v_day)::integer)
                     - (extract(year from v_anchor_local)::integer * 12
                        + extract(month from v_anchor_local)::integer)) % v_interval) <> 0 then
                continue;
            end if;

        elsif v_freq = 'DAILY' then
            if v_interval > 1
               and ((v_day - v_anchor_local::date) % v_interval) <> 0 then
                continue;
            end if;
        end if;

        foreach v_hour in array v_byhour loop
            foreach v_minute in array v_byminute loop
                v_cand := timezone(v_tz, v_day + make_time(v_hour, v_minute, 0));
                if v_cand > p_after then
                    return v_cand;
                end if;
            end loop;
        end loop;
    end loop;

    return null;
end;
$$;

create or replace function public.compute_reminder_next_fire(
    p_reminder jsonb,
    p_after    timestamp with time zone default null
) returns timestamp with time zone
    language plpgsql stable security definer
    set search_path to ''
as $$
declare
    v_after    timestamp with time zone := coalesce(p_after, now());
    v_kind     text := p_reminder ->> 'schedule_kind';
    v_fired    integer := coalesce((p_reminder ->> 'fired_count')::integer, 0);
    v_max      integer := (p_reminder ->> 'max_occurrences')::integer;
    v_until    timestamp with time zone := (p_reminder ->> 'until_at')::timestamp with time zone;
    v_offset   integer := (p_reminder ->> 'offset_minutes')::integer;
    v_due      timestamp with time zone;
    v_next     timestamp with time zone;
begin
    if v_max is not null and v_fired >= v_max then
        return null;
    end if;

    if v_kind = 'absolute' then
        if v_fired = 0 then
            v_next := (p_reminder ->> 'absolute_at')::timestamp with time zone;
        end if;

    elsif v_kind in ('relative_before_due', 'relative_after_due') then
        select t.due_date into v_due
          from public.tasks t
         where t.id = (p_reminder ->> 'task_id')::bigint;

        if v_due is null or v_fired > 0 then
            v_next := null;
        elsif v_kind = 'relative_before_due' then
            v_next := v_due - make_interval(mins => v_offset);
            if v_next <= v_after then
                v_next := null;
            end if;
        else
            v_next := v_due + make_interval(mins => v_offset);
        end if;

    elsif v_kind = 'recurring' then
        v_next := public.next_rrule_occurrence(
            p_reminder ->> 'rrule',
            greatest(v_after, coalesce(
                (p_reminder ->> 'created_at')::timestamp with time zone, v_after)),
            coalesce(p_reminder ->> 'timezone', 'UTC'),
            (p_reminder ->> 'created_at')::timestamp with time zone);
    end if;

    if v_next is not null and v_until is not null and v_next > v_until then
        return null;
    end if;

    return v_next;
end;
$$;

create or replace function public.reminder_recipient_ids(p_reminder jsonb)
returns setof bigint
    language sql stable security definer
    set search_path to ''
as $$
    select distinct q.sales_id
    from (
        select t.owner_sales_id as sales_id
          from public.tasks t
         where t.id = (p_reminder ->> 'task_id')::bigint
           and (p_reminder ->> 'recipients') in ('owner', 'assignees', 'all')

        union all

        select a.sales_id
          from public.task_assignments a
         where a.task_id = (p_reminder ->> 'task_id')::bigint
           and a.unassigned_at is null
           and a.sales_id is not null
           and ((p_reminder ->> 'recipients') = 'all'
             or ((p_reminder ->> 'recipients') = 'assignees'
                 and a.role in ('owner', 'collaborator'))
             or ((p_reminder ->> 'recipients') = 'watchers' and a.role = 'watcher'))

        union all

        select tm.sales_id
          from public.task_assignments a
          join public.team_members tm on tm.team_id = a.team_id
         where a.task_id = (p_reminder ->> 'task_id')::bigint
           and a.unassigned_at is null
           and a.team_id is not null
           and (p_reminder ->> 'recipients') in ('assignees', 'all')

        union all

        select e.value::bigint
          from jsonb_array_elements_text(
                 coalesce(p_reminder -> 'custom_recipients', '[]'::jsonb)
               ) as e(value)
         where (p_reminder ->> 'recipients') = 'custom'
    ) q
    join public.sales s on s.id = q.sales_id and s.disabled is not true;
$$;

create or replace function public.dispatch_due_reminders(p_limit integer default 200)
returns integer
    language plpgsql security definer
    set search_path to ''
as $$
declare
    v_reminder   public.task_reminders;
    v_occurrence timestamp with time zone;
    v_recipient  bigint;
    v_channel    public.reminder_channel;
    v_task       public.tasks;
    v_is_open    boolean;
    v_next       timestamp with time zone;
    v_sent       integer := 0;
begin
    for v_reminder in
        select r.*
          from public.task_reminders r
         where r.is_active
           and r.next_fire_at is not null
           and r.next_fire_at <= now()
         order by r.next_fire_at
         limit p_limit
           for update skip locked
    loop
        v_occurrence := v_reminder.next_fire_at;

        select * into v_task from public.tasks where id = v_reminder.task_id;
        select s.is_open into v_is_open
          from public.task_statuses s where s.id = v_task.status_id;

        if v_task.id is null
           or v_task.deleted_at is not null
           or (v_reminder.stop_on_complete and not coalesce(v_is_open, false)) then
            update public.task_reminders
               set is_active = false, next_fire_at = null
             where id = v_reminder.id;
            continue;
        end if;

        for v_recipient in
            select * from public.reminder_recipient_ids(to_jsonb(v_reminder))
        loop
            foreach v_channel in array v_reminder.channels loop
                insert into public.task_notifications (
                    reminder_id, task_id, recipient_id, channel, scheduled_for,
                    title, body, dedupe_key, status, sent_at, delivered_at)
                values (
                    v_reminder.id, v_reminder.task_id, v_recipient, v_channel,
                    v_occurrence, v_task.title,
                    coalesce(nullif(btrim(v_reminder.message_template), ''),
                             v_task.description),
                    format('%s:%s:%s:%s', v_reminder.id,
                           extract(epoch from v_occurrence)::bigint,
                           v_recipient, v_channel),
                    case when v_channel = 'in_app' then 'delivered' else 'queued' end,
                    case when v_channel = 'in_app' then now() end,
                    case when v_channel = 'in_app' then now() end)
                on conflict (dedupe_key) do nothing;
            end loop;
        end loop;

        v_reminder.fired_count := v_reminder.fired_count + 1;
        v_next := public.compute_reminder_next_fire(
            to_jsonb(v_reminder), v_occurrence);

        update public.task_reminders
           set fired_count  = v_reminder.fired_count,
               next_fire_at = v_next,
               is_active    = (v_next is not null)
         where id = v_reminder.id;

        perform public.emit_task_event(
            v_reminder.task_id, 'reminder.sent', null, null, null,
            jsonb_build_object('reminder_id', v_reminder.id,
                               'occurrence', v_occurrence,
                               'channels', to_jsonb(v_reminder.channels)),
            null, 'system');

        v_sent := v_sent + 1;
    end loop;

    return v_sent;
end;
$$;

create or replace function public.task_reminders_before_write() returns trigger
    language plpgsql security definer
    set search_path to ''
as $$
begin
    if tg_op = 'INSERT' then
        new.created_by := coalesce((select public.current_sale_id()), new.created_by);
        new.next_fire_at := public.compute_reminder_next_fire(to_jsonb(new), now());
        new.is_active := new.is_active and new.next_fire_at is not null;
        return new;
    end if;

    if (new.schedule_kind, new.absolute_at, new.offset_minutes, new.rrule,
        new.timezone, new.until_at, new.max_occurrences)
       is distinct from
       (old.schedule_kind, old.absolute_at, old.offset_minutes, old.rrule,
        old.timezone, old.until_at, old.max_occurrences)
       or (new.is_active and not old.is_active) then
        new.next_fire_at := public.compute_reminder_next_fire(to_jsonb(new), now());
    end if;

    if not new.is_active then
        new.next_fire_at := null;
    end if;

    return new;
end;
$$;

create or replace function public.task_reminders_audit() returns trigger
    language plpgsql security definer
    set search_path to ''
as $$
declare
    v_actor bigint := (select public.current_sale_id());
    v_meta  jsonb;
begin
    v_meta := jsonb_build_object(
        'reminder_id', new.id,
        'schedule_kind', new.schedule_kind,
        'channels', to_jsonb(new.channels),
        'recipients', new.recipients,
        'next_fire_at', new.next_fire_at);

    if tg_op = 'INSERT' then
        perform public.emit_task_event(
            new.task_id, 'reminder.created', v_actor, null, null, v_meta, null,
            case when v_actor is null then 'system' else 'user' end);
    elsif old.is_active and not new.is_active then
        perform public.emit_task_event(
            new.task_id, 'reminder.canceled', v_actor, null, null, v_meta, null,
            case when v_actor is null then 'system' else 'user' end);
    elsif new.fired_count = old.fired_count then
        perform public.emit_task_event(
            new.task_id, 'reminder.updated', v_actor, null, null, v_meta, null,
            case when v_actor is null then 'system' else 'user' end);
    end if;

    return new;
end;
$$;

create or replace function public.task_notifications_audit() returns trigger
    language plpgsql security definer
    set search_path to ''
as $$
begin
    if new.status in ('failed', 'bounced') and old.status is distinct from new.status then
        perform public.emit_task_event(
            new.task_id, 'reminder.failed', null, null, null,
            jsonb_build_object('notification_id', new.id,
                               'channel', new.channel,
                               'recipient_id', new.recipient_id,
                               'attempt', new.attempt,
                               'error', new.error),
            null, 'system');
    elsif new.acknowledged_at is not null and old.acknowledged_at is null then
        perform public.emit_task_event(
            new.task_id, 'reminder.acknowledged', new.recipient_id, null, null,
            jsonb_build_object('notification_id', new.id, 'channel', new.channel),
            null, 'user');
    end if;

    return new;
end;
$$;

create or replace function public.tasks_refresh_relative_reminders() returns trigger
    language plpgsql security definer
    set search_path to ''
as $$
declare
    v_reminder public.task_reminders;
begin
    for v_reminder in
        select r.* from public.task_reminders r
         where r.task_id = new.id
           and r.schedule_kind in ('relative_before_due', 'relative_after_due')
           and r.fired_count = 0
    loop
        update public.task_reminders
           set next_fire_at = public.compute_reminder_next_fire(
                                  to_jsonb(v_reminder), now())
         where id = v_reminder.id;
    end loop;

    return new;
end;
$$;

create or replace function public.tasks_cancel_reminders_on_close() returns trigger
    language plpgsql security definer
    set search_path to ''
as $$
declare
    v_is_open boolean;
begin
    select s.is_open into v_is_open
      from public.task_statuses s where s.id = new.status_id;

    if coalesce(v_is_open, false) and new.deleted_at is null then
        return new;
    end if;

    update public.task_notifications
       set status = 'canceled'
     where task_id = new.id
       and status in ('queued', 'sending');

    update public.task_reminders
       set is_active = false, next_fire_at = null
     where task_id = new.id
       and is_active
       and (stop_on_complete or new.deleted_at is not null);

    return new;
end;
$$;

--
-- Triggers
--

create or replace trigger task_reminders_before_write
    before insert or update on public.task_reminders
    for each row execute function public.task_reminders_before_write();

create or replace trigger task_reminders_audit
    after insert or update on public.task_reminders
    for each row execute function public.task_reminders_audit();

create or replace trigger task_notifications_audit
    after update on public.task_notifications
    for each row execute function public.task_notifications_audit();

create or replace trigger tasks_refresh_relative_reminders
    after update on public.tasks
    for each row
    when (old.due_date is distinct from new.due_date)
    execute function public.tasks_refresh_relative_reminders();

create or replace trigger tasks_cancel_reminders_on_close
    after update on public.tasks
    for each row
    when (old.status_id is distinct from new.status_id
       or old.deleted_at is distinct from new.deleted_at)
    execute function public.tasks_cancel_reminders_on_close();

--
-- Policies
--

alter table public.task_reminders enable row level security;

create policy "Reminders are readable with their task"
    on public.task_reminders for select to authenticated
    using (public.can_see_task(task_id));

create policy "Reminders are created by users who can see the task"
    on public.task_reminders for insert to authenticated
    with check (public.can_see_task(task_id));

create policy "Reminders are updated by users who can see the task"
    on public.task_reminders for update to authenticated
    using (public.can_see_task(task_id))
    with check (public.can_see_task(task_id));

alter table public.task_notifications enable row level security;

create policy "You read your own notifications"
    on public.task_notifications for select to authenticated
    using (recipient_id = (select public.current_sale_id()));

create policy "You acknowledge your own notifications"
    on public.task_notifications for update to authenticated
    using (recipient_id = (select public.current_sale_id()))
    with check (recipient_id = (select public.current_sale_id()));

--
-- Grants
--

grant all on function public.next_rrule_occurrence(text, timestamp with time zone, text, timestamp with time zone) to authenticated;
grant all on function public.next_rrule_occurrence(text, timestamp with time zone, text, timestamp with time zone) to service_role;
grant all on function public.compute_reminder_next_fire(jsonb, timestamp with time zone) to authenticated;
grant all on function public.compute_reminder_next_fire(jsonb, timestamp with time zone) to service_role;
grant all on function public.reminder_recipient_ids(jsonb) to service_role;
grant all on function public.dispatch_due_reminders(integer) to service_role;
grant all on function public.task_reminders_before_write() to service_role;
grant all on function public.task_reminders_audit() to service_role;
grant all on function public.task_notifications_audit() to service_role;
grant all on function public.tasks_refresh_relative_reminders() to service_role;
grant all on function public.tasks_cancel_reminders_on_close() to service_role;

grant select, insert, update on table public.task_reminders to authenticated;
grant all on table public.task_reminders to service_role;
revoke all on table public.task_reminders from anon;

grant select, update on table public.task_notifications to authenticated;
grant all on table public.task_notifications to service_role;
revoke all on table public.task_notifications from anon;

grant usage, select on sequence public.task_reminders_id_seq to authenticated;
grant all on sequence public.task_reminders_id_seq to service_role;
grant all on sequence public.task_notifications_id_seq to service_role;

notify pgrst, 'reload schema';
