-- Task module — attachments and comment reactions (§3.2, §8.2, §17.3).
--
-- Phase 2.3 of docs/proposals/enterprise-task-module.md. Three things:
--
--   1. `task_attachments` — file metadata for both task-level and
--      comment-level files, with the counter and the audit events the rest of
--      the module already gets.
--   2. A private `task-attachments` storage bucket. The Phase 1 hardening
--      (20260803182000) path-scoped task files inside the `attachments`
--      bucket, but that bucket is PUBLIC (see the initial migration), so any
--      object in it is served to anybody holding the URL, signed in or not.
--      Policies on a public bucket gate the API and leave the object path
--      open, so task files move to a bucket that is actually private and are
--      read through short-lived signed URLs.
--   3. A surrogate `id` on `task_comment_reactions`, which shipped with a
--      composite primary key that PostgREST and react-admin cannot address —
--      un-reacting is a delete by id.
--
-- Hand-written rather than `db diff`-generated, and additive on `public.tasks`
-- (it only reads it), so it does not trigger the drop-view cascade that a
-- generated diff produces for every view reading `tasks`.


--
-- 1. Attachments
--

create table "public"."task_attachments" (
    "id" bigint generated by default as identity not null,
    "task_id" bigint not null,
    "comment_id" bigint,
    "storage_path" text not null,
    "file_name" text not null,
    "mime_type" text,
    "size_bytes" bigint,
    "checksum" text,
    "uploaded_by" bigint not null,
    "uploaded_at" timestamp with time zone not null default now(),
    "deleted_at" timestamp with time zone,
    "deleted_by" bigint
);


alter table "public"."task_attachments" enable row level security;

CREATE UNIQUE INDEX task_attachments_pkey ON public.task_attachments USING btree (id);

CREATE INDEX task_attachments_task ON public.task_attachments USING btree (task_id, uploaded_at) WHERE (deleted_at IS NULL);

CREATE INDEX task_attachments_comment ON public.task_attachments USING btree (comment_id, uploaded_at) WHERE ((deleted_at IS NULL) AND (comment_id IS NOT NULL));

CREATE UNIQUE INDEX task_attachments_path_unique ON public.task_attachments USING btree (storage_path) WHERE (deleted_at IS NULL);

alter table "public"."task_attachments" add constraint "task_attachments_pkey" PRIMARY KEY using index "task_attachments_pkey";

alter table "public"."task_attachments" add constraint "task_attachments_file_name_not_blank" CHECK ((btrim(file_name) <> ''::text)) not valid;

alter table "public"."task_attachments" validate constraint "task_attachments_file_name_not_blank";

alter table "public"."task_attachments" add constraint "task_attachments_path_not_blank" CHECK ((btrim(storage_path) <> ''::text)) not valid;

alter table "public"."task_attachments" validate constraint "task_attachments_path_not_blank";

alter table "public"."task_attachments" add constraint "task_attachments_size_not_negative" CHECK (((size_bytes IS NULL) OR (size_bytes >= 0))) not valid;

alter table "public"."task_attachments" validate constraint "task_attachments_size_not_negative";

alter table "public"."task_attachments" add constraint "task_attachments_task_id_fkey" FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE RESTRICT not valid;

alter table "public"."task_attachments" validate constraint "task_attachments_task_id_fkey";

alter table "public"."task_attachments" add constraint "task_attachments_comment_id_fkey" FOREIGN KEY (comment_id) REFERENCES public.task_comments(id) ON DELETE RESTRICT not valid;

alter table "public"."task_attachments" validate constraint "task_attachments_comment_id_fkey";

alter table "public"."task_attachments" add constraint "task_attachments_uploaded_by_fkey" FOREIGN KEY (uploaded_by) REFERENCES public.sales(id) not valid;

alter table "public"."task_attachments" validate constraint "task_attachments_uploaded_by_fkey";

alter table "public"."task_attachments" add constraint "task_attachments_deleted_by_fkey" FOREIGN KEY (deleted_by) REFERENCES public.sales(id) not valid;

alter table "public"."task_attachments" validate constraint "task_attachments_deleted_by_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.refresh_attachment_counter(p_task_id bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
    update public.tasks t
       set attachment_count = a.total
      from (
        select count(*) as total
          from public.task_attachments
         where task_id = p_task_id
           and deleted_at is null
      ) a
     where t.id = p_task_id
       and t.attachment_count is distinct from a.total;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.task_attachments_before_insert()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
    v_comment_task bigint;
begin
    new.uploaded_by := coalesce((select public.current_sale_id()), new.uploaded_by);

    if new.storage_path !~ ('^' || new.task_id::text || '/.+') then
        raise exception 'attachment path % is not under task %',
            new.storage_path, new.task_id
            using errcode = 'check_violation';
    end if;

    if new.comment_id is not null then
        select task_id into v_comment_task
          from public.task_comments where id = new.comment_id;

        if v_comment_task is distinct from new.task_id then
            raise exception 'comment % belongs to another task', new.comment_id
                using errcode = 'check_violation';
        end if;
    end if;

    return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.task_attachments_before_update()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
    v_actor bigint := (select public.current_sale_id());
begin
    if old.deleted_at is null and new.deleted_at is not null then
        new.deleted_by := coalesce(v_actor, new.deleted_by);
    elsif new.deleted_at is null then
        new.deleted_by := null;
    end if;

    new.task_id      := old.task_id;
    new.comment_id   := old.comment_id;
    new.storage_path := old.storage_path;
    new.uploaded_by  := old.uploaded_by;
    new.uploaded_at  := old.uploaded_at;
    new.checksum     := old.checksum;

    return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.task_attachments_audit()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
    v_actor bigint := (select public.current_sale_id());
    v_type  public.task_event_type;
begin
    if tg_op = 'INSERT' then
        v_type := 'attachment.added';
    elsif old.deleted_at is null and new.deleted_at is not null then
        v_type := 'attachment.removed';
    elsif old.deleted_at is not null and new.deleted_at is null then
        v_type := 'attachment.added';
    else
        perform public.refresh_attachment_counter(new.task_id);
        return new;
    end if;

    perform public.emit_task_event(
        new.task_id, v_type,
        coalesce(v_actor, new.uploaded_by), null, null,
        jsonb_build_object('attachment_id', new.id,
                           'comment_id', new.comment_id,
                           'file_name', new.file_name,
                           'mime_type', new.mime_type,
                           'size_bytes', new.size_bytes),
        null,
        case when coalesce(v_actor, new.uploaded_by) is null
             then 'system' else 'user' end
    );

    perform public.refresh_attachment_counter(new.task_id);

    return new;
end;
$function$
;

--
-- Row level security (§3.2). No `for delete` policy: removal is the soft
-- delete done as an update, so the `attachment.removed` event keeps pointing
-- at a row that still exists.
--

  create policy "Attachments are readable with their task"
  on "public"."task_attachments"
  as permissive
  for select
  to authenticated
using (public.can_see_task(task_id));



  create policy "Attachments are written by users who can see the task"
  on "public"."task_attachments"
  as permissive
  for insert
  to authenticated
with check (public.can_see_task(task_id));



  create policy "Attachments are updated by users who can see the task"
  on "public"."task_attachments"
  as permissive
  for update
  to authenticated
using (public.can_see_task(task_id))
with check (public.can_see_task(task_id));


--
-- Triggers
--

CREATE TRIGGER task_attachments_before_insert BEFORE INSERT ON public.task_attachments FOR EACH ROW EXECUTE FUNCTION public.task_attachments_before_insert();

CREATE TRIGGER task_attachments_before_update BEFORE UPDATE ON public.task_attachments FOR EACH ROW EXECUTE FUNCTION public.task_attachments_before_update();

CREATE TRIGGER task_attachments_audit AFTER INSERT OR UPDATE ON public.task_attachments FOR EACH ROW EXECUTE FUNCTION public.task_attachments_audit();


--
-- Grants (§17.3 P1). No `delete`: removal is a soft delete via update.
--
grant select, insert, update on table "public"."task_attachments" to "authenticated";
grant all on table "public"."task_attachments" to "service_role";
revoke all on table "public"."task_attachments" from "anon";

grant usage, select on sequence "public"."task_attachments_id_seq" to "authenticated";
grant all on sequence "public"."task_attachments_id_seq" to "service_role";

grant all on function "public"."refresh_attachment_counter"(bigint) to "service_role";
grant all on function "public"."task_attachments_before_insert"() to "service_role";
grant all on function "public"."task_attachments_before_update"() to "service_role";
grant all on function "public"."task_attachments_audit"() to "service_role";


--
-- 2. Reactions get a surrogate key
--
-- The composite primary key is unaddressable through PostgREST's `?id=eq.…`,
-- which is how react-admin deletes a row. The triple stays unique, so the same
-- person still cannot register the same emoji twice on a comment.
--

alter table "public"."task_comment_reactions" drop constraint "task_comment_reactions_pkey";

drop index if exists "public"."task_comment_reactions_pkey";

alter table "public"."task_comment_reactions" add column "id" bigint generated by default as identity not null;

CREATE UNIQUE INDEX task_comment_reactions_pkey ON public.task_comment_reactions USING btree (id);

CREATE UNIQUE INDEX task_comment_reactions_unique ON public.task_comment_reactions USING btree (comment_id, sales_id, emoji);

alter table "public"."task_comment_reactions" add constraint "task_comment_reactions_pkey" PRIMARY KEY using index "task_comment_reactions_pkey";

alter table "public"."task_comment_reactions" add constraint "task_comment_reactions_unique" UNIQUE using index "task_comment_reactions_unique";

grant usage, select on sequence "public"."task_comment_reactions_id_seq" to "authenticated";
grant all on sequence "public"."task_comment_reactions_id_seq" to "service_role";


--
-- 3. A private bucket for task files (§17.3 P0)
--
-- A bucket row is data, not schema, so it is created here and not in
-- `07_storage.sql` — same reasoning as the pg_cron job in the reminder
-- scheduler migration.
--

insert into storage.buckets (id, name, public)
values ('task-attachments', 'task-attachments', false)
on conflict (id) do nothing;

drop policy if exists "Task attachments follow task visibility for reads" on storage.objects;
drop policy if exists "Task attachments can be added by visible-task users" on storage.objects;
drop policy if exists "Task attachments can be deleted by visible-task users" on storage.objects;
drop policy if exists "Note attachments remain available to authenticated users" on storage.objects;
drop policy if exists "Note attachments can be added by authenticated users" on storage.objects;
drop policy if exists "Note attachments can be deleted by authenticated users" on storage.objects;

create policy "Task attachments follow task visibility for reads"
    on storage.objects for select to authenticated
    using (
        bucket_id = 'task-attachments'
        and (storage.foldername(name))[1] ~ '^[0-9]+$'
        and public.can_see_task((storage.foldername(name))[1]::bigint)
    );

create policy "Task attachments can be added by visible-task users"
    on storage.objects for insert to authenticated
    with check (
        bucket_id = 'task-attachments'
        and (storage.foldername(name))[1] ~ '^[0-9]+$'
        and public.can_see_task((storage.foldername(name))[1]::bigint)
    );

create policy "Task attachments can be deleted by visible-task users"
    on storage.objects for delete to authenticated
    using (
        bucket_id = 'task-attachments'
        and (storage.foldername(name))[1] ~ '^[0-9]+$'
        and public.can_see_task((storage.foldername(name))[1]::bigint)
    );

-- Note attachments keep the public bucket and the behavior they had before the
-- Phase 1 hardening carved a `tasks/` prefix out of it: nothing lives under
-- that prefix any more.
create policy "Note attachments remain available to authenticated users"
    on storage.objects for select to authenticated
    using (bucket_id = 'attachments');

create policy "Note attachments can be added by authenticated users"
    on storage.objects for insert to authenticated
    with check (bucket_id = 'attachments');

create policy "Note attachments can be deleted by authenticated users"
    on storage.objects for delete to authenticated
    using (bucket_id = 'attachments');

notify pgrst, 'reload schema';
